### PR TITLE
Adding content-length header

### PR DESCRIPTION
**Pull request by nagarev**
## Description

Adding `Content-Length` header to `JSON-RPC` responses.

## Motivation and Context

`Content-Length` header should be included in all `JSON-RPC` responses to increase compatibility with some clients.

## How Has This Been Tested?

- Unit Tests
- Local Tests
- QA

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

* **Other information**:

N/A

### CODE REVIEW

**Comment by nagarev** [comment]
pipeline:run

**Review by Vovchyk — DISMISSED** [review]

**Comment by nagarev** [comment]
pipeline:run

**Comment by nagarev** [comment]
pipeline:run

**Comment by nagarev** [comment]
pipeline:run

**Comment by nagarev** [comment]
pipeline:run

**Comment by nagarev** [comment]
pipeline:run

**Comment by nagarev** [comment]
pipeline:run

**Review by Vovchyk — DISMISSED** [review]

**Review by Vovchyk — DISMISSED** [review]

**Pull request closed without merging**
