### PR TITLE
Create Web3MnrModule

### PR DESCRIPTION
**Pull request by M-Picco**
Move mnr methods from Web3RskImpl to a new Web3MnrModule interface implemented by Web3 trying to follow the same format as in the txpool module changes (PR #497).

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 161 issues
* ![BLOCKER][BLOCKER] 1 blocker
* ![CRITICAL][CRITICAL] 39 critical
* ![MAJOR][MAJOR] 44 major
* ![MINOR][MINOR] 61 minor
* ![INFO][INFO] 16 info

#### Top 10 issues

1. ![BLOCKER][BLOCKER] [Web3Impl.java#L486](https://github.com/rsksmart/rskj/blob/8bc488a1065f944dc3df0a8ff3f655423396001f/rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java#L486): "blockchain" is a method parameter, and should not be used for synchronization. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2445)
1. ![CRITICAL][CRITICAL] [Web3RskImpl.java#L102](https://github.com/rsksmart/rskj/blob/8bc488a1065f944dc3df0a8ff3f655423396001f/rskj-core/src/main/java/co/rsk/rpc/Web3RskImpl.java#L102): Change this "try" to a try-with-resources. (sonar.java.source not set. Assuming 7 or greater.) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2093)
1. ![CRITICAL][CRITICAL] [Web3.java#L31](https://github.com/rsksmart/rskj/blob/8bc488a1065f944dc3df0a8ff3f655423396001f/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L31): Make startingBlock a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L32](https://github.com/rsksmart/rskj/blob/8bc488a1065f944dc3df0a8ff3f655423396001f/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L32): Make currentBlock a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L33](https://github.com/rsksmart/rskj/blob/8bc488a1065f944dc3df0a8ff3f655423396001f/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L33): Make highestBlock a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L37](https://github.com/rsksmart/rskj/blob/8bc488a1065f944dc3df0a8ff3f655423396001f/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L37): Make from a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L38](https://github.com/rsksmart/rskj/blob/8bc488a1065f944dc3df0a8ff3f655423396001f/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L38): Make to a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L39](https://github.com/rsksmart/rskj/blob/8bc488a1065f944dc3df0a8ff3f655423396001f/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L39): Make gas a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L40](https://github.com/rsksmart/rskj/blob/8bc488a1065f944dc3df0a8ff3f655423396001f/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L40): Make gasPrice a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L41](https://github.com/rsksmart/rskj/blob/8bc488a1065f944dc3df0a8ff3f655423396001f/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L41): Make value a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by tinchou** [comment]
@aeidelman this blocker is legacy and hard to fix. I'll make it a major. The criticals about providing accessors are also legacy and could be ignored for now.

**Comment by rskops** [comment]
SonarQube analysis reported 161 issues
* ![BLOCKER][BLOCKER] 1 blocker
* ![CRITICAL][CRITICAL] 39 critical
* ![MAJOR][MAJOR] 44 major
* ![MINOR][MINOR] 62 minor
* ![INFO][INFO] 15 info

#### Top 10 issues

1. ![BLOCKER][BLOCKER] [Web3Impl.java#L486](https://github.com/rsksmart/rskj/blob/51eb16b3d8d50fc47994ef85066d652127687388/rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java#L486): "blockchain" is a method parameter, and should not be used for synchronization. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2445)
1. ![CRITICAL][CRITICAL] [Web3RskImpl.java#L102](https://github.com/rsksmart/rskj/blob/51eb16b3d8d50fc47994ef85066d652127687388/rskj-core/src/main/java/co/rsk/rpc/Web3RskImpl.java#L102): Change this "try" to a try-with-resources. (sonar.java.source not set. Assuming 7 or greater.) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2093)
1. ![CRITICAL][CRITICAL] [Web3.java#L31](https://github.com/rsksmart/rskj/blob/51eb16b3d8d50fc47994ef85066d652127687388/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L31): Make startingBlock a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L32](https://github.com/rsksmart/rskj/blob/51eb16b3d8d50fc47994ef85066d652127687388/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L32): Make currentBlock a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L33](https://github.com/rsksmart/rskj/blob/51eb16b3d8d50fc47994ef85066d652127687388/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L33): Make highestBlock a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L37](https://github.com/rsksmart/rskj/blob/51eb16b3d8d50fc47994ef85066d652127687388/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L37): Make from a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L38](https://github.com/rsksmart/rskj/blob/51eb16b3d8d50fc47994ef85066d652127687388/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L38): Make to a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L39](https://github.com/rsksmart/rskj/blob/51eb16b3d8d50fc47994ef85066d652127687388/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L39): Make gas a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L40](https://github.com/rsksmart/rskj/blob/51eb16b3d8d50fc47994ef85066d652127687388/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L40): Make gasPrice a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L41](https://github.com/rsksmart/rskj/blob/51eb16b3d8d50fc47994ef85066d652127687388/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L41): Make value a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 158 issues
* ![CRITICAL][CRITICAL] 39 critical
* ![MAJOR][MAJOR] 43 major
* ![MINOR][MINOR] 62 minor
* ![INFO][INFO] 14 info

#### Top 10 issues

1. ![CRITICAL][CRITICAL] [Web3RskImpl.java#L102](https://github.com/rsksmart/rskj/blob/f8faa5fc923513915a33f319270fa0917103e1e1/rskj-core/src/main/java/co/rsk/rpc/Web3RskImpl.java#L102): Change this "try" to a try-with-resources. (sonar.java.source not set. Assuming 7 or greater.) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2093)
1. ![CRITICAL][CRITICAL] [Web3.java#L31](https://github.com/rsksmart/rskj/blob/f8faa5fc923513915a33f319270fa0917103e1e1/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L31): Make startingBlock a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L32](https://github.com/rsksmart/rskj/blob/f8faa5fc923513915a33f319270fa0917103e1e1/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L32): Make currentBlock a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L33](https://github.com/rsksmart/rskj/blob/f8faa5fc923513915a33f319270fa0917103e1e1/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L33): Make highestBlock a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L37](https://github.com/rsksmart/rskj/blob/f8faa5fc923513915a33f319270fa0917103e1e1/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L37): Make from a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L38](https://github.com/rsksmart/rskj/blob/f8faa5fc923513915a33f319270fa0917103e1e1/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L38): Make to a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L39](https://github.com/rsksmart/rskj/blob/f8faa5fc923513915a33f319270fa0917103e1e1/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L39): Make gas a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L40](https://github.com/rsksmart/rskj/blob/f8faa5fc923513915a33f319270fa0917103e1e1/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L40): Make gasPrice a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L41](https://github.com/rsksmart/rskj/blob/f8faa5fc923513915a33f319270fa0917103e1e1/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L41): Make value a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L42](https://github.com/rsksmart/rskj/blob/f8faa5fc923513915a33f319270fa0917103e1e1/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L42): Make data a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 158 issues
* ![CRITICAL][CRITICAL] 39 critical
* ![MAJOR][MAJOR] 43 major
* ![MINOR][MINOR] 62 minor
* ![INFO][INFO] 14 info

#### Top 10 issues

1. ![CRITICAL][CRITICAL] [Web3RskImpl.java#L102](https://github.com/rsksmart/rskj/blob/9043a2731685927270c8e47e1af5ff384f46f816/rskj-core/src/main/java/co/rsk/rpc/Web3RskImpl.java#L102): Change this "try" to a try-with-resources. (sonar.java.source not set. Assuming 7 or greater.) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2093)
1. ![CRITICAL][CRITICAL] [Web3.java#L31](https://github.com/rsksmart/rskj/blob/9043a2731685927270c8e47e1af5ff384f46f816/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L31): Make startingBlock a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L32](https://github.com/rsksmart/rskj/blob/9043a2731685927270c8e47e1af5ff384f46f816/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L32): Make currentBlock a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L33](https://github.com/rsksmart/rskj/blob/9043a2731685927270c8e47e1af5ff384f46f816/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L33): Make highestBlock a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L37](https://github.com/rsksmart/rskj/blob/9043a2731685927270c8e47e1af5ff384f46f816/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L37): Make from a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L38](https://github.com/rsksmart/rskj/blob/9043a2731685927270c8e47e1af5ff384f46f816/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L38): Make to a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L39](https://github.com/rsksmart/rskj/blob/9043a2731685927270c8e47e1af5ff384f46f816/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L39): Make gas a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L40](https://github.com/rsksmart/rskj/blob/9043a2731685927270c8e47e1af5ff384f46f816/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L40): Make gasPrice a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L41](https://github.com/rsksmart/rskj/blob/9043a2731685927270c8e47e1af5ff384f46f816/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L41): Make value a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [Web3.java#L42](https://github.com/rsksmart/rskj/blob/9043a2731685927270c8e47e1af5ff384f46f816/rskj-core/src/main/java/org/ethereum/rpc/Web3.java#L42): Make data a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
