### PR TITLE
Heartbeat switch

### PR DESCRIPTION
**Pull request by martinmedina**
Heartbeat periodically checks if messages are received from peers in order to determine if their connection should be kept or dropped.

This new switch allows the former described functionality to be turned on or off using a configuration setting.

### CODE REVIEW

**Comment by martinmedina** [comment]
ci: hotfix-v2.0.1

**Comment by martinmedina** [comment]
pipeline: run

**Comment by martinmedina** [comment]
pipeline: run

**Comment by josedahlquist** [comment]
pipelin:run

**Comment by josedahlquist** [comment]
pipeline:run

**Pull request merged**
