### PR TITLE
Remove bridge method get state for debugging

### PR DESCRIPTION
**Pull request by ajlopezrsk**
Only to be applied after mainnet release.

Removes a method that has no use as a contract method.

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 70 issues
* ![MAJOR][MAJOR] 51 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 16 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [Bridge.java#L1](https://github.com/rsksmart/rskj/blob/1339e89437514353c9cf062a5e285bf5d18cd6f0/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L1): Class co.rsk.peg.Bridge defines static field "co.rsk.peg.Bridge.functionCostMap" which appears to allow memory bloat [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APMB_POSSIBLE_MEMORY_BLOAT)
1. ![MAJOR][MAJOR] [Bridge.java#L268](https://github.com/rsksmart/rskj/blob/1339e89437514353c9cf062a5e285bf5d18cd6f0/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L268): Either log or rethrow this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [Bridge.java#L297](https://github.com/rsksmart/rskj/blob/1339e89437514353c9cf062a5e285bf5d18cd6f0/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L297): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [Bridge.java#L308](https://github.com/rsksmart/rskj/blob/1339e89437514353c9cf062a5e285bf5d18cd6f0/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L308): Extract this nested try block into a separate method. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1141)
1. ![MAJOR][MAJOR] [Bridge.java#L313](https://github.com/rsksmart/rskj/blob/1339e89437514353c9cf062a5e285bf5d18cd6f0/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L313): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [Bridge.java#L330](https://github.com/rsksmart/rskj/blob/1339e89437514353c9cf062a5e285bf5d18cd6f0/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L330): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Bridge.java#L334](https://github.com/rsksmart/rskj/blob/1339e89437514353c9cf062a5e285bf5d18cd6f0/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L334): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Bridge.java#L343](https://github.com/rsksmart/rskj/blob/1339e89437514353c9cf062a5e285bf5d18cd6f0/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L343): Remove this unused method parameter "args". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [Bridge.java#L351](https://github.com/rsksmart/rskj/blob/1339e89437514353c9cf062a5e285bf5d18cd6f0/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L351): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Bridge.java#L374](https://github.com/rsksmart/rskj/blob/1339e89437514353c9cf062a5e285bf5d18cd6f0/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L374): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by donequis** [comment]
@aeidelman this changes consensus, are we ok with this?

**Comment by aeidelman** [comment]
@donequis @ajlopezrsk we need to program this as a hard fork

**Comment by aeidelman** [comment]
Duplicated with #475

**Pull request closed without merging**
