### PR TITLE
Affecting consensus by changing back federation migration age to its previous value

### PR DESCRIPTION
**Pull request by nathanieliov**
This change consists of changing method co.rsk.config.BridgeConstants#getFundsMigrationAgeSinceActivationEnd to return again the fundsMigrationAgeSinceActivationEnd(10585L) value when the RSKIP374 gets active.

### CODE REVIEW

**Comment by nathanieliov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Review by marcos-iov — APPROVED** [review]

**Pull request merged**
