### PR TITLE
Update signature

### PR DESCRIPTION
**Pull request by bcodesido**
Update Signature

## Description
Signature used for sign the `configure.sh` file was updated.

## Motivation and Context
The old signature expired and we created, uploaded and configure a new one.

### CODE REVIEW

**Comment by bcodesido** [comment]
`pipeline:run`

**Comment by bcodesido** [comment]
`pipeline:run`

**Comment by lucasvuotto** [comment]
pipeline: run

**Comment by lucasvuotto** [comment]
pipeline: run

**Review by aeidelman — APPROVED** [review]

**Pull request merged**
