### PR TITLE
Rebase federations new refactor integration

### PR DESCRIPTION
**Pull request by julia-zack**
*fed:rebase-federations-new-refactor-integration*

In order to move forward with the implementation of the segwit-compatible powpeg address, there are some improvements that need to be made in rskj projects regarding classes related to the Federation.
The current state of the design makes it hard to scale so implementing segwit can become a challenge both to developers and auditors.

**Changes made**
- Removal of all ErpFederation particular classes (LegacyErpFederation, P2shErpFederation).
- Creation of a _ErpRedeemScriptBuilder_ in charge of building the different erp redeem scripts, and injected in the ErpFederation constructor.
- Creation of a _formatVersion_ field in Federation's constructor to make format saving in the storage easier.
- Creation of a _FederationFactory_ in charge of building each one of the specific erp federations with each respective format.
- Creation of a _/federation_ package inside _/peg_ package to have all the federation-related classes there.
- Creation of a _FederationArgs_ field in order to reduce the amount of parameters we pass to the constructor.

### CODE REVIEW

**Comment by julia-zack** [comment]
pipeline:run

**Comment by julia-zack** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Review by marcos-iov — APPROVED** [review]

**Comment by josedahlquist** [comment]
may I suggest some squashing here? 110 commits 😅

**Comment by marcos-iov** [comment]
> may I suggest some squashing here? 110 commits 😅

Got it down to 35 :)

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Pull request merged**
