### PR TITLE
validating parent related timestamp

### PR DESCRIPTION
**Pull request by donequis**
this shuold solve issues #8 and #7

Missing tests

### CODE REVIEW

**Comment by donequis** [comment]
Rejects current testnet block at height 4709.

**Comment by aeidelman** [comment]
This is a hard fork. We can code it to be applied in a future block only for Testnet.

**Comment by rskops** [comment]
SonarQube analysis reported 17 issues
* ![BLOCKER][BLOCKER] 1 blocker
* ![MAJOR][MAJOR] 12 major
* ![INFO][INFO] 4 info

#### Top 10 issues

1. ![BLOCKER][BLOCKER] [MinerServerImpl.java#L514](https://github.com/rsksmart/rskj/blob/ee6ca5e92b90fed0b74b360fa63b673cb9a79390/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L514): Catch Exception instead of Throwable. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1181)
1. ![MAJOR][MAJOR] [MinerServerImpl.java#L151](https://github.com/rsksmart/rskj/blob/ee6ca5e92b90fed0b74b360fa63b673cb9a79390/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L151): Method co.rsk.mine.MinerServerImpl.submitBitcoinBlock(String, BtcBlock) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![MAJOR][MAJOR] [MinerServerImpl.java#L162](https://github.com/rsksmart/rskj/blob/ee6ca5e92b90fed0b74b360fa63b673cb9a79390/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L162): Method co.rsk.mine.MinerServerImpl.submitBitcoinBlock(String, BtcBlock) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![MAJOR][MAJOR] [MinerServerImpl.java#L176](https://github.com/rsksmart/rskj/blob/ee6ca5e92b90fed0b74b360fa63b673cb9a79390/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L176): Method co.rsk.mine.MinerServerImpl.submitBitcoinBlock(String, BtcBlock) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![MAJOR][MAJOR] [MinerServerImpl.java#L187](https://github.com/rsksmart/rskj/blob/ee6ca5e92b90fed0b74b360fa63b673cb9a79390/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L187): Method co.rsk.mine.MinerServerImpl.submitBitcoinBlock(String, BtcBlock) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![MAJOR][MAJOR] [MinerServerImpl.java#L190](https://github.com/rsksmart/rskj/blob/ee6ca5e92b90fed0b74b360fa63b673cb9a79390/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L190): Method co.rsk.mine.MinerServerImpl.submitBitcoinBlock(String, BtcBlock) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![MAJOR][MAJOR] [MinerServerImpl.java#L281](https://github.com/rsksmart/rskj/blob/ee6ca5e92b90fed0b74b360fa63b673cb9a79390/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L281): Boxing/unboxing to parse a primitive co.rsk.mine.MinerServerImpl.getWork() [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3ADM_BOXED_PRIMITIVE_FOR_PARSING)
1. ![MAJOR][MAJOR] [MinerServerImpl.java#L281](https://github.com/rsksmart/rskj/blob/ee6ca5e92b90fed0b74b360fa63b673cb9a79390/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L281): Method co.rsk.mine.MinerServerImpl.getWork() converts String to primitive using excessive boxing [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ANAB_NEEDLESS_BOXING_PARSE)
1. ![MAJOR][MAJOR] [MinerServerImpl.java#L301](https://github.com/rsksmart/rskj/blob/ee6ca5e92b90fed0b74b360fa63b673cb9a79390/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L301): Method co.rsk.mine.MinerServerImpl.updateGetWork(Block, boolean) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![MAJOR][MAJOR] [MinerServerImpl.java#L358](https://github.com/rsksmart/rskj/blob/ee6ca5e92b90fed0b74b360fa63b673cb9a79390/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L358): Method co.rsk.mine.MinerServerImpl.buildBlockToMine(Block, boolean) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by rskops** [comment]
SonarQube analysis reported 148 issues
* ![BLOCKER][BLOCKER] 2 blocker
* ![MAJOR][MAJOR] 91 major
* ![MINOR][MINOR] 15 minor
* ![INFO][INFO] 40 info

#### Top 10 issues

1. ![BLOCKER][BLOCKER] [MinerServerImpl.java#L514](https://github.com/rsksmart/rskj/blob/c300433814c49d00820567c8f130bd3e892fd19b/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L514): Catch Exception instead of Throwable. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1181)
1. ![BLOCKER][BLOCKER] [Federation.java#L116](https://github.com/rsksmart/rskj/blob/c300433814c49d00820567c8f130bd3e892fd19b/rskj-core/src/main/java/co/rsk/peg/Federation.java#L116): This class overrides "equals()" and should therefore also override "hashCode()". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1206)
1. ![MAJOR][MAJOR] [BridgeDevNetConstants.java#L36](https://github.com/rsksmart/rskj/blob/c300433814c49d00820567c8f130bd3e892fd19b/rskj-core/src/main/java/co/rsk/config/BridgeDevNetConstants.java#L36): Remove this unused "logger" private field. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1068)
1. ![MAJOR][MAJOR] [BridgeDevNetConstants.java#L52](https://github.com/rsksmart/rskj/blob/c300433814c49d00820567c8f130bd3e892fd19b/rskj-core/src/main/java/co/rsk/config/BridgeDevNetConstants.java#L52): This block of commented-out lines of code should be removed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [BridgeRegTestConstants.java#L38](https://github.com/rsksmart/rskj/blob/c300433814c49d00820567c8f130bd3e892fd19b/rskj-core/src/main/java/co/rsk/config/BridgeRegTestConstants.java#L38): Remove this unused "logger" private field. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1068)
1. ![MAJOR][MAJOR] [BridgeTestNetConstants.java#L35](https://github.com/rsksmart/rskj/blob/c300433814c49d00820567c8f130bd3e892fd19b/rskj-core/src/main/java/co/rsk/config/BridgeTestNetConstants.java#L35): Remove this unused "logger" private field. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1068)
1. ![MAJOR][MAJOR] [BridgeTestNetConstants.java#L71](https://github.com/rsksmart/rskj/blob/c300433814c49d00820567c8f130bd3e892fd19b/rskj-core/src/main/java/co/rsk/config/BridgeTestNetConstants.java#L71): This block of commented-out lines of code should be removed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [MinerServerImpl.java#L151](https://github.com/rsksmart/rskj/blob/c300433814c49d00820567c8f130bd3e892fd19b/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L151): Method co.rsk.mine.MinerServerImpl.submitBitcoinBlock(String, BtcBlock) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![MAJOR][MAJOR] [MinerServerImpl.java#L162](https://github.com/rsksmart/rskj/blob/c300433814c49d00820567c8f130bd3e892fd19b/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L162): Method co.rsk.mine.MinerServerImpl.submitBitcoinBlock(String, BtcBlock) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![MAJOR][MAJOR] [MinerServerImpl.java#L176](https://github.com/rsksmart/rskj/blob/c300433814c49d00820567c8f130bd3e892fd19b/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L176): Method co.rsk.mine.MinerServerImpl.submitBitcoinBlock(String, BtcBlock) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 149 issues
* ![BLOCKER][BLOCKER] 2 blocker
* ![MAJOR][MAJOR] 92 major
* ![MINOR][MINOR] 15 minor
* ![INFO][INFO] 40 info

#### Top 10 issues

1. ![BLOCKER][BLOCKER] [MinerServerImpl.java#L514](https://github.com/rsksmart/rskj/blob/c50f8b887ad62517336f7dcaebc89ea50ead26ef/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L514): Catch Exception instead of Throwable. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1181)
1. ![BLOCKER][BLOCKER] [Federation.java#L116](https://github.com/rsksmart/rskj/blob/c50f8b887ad62517336f7dcaebc89ea50ead26ef/rskj-core/src/main/java/co/rsk/peg/Federation.java#L116): This class overrides "equals()" and should therefore also override "hashCode()". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1206)
1. ![MAJOR][MAJOR] [BridgeDevNetConstants.java#L36](https://github.com/rsksmart/rskj/blob/c50f8b887ad62517336f7dcaebc89ea50ead26ef/rskj-core/src/main/java/co/rsk/config/BridgeDevNetConstants.java#L36): Remove this unused "logger" private field. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1068)
1. ![MAJOR][MAJOR] [BridgeDevNetConstants.java#L52](https://github.com/rsksmart/rskj/blob/c50f8b887ad62517336f7dcaebc89ea50ead26ef/rskj-core/src/main/java/co/rsk/config/BridgeDevNetConstants.java#L52): This block of commented-out lines of code should be removed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [BridgeRegTestConstants.java#L38](https://github.com/rsksmart/rskj/blob/c50f8b887ad62517336f7dcaebc89ea50ead26ef/rskj-core/src/main/java/co/rsk/config/BridgeRegTestConstants.java#L38): Remove this unused "logger" private field. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1068)
1. ![MAJOR][MAJOR] [BridgeTestNetConstants.java#L35](https://github.com/rsksmart/rskj/blob/c50f8b887ad62517336f7dcaebc89ea50ead26ef/rskj-core/src/main/java/co/rsk/config/BridgeTestNetConstants.java#L35): Remove this unused "logger" private field. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1068)
1. ![MAJOR][MAJOR] [BridgeTestNetConstants.java#L71](https://github.com/rsksmart/rskj/blob/c50f8b887ad62517336f7dcaebc89ea50ead26ef/rskj-core/src/main/java/co/rsk/config/BridgeTestNetConstants.java#L71): This block of commented-out lines of code should be removed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3ACommentedOutCodeLine)
1. ![MAJOR][MAJOR] [MinerServerImpl.java#L151](https://github.com/rsksmart/rskj/blob/c50f8b887ad62517336f7dcaebc89ea50ead26ef/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L151): Method co.rsk.mine.MinerServerImpl.submitBitcoinBlock(String, BtcBlock) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![MAJOR][MAJOR] [MinerServerImpl.java#L162](https://github.com/rsksmart/rskj/blob/c50f8b887ad62517336f7dcaebc89ea50ead26ef/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L162): Method co.rsk.mine.MinerServerImpl.submitBitcoinBlock(String, BtcBlock) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![MAJOR][MAJOR] [MinerServerImpl.java#L176](https://github.com/rsksmart/rskj/blob/c50f8b887ad62517336f7dcaebc89ea50ead26ef/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L176): Method co.rsk.mine.MinerServerImpl.submitBitcoinBlock(String, BtcBlock) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by aeidelman** [comment]
This has been fixed in another PR

**Pull request closed without merging**
