### PR TITLE
Extract Web3EthModule from Web3

### PR DESCRIPTION
**Pull request by tinchou**
This extracts `Web3EthModule` from the `Web3` interface, along the lines of `Web3TxPoolModule` in #471.

This is in preparation for `eth_call` with `pending` parameter.

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 249 issues
* ![BLOCKER][BLOCKER] 1 blocker
* ![MAJOR][MAJOR] 150 major
* ![MINOR][MINOR] 84 minor
* ![INFO][INFO] 14 info

#### Top 10 issues

1. ![BLOCKER][BLOCKER] [Web3Impl.java#L505](https://github.com/rsksmart/rskj/blob/1c75bc465fb5fb584433770d8ad25da774d5ad04/rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java#L505): "blockchain" is a method parameter, and should not be used for synchronization. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2445)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L54](https://github.com/rsksmart/rskj/blob/1c75bc465fb5fb584433770d8ad25da774d5ad04/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L54): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L74](https://github.com/rsksmart/rskj/blob/1c75bc465fb5fb584433770d8ad25da774d5ad04/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L74): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L76](https://github.com/rsksmart/rskj/blob/1c75bc465fb5fb584433770d8ad25da774d5ad04/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L76): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L78](https://github.com/rsksmart/rskj/blob/1c75bc465fb5fb584433770d8ad25da774d5ad04/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L78): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L80](https://github.com/rsksmart/rskj/blob/1c75bc465fb5fb584433770d8ad25da774d5ad04/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L80): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L82](https://github.com/rsksmart/rskj/blob/1c75bc465fb5fb584433770d8ad25da774d5ad04/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L82): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L84](https://github.com/rsksmart/rskj/blob/1c75bc465fb5fb584433770d8ad25da774d5ad04/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L84): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L86](https://github.com/rsksmart/rskj/blob/1c75bc465fb5fb584433770d8ad25da774d5ad04/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L86): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L88](https://github.com/rsksmart/rskj/blob/1c75bc465fb5fb584433770d8ad25da774d5ad04/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L88): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 249 issues
* ![BLOCKER][BLOCKER] 1 blocker
* ![MAJOR][MAJOR] 150 major
* ![MINOR][MINOR] 84 minor
* ![INFO][INFO] 14 info

#### Top 10 issues

1. ![BLOCKER][BLOCKER] [Web3Impl.java#L504](https://github.com/rsksmart/rskj/blob/2392ab320d10d4f42f2c048e9744ed20117e0c5c/rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java#L504): "blockchain" is a method parameter, and should not be used for synchronization. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2445)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L54](https://github.com/rsksmart/rskj/blob/2392ab320d10d4f42f2c048e9744ed20117e0c5c/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L54): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L74](https://github.com/rsksmart/rskj/blob/2392ab320d10d4f42f2c048e9744ed20117e0c5c/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L74): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L76](https://github.com/rsksmart/rskj/blob/2392ab320d10d4f42f2c048e9744ed20117e0c5c/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L76): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L78](https://github.com/rsksmart/rskj/blob/2392ab320d10d4f42f2c048e9744ed20117e0c5c/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L78): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L80](https://github.com/rsksmart/rskj/blob/2392ab320d10d4f42f2c048e9744ed20117e0c5c/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L80): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L82](https://github.com/rsksmart/rskj/blob/2392ab320d10d4f42f2c048e9744ed20117e0c5c/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L82): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L84](https://github.com/rsksmart/rskj/blob/2392ab320d10d4f42f2c048e9744ed20117e0c5c/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L84): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L86](https://github.com/rsksmart/rskj/blob/2392ab320d10d4f42f2c048e9744ed20117e0c5c/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L86): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L88](https://github.com/rsksmart/rskj/blob/2392ab320d10d4f42f2c048e9744ed20117e0c5c/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L88): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 249 issues
* ![BLOCKER][BLOCKER] 1 blocker
* ![MAJOR][MAJOR] 150 major
* ![MINOR][MINOR] 84 minor
* ![INFO][INFO] 14 info

#### Top 10 issues

1. ![BLOCKER][BLOCKER] [Web3Impl.java#L508](https://github.com/rsksmart/rskj/blob/1c9f54ebdcbf71b06ace8d91ce00b89dc0a28ef4/rskj-core/src/main/java/org/ethereum/rpc/Web3Impl.java#L508): "blockchain" is a method parameter, and should not be used for synchronization. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2445)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L54](https://github.com/rsksmart/rskj/blob/1c9f54ebdcbf71b06ace8d91ce00b89dc0a28ef4/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L54): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L74](https://github.com/rsksmart/rskj/blob/1c9f54ebdcbf71b06ace8d91ce00b89dc0a28ef4/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L74): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L76](https://github.com/rsksmart/rskj/blob/1c9f54ebdcbf71b06ace8d91ce00b89dc0a28ef4/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L76): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L78](https://github.com/rsksmart/rskj/blob/1c9f54ebdcbf71b06ace8d91ce00b89dc0a28ef4/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L78): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L80](https://github.com/rsksmart/rskj/blob/1c9f54ebdcbf71b06ace8d91ce00b89dc0a28ef4/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L80): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L82](https://github.com/rsksmart/rskj/blob/1c9f54ebdcbf71b06ace8d91ce00b89dc0a28ef4/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L82): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L84](https://github.com/rsksmart/rskj/blob/1c9f54ebdcbf71b06ace8d91ce00b89dc0a28ef4/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L84): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L86](https://github.com/rsksmart/rskj/blob/1c9f54ebdcbf71b06ace8d91ce00b89dc0a28ef4/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L86): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Web3EthModule.java#L88](https://github.com/rsksmart/rskj/blob/1c9f54ebdcbf71b06ace8d91ce00b89dc0a28ef4/rskj-core/src/main/java/co/rsk/rpc/Web3EthModule.java#L88): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by tinchou** [comment]
@lsebrie your review was automatically dismissed

**Pull request merged**
