### PR TITLE
Revert "Validating request content before processing the request itself"

### PR DESCRIPTION
**Pull request by Vovchyk**
Reverts rsksmart/rskj#1672

### CODE REVIEW

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Review by nagarev — APPROVED** [review]
LGTM

**Comment by nagarev** [comment]
pipeline:run

**Comment by nagarev** [comment]
pipeline:run

**Comment by nagarev** [comment]
pipeline:run

**Comment by lucasvuotto** [comment]
pipeline: run

**Comment by lucasvuotto** [comment]
pipeline: run

**Comment by lucasvuotto** [comment]
pipeline:run

**Pull request merged**
