### PR TITLE
Populate Constants through constructor

### PR DESCRIPTION
**Pull request by tinchou**
This simplifies reading, understanding and configuring per-network constants. This is also in preparation for PR #827.

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 12 issues
* ![MAJOR][MAJOR] 9 major
* ![MINOR][MINOR] 1 minor
* ![INFO][INFO] 2 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [Constants.java#L116](https://github.com/rsksmart/rskj/blob/d039410fa1b43b900563a8a6e9a8618b4d7a1aa5/rskj-core/src/main/java/org/ethereum/config/Constants.java#L116): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L120](https://github.com/rsksmart/rskj/blob/d039410fa1b43b900563a8a6e9a8618b4d7a1aa5/rskj-core/src/main/java/org/ethereum/config/Constants.java#L120): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L124](https://github.com/rsksmart/rskj/blob/d039410fa1b43b900563a8a6e9a8618b4d7a1aa5/rskj-core/src/main/java/org/ethereum/config/Constants.java#L124): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L128](https://github.com/rsksmart/rskj/blob/d039410fa1b43b900563a8a6e9a8618b4d7a1aa5/rskj-core/src/main/java/org/ethereum/config/Constants.java#L128): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L132](https://github.com/rsksmart/rskj/blob/d039410fa1b43b900563a8a6e9a8618b4d7a1aa5/rskj-core/src/main/java/org/ethereum/config/Constants.java#L132): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L136](https://github.com/rsksmart/rskj/blob/d039410fa1b43b900563a8a6e9a8618b4d7a1aa5/rskj-core/src/main/java/org/ethereum/config/Constants.java#L136): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L140](https://github.com/rsksmart/rskj/blob/d039410fa1b43b900563a8a6e9a8618b4d7a1aa5/rskj-core/src/main/java/org/ethereum/config/Constants.java#L140): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L160](https://github.com/rsksmart/rskj/blob/d039410fa1b43b900563a8a6e9a8618b4d7a1aa5/rskj-core/src/main/java/org/ethereum/config/Constants.java#L160): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L164](https://github.com/rsksmart/rskj/blob/d039410fa1b43b900563a8a6e9a8618b4d7a1aa5/rskj-core/src/main/java/org/ethereum/config/Constants.java#L164): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MINOR][MINOR] [Constants.java#L48](https://github.com/rsksmart/rskj/blob/d039410fa1b43b900563a8a6e9a8618b4d7a1aa5/rskj-core/src/main/java/org/ethereum/config/Constants.java#L48): Constructor has 8 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by tinchou** [comment]
@diega 

* extracted commit for `fallbackmain`
* removed the inheritance relation, now the different constants are factory methods (so `Constants` doesn't need to be abstract)
* I agree with the intention of the rename, but we're in the middle of merging big PRs and I would like to minimize the rebasing difficulties

**Comment by rskops** [comment]
SonarQube analysis reported 12 issues
* ![MAJOR][MAJOR] 9 major
* ![MINOR][MINOR] 1 minor
* ![INFO][INFO] 2 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [Constants.java#L121](https://github.com/rsksmart/rskj/blob/2bf3373f7e12b1d2308bce6cc51556392ff10057/rskj-core/src/main/java/org/ethereum/config/Constants.java#L121): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L125](https://github.com/rsksmart/rskj/blob/2bf3373f7e12b1d2308bce6cc51556392ff10057/rskj-core/src/main/java/org/ethereum/config/Constants.java#L125): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L129](https://github.com/rsksmart/rskj/blob/2bf3373f7e12b1d2308bce6cc51556392ff10057/rskj-core/src/main/java/org/ethereum/config/Constants.java#L129): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L133](https://github.com/rsksmart/rskj/blob/2bf3373f7e12b1d2308bce6cc51556392ff10057/rskj-core/src/main/java/org/ethereum/config/Constants.java#L133): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L137](https://github.com/rsksmart/rskj/blob/2bf3373f7e12b1d2308bce6cc51556392ff10057/rskj-core/src/main/java/org/ethereum/config/Constants.java#L137): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L141](https://github.com/rsksmart/rskj/blob/2bf3373f7e12b1d2308bce6cc51556392ff10057/rskj-core/src/main/java/org/ethereum/config/Constants.java#L141): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L145](https://github.com/rsksmart/rskj/blob/2bf3373f7e12b1d2308bce6cc51556392ff10057/rskj-core/src/main/java/org/ethereum/config/Constants.java#L145): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L165](https://github.com/rsksmart/rskj/blob/2bf3373f7e12b1d2308bce6cc51556392ff10057/rskj-core/src/main/java/org/ethereum/config/Constants.java#L165): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L169](https://github.com/rsksmart/rskj/blob/2bf3373f7e12b1d2308bce6cc51556392ff10057/rskj-core/src/main/java/org/ethereum/config/Constants.java#L169): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MINOR][MINOR] [Constants.java#L53](https://github.com/rsksmart/rskj/blob/2bf3373f7e12b1d2308bce6cc51556392ff10057/rskj-core/src/main/java/org/ethereum/config/Constants.java#L53): Constructor has 8 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 12 issues
* ![MAJOR][MAJOR] 9 major
* ![MINOR][MINOR] 1 minor
* ![INFO][INFO] 2 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [Constants.java#L121](https://github.com/rsksmart/rskj/blob/97ae95294eb50b95149f9aee83bff76cd5335347/rskj-core/src/main/java/org/ethereum/config/Constants.java#L121): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L125](https://github.com/rsksmart/rskj/blob/97ae95294eb50b95149f9aee83bff76cd5335347/rskj-core/src/main/java/org/ethereum/config/Constants.java#L125): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L129](https://github.com/rsksmart/rskj/blob/97ae95294eb50b95149f9aee83bff76cd5335347/rskj-core/src/main/java/org/ethereum/config/Constants.java#L129): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L133](https://github.com/rsksmart/rskj/blob/97ae95294eb50b95149f9aee83bff76cd5335347/rskj-core/src/main/java/org/ethereum/config/Constants.java#L133): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L137](https://github.com/rsksmart/rskj/blob/97ae95294eb50b95149f9aee83bff76cd5335347/rskj-core/src/main/java/org/ethereum/config/Constants.java#L137): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L141](https://github.com/rsksmart/rskj/blob/97ae95294eb50b95149f9aee83bff76cd5335347/rskj-core/src/main/java/org/ethereum/config/Constants.java#L141): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L145](https://github.com/rsksmart/rskj/blob/97ae95294eb50b95149f9aee83bff76cd5335347/rskj-core/src/main/java/org/ethereum/config/Constants.java#L145): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L165](https://github.com/rsksmart/rskj/blob/97ae95294eb50b95149f9aee83bff76cd5335347/rskj-core/src/main/java/org/ethereum/config/Constants.java#L165): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [Constants.java#L169](https://github.com/rsksmart/rskj/blob/97ae95294eb50b95149f9aee83bff76cd5335347/rskj-core/src/main/java/org/ethereum/config/Constants.java#L169): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MINOR][MINOR] [Constants.java#L53](https://github.com/rsksmart/rskj/blob/97ae95294eb50b95149f9aee83bff76cd5335347/rskj-core/src/main/java/org/ethereum/config/Constants.java#L53): Constructor has 8 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
