### PR TITLE
Implementation of RSKIP379

### PR DESCRIPTION
**Pull request by marcos-iov**
Create an index in the Bridge to store the sighash of transactions created by the Bridge. This index can then be used to simplify the detection of peg-in/peg-out/migration transactions.

*fed:bridge-btc-tx-index-integration*
*rit:adds-tbd600-fork*

### CODE REVIEW

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by nathanieliov** [comment]
pipeline:run

**Comment by nathanieliov** [comment]
pipeline:run

**Comment by nathanieliov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Review by nathanieliov — APPROVED** [review]
LGTM

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Pull request merged**
