### PR TITLE
Subroutines removal

### PR DESCRIPTION
**Pull request by fedejinich**
# EVM Subroutines Removal

## Description

This PR removes three opcodes:
- BEGINSUB
- RETURNSUB
- JUMPSUB

NOTE: I've created a [backup branch](https://github.com/rsksmart/rskj/tree/subroutines-backup), so if we want to addd them we can just rebase the branch.

## Motivation and Context

Previously, we [added](https://github.com/rsksmart/rskj/pull/1302/files) three opcodes in order to maintain EVM compatibility. Since they are not included anymore in Berlin hardfork, we've decided to remove them.

## How Has This Been Tested?

Run the entire test-suite

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

### CODE REVIEW

**Comment by fedejinich** [comment]
pipeline:run

**Comment by fedejinich** [comment]
pipeline:run

**Review by ajlopezrsk — APPROVED** [review]

**Review by donequis — DISMISSED** [review]
This is a revert of https://github.com/rsksmart/rskj/pull/1302/files and can be easily compared

The only small difference is in the playWithActivations functions in tests which are used for `dupn` and `swapn`

**Review by Vovchyk — APPROVED** [review]
lgtm

**Comment by fedejinich** [comment]
rebasing it

**Review by ajlopezrsk — APPROVED** [review]

**Pull request merged**
