### PR TITLE
Set peg-out tx index bridge constants

### PR DESCRIPTION
**Pull request by nathanieliov**
- Set estimatedPegoutTxIndexBtcActivationHeight final value.
- Set pegoutTxIndexGracePeriodInBtcBlocks final value.

*ci:rc600-modifier*
*fed:ARROWHEAD-6.0.0-rc*
*rit:ARROWHEAD-6.0.0-rc*

### CODE REVIEW

**Comment by nathanieliov** [comment]
pipeline:run

**Comment by nathanieliov** [comment]
pipeline:rub

**Comment by nathanieliov** [comment]
pipeline:run

**Comment by nathanieliov** [comment]
pipeline:run

**Comment by nathanieliov** [comment]
pipeline:run

**Comment by nathanieliov** [comment]
pipeline:run

**Comment by nathanieliov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
Moved to https://github.com/rsksmart/rskj/pull/2263

**Pull request closed without merging**
