### PR TITLE
Fix bug where a contract would inherit msg.value

### PR DESCRIPTION
**Pull request by tinchou**

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 63 issues
* ![MAJOR][MAJOR] 43 major
* ![MINOR][MINOR] 6 minor
* ![INFO][INFO] 14 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [Transaction.java#L130](https://github.com/rsksmart/rskj/blob/79b25c09ab5321e6da09d50d043138ec6a28bbf1/rskj-core/src/main/java/org/ethereum/core/Transaction.java#L130): Constructor has 9 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)
1. ![MAJOR][MAJOR] [Transaction.java#L196](https://github.com/rsksmart/rskj/blob/79b25c09ab5321e6da09d50d043138ec6a28bbf1/rskj-core/src/main/java/org/ethereum/core/Transaction.java#L196): Method org.ethereum.core.Transaction.rlpParse() manually casts the right hand side of an assignment more specifically than needed [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3AOC_OVERZEALOUS_CASTING)
1. ![MAJOR][MAJOR] [Transaction.java#L334](https://github.com/rsksmart/rskj/blob/79b25c09ab5321e6da09d50d043138ec6a28bbf1/rskj-core/src/main/java/org/ethereum/core/Transaction.java#L334): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [Transaction.java#L374](https://github.com/rsksmart/rskj/blob/79b25c09ab5321e6da09d50d043138ec6a28bbf1/rskj-core/src/main/java/org/ethereum/core/Transaction.java#L374): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [Program.java](https://github.com/rsksmart/rskj/blob/79b25c09ab5321e6da09d50d043138ec6a28bbf1/rskj-core/src/main/java/org/ethereum/vm/program/Program.java): This file has 1,121 lines, which is greater than 1,000 authorized. Split it into smaller files. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Program.java#L173](https://github.com/rsksmart/rskj/blob/79b25c09ab5321e6da09d50d043138ec6a28bbf1/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L173): Method org.ethereum.vm.program.Program.<static initializer for Program>() needlessly boxes a boolean constant [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ANAB_NEEDLESS_BOOLEAN_CONSTANT_CONVERSION)
1. ![MAJOR][MAJOR] [Program.java#L193](https://github.com/rsksmart/rskj/blob/79b25c09ab5321e6da09d50d043138ec6a28bbf1/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L193): Replace the type specification in this constructor call with the diamond operator ("<>"). (sonar.java.source not set. Assuming 7 or greater.) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2293)
1. ![MAJOR][MAJOR] [Program.java#L201](https://github.com/rsksmart/rskj/blob/79b25c09ab5321e6da09d50d043138ec6a28bbf1/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L201): Constructor new org.ethereum.vm.program.Program(byte[], ProgramInvoke) makes call to non-final method [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APCOA_PARTIALLY_CONSTRUCTED_OBJECT_ACCESS)
1. ![MAJOR][MAJOR] [Program.java#L226](https://github.com/rsksmart/rskj/blob/79b25c09ab5321e6da09d50d043138ec6a28bbf1/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L226): Rename "result" which hides the field declared at line 96. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. ![MAJOR][MAJOR] [Program.java#L310](https://github.com/rsksmart/rskj/blob/79b25c09ab5321e6da09d50d043138ec6a28bbf1/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L310): Use isEmpty() to check whether the collection is empty or not. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1155)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by donequis** [comment]
Could you please describe the bug and fix?

**Comment by tinchou** [comment]
You can easily see the bug if you check the parent and child contracts that
were used for testing.

If you create a contract like "new Child()", the child contract shouldn't
inherit the parent msg.value.

The parent test contract passes its own value to the child contract and the
child asserts that it should be different to its own (I pass a value of 10
to the parent, and the child should have a value of 0, which is different).

The fix is what you see in the Program.java different. We basically picked
the wrong variable.

**Comment by donequis** [comment]
Thanks. I'll check it tomorrow

**Comment by rskops** [comment]
SonarQube analysis reported 63 issues
* ![MAJOR][MAJOR] 43 major
* ![MINOR][MINOR] 6 minor
* ![INFO][INFO] 14 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [Transaction.java#L130](https://github.com/rsksmart/rskj/blob/1f34187baf327e01965987047b3c1076c57bd857/rskj-core/src/main/java/org/ethereum/core/Transaction.java#L130): Constructor has 9 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)
1. ![MAJOR][MAJOR] [Transaction.java#L196](https://github.com/rsksmart/rskj/blob/1f34187baf327e01965987047b3c1076c57bd857/rskj-core/src/main/java/org/ethereum/core/Transaction.java#L196): Method org.ethereum.core.Transaction.rlpParse() manually casts the right hand side of an assignment more specifically than needed [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3AOC_OVERZEALOUS_CASTING)
1. ![MAJOR][MAJOR] [Transaction.java#L334](https://github.com/rsksmart/rskj/blob/1f34187baf327e01965987047b3c1076c57bd857/rskj-core/src/main/java/org/ethereum/core/Transaction.java#L334): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [Transaction.java#L374](https://github.com/rsksmart/rskj/blob/1f34187baf327e01965987047b3c1076c57bd857/rskj-core/src/main/java/org/ethereum/core/Transaction.java#L374): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [Program.java](https://github.com/rsksmart/rskj/blob/1f34187baf327e01965987047b3c1076c57bd857/rskj-core/src/main/java/org/ethereum/vm/program/Program.java): This file has 1,121 lines, which is greater than 1,000 authorized. Split it into smaller files. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Program.java#L173](https://github.com/rsksmart/rskj/blob/1f34187baf327e01965987047b3c1076c57bd857/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L173): Method org.ethereum.vm.program.Program.<static initializer for Program>() needlessly boxes a boolean constant [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ANAB_NEEDLESS_BOOLEAN_CONSTANT_CONVERSION)
1. ![MAJOR][MAJOR] [Program.java#L193](https://github.com/rsksmart/rskj/blob/1f34187baf327e01965987047b3c1076c57bd857/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L193): Replace the type specification in this constructor call with the diamond operator ("<>"). (sonar.java.source not set. Assuming 7 or greater.) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2293)
1. ![MAJOR][MAJOR] [Program.java#L201](https://github.com/rsksmart/rskj/blob/1f34187baf327e01965987047b3c1076c57bd857/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L201): Constructor new org.ethereum.vm.program.Program(byte[], ProgramInvoke) makes call to non-final method [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APCOA_PARTIALLY_CONSTRUCTED_OBJECT_ACCESS)
1. ![MAJOR][MAJOR] [Program.java#L226](https://github.com/rsksmart/rskj/blob/1f34187baf327e01965987047b3c1076c57bd857/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L226): Rename "result" which hides the field declared at line 96. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. ![MAJOR][MAJOR] [Program.java#L310](https://github.com/rsksmart/rskj/blob/1f34187baf327e01965987047b3c1076c57bd857/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L310): Use isEmpty() to check whether the collection is empty or not. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1155)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
