### PR TITLE
Profiler tool interfaces and Dummy profiler implementation added

### PR DESCRIPTION
**Pull request by raullaprida**
new package co.rsk.metrics.profilers
2 Interfaces: Metric, Profiler
1 Instance retriever :  ProfilerFactory
1 Initial/Default/Dummy profiler implementation: DummyProfiler

These 4 files are the minimum required information core needs to know. Information that allows classes to generate hooks to take measurements using Profiler implementations (deployed in external solutions that use the profiling tool)

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 2 issues

1. ![MAJOR][MAJOR] [DummyProfiler.java#L19](https://github.com/rsksmart/rskj/blob/7252cbe4667a48730e75c767ef58ceb3f9306860/rskj-core/src/main/java/co/rsk/metrics/profilers/impl/DummyProfiler.java#L19): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1186)
1. ![MAJOR][MAJOR] [DummyProfiler.java#L24](https://github.com/rsksmart/rskj/blob/7252cbe4667a48730e75c767ef58ceb3f9306860/rskj-core/src/main/java/co/rsk/metrics/profilers/impl/DummyProfiler.java#L24): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1186)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by rskops** [comment]
SonarQube analysis reported 2 issues

1. ![MAJOR][MAJOR] [DummyProfiler.java#L19](https://github.com/rsksmart/rskj/blob/22d24035282f399411885571544e8fba07ea2cd4/rskj-core/src/main/java/co/rsk/metrics/profilers/impl/DummyProfiler.java#L19): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1186)
1. ![MAJOR][MAJOR] [DummyProfiler.java#L24](https://github.com/rsksmart/rskj/blob/22d24035282f399411885571544e8fba07ea2cd4/rskj-core/src/main/java/co/rsk/metrics/profilers/impl/DummyProfiler.java#L24): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1186)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by rskops** [comment]
SonarQube analysis reported 2 issues

1. ![MAJOR][MAJOR] [DummyProfiler.java#L19](https://github.com/rsksmart/rskj/blob/87f90545579d258c7338b6e93b7cd879711a6081/rskj-core/src/main/java/co/rsk/metrics/profilers/impl/DummyProfiler.java#L19): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1186)
1. ![MAJOR][MAJOR] [DummyProfiler.java#L24](https://github.com/rsksmart/rskj/blob/87f90545579d258c7338b6e93b7cd879711a6081/rskj-core/src/main/java/co/rsk/metrics/profilers/impl/DummyProfiler.java#L24): Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1186)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by raullaprida** [comment]
This PR was superseded by PR  #791

**Pull request closed without merging**
