### PR TITLE
Fixing parameters on log messages

### PR DESCRIPTION
**Pull request by nagarev**
## Description

Updating log messages to use parameters as expected.

## Motivation and Context

As described in LGTM [documentation](https://lgtm.com/rules/1930000368/): "When formatting strings using printf-style format strings, one must ensure that the number of supplied arguments matches the number of arguments referenced by the format string. Additional arguments will be thrown away silently, which may not be the intended behavior, and too few arguments will cause an IllegalFormatException."

## How Has This Been Tested?

Using Unit Tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

* **Other information**:

### CODE REVIEW

**Review by patogallaiovlabs — APPROVED** [review]
LGTM

**Comment by patogallaiovlabs** [comment]
The failing tests are epics 🤣

**Comment by nagarev** [comment]
pipeline:run

**Review by Vovchyk — DISMISSED** [review]

**Review by fedejinich — DISMISSED** [review]
lgtm

**Comment by nagarev** [comment]
pipeline:run

**Comment by nagarev** [comment]
pipeline:run

**Comment by nagarev** [comment]
pipeline:run

**Review by Vovchyk — APPROVED** [review]

**Review by marcciosilva — APPROVED** [review]

**Pull request merged**
