### PR TITLE
Cloudflare bn128

### PR DESCRIPTION
**Pull request by bakaoh**
Fix: #1037
Native Alt_bn128 ECC Precompiles Using Cloudflare library

```
Benchmark                     Mode  Cnt      Score      Error  Units
BenchMark.cloudflareAdd      thrpt    5  36373.381 ± 2679.576  ops/s
BenchMark.cloudflareMul      thrpt    5   5108.305 ± 1003.203  ops/s
BenchMark.cloudflarePairing  thrpt    5     52.088 ±    5.630  ops/s
BenchMark.currentAdd         thrpt    5  27681.939 ± 3150.748  ops/s
BenchMark.currentMul         thrpt    5    925.592 ±  173.279  ops/s
BenchMark.currentPairing     thrpt    5      2.895 ±    0.975  ops/s
```

The jni and benchmark are packaged in this library https://github.com/bakaoh/cloudflare-altbn128-jni to simplify the build process. Published to jcenter `com.bakaoh:altbn128:1.0`

### CODE REVIEW

**Comment by smcsicardi** [comment]
Hi! Could you please upload the libraries for the other OSes? We need mainly the osx one.

Or in other case please provide instructions to generate them

**Comment by bakaoh** [comment]
@smcsicardi --- i updated the README here https://github.com/bakaoh/cloudflare-altbn128-jni#build

**Comment by nacho692** [comment]
@bakaoh could you rebase to master to allow the merge? In the case there are to many issues just solve the conflicts.

**Comment by bakaoh** [comment]
@nacho692 --- i rebased to master

**Pull request merged**
