### PR TITLE
Consider case when hash has a leading 0 when deserializing

### PR DESCRIPTION
**Pull request by marcos-iov**
*fit:troubleshooting*

### CODE REVIEW

**Comment by marcos-iov** [comment]
pipeline:run

**Review by josedahlquist — APPROVED** [review]

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Review by pamgonzalez — APPROVED** [review]

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Review by guidohernan93 — APPROVED** [review]

**Pull request merged**
