### PR TITLE
Code formatting

### PR DESCRIPTION
**Pull request by illuque-iov**
Just some code formatting before opening the actual PR to ease review

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

* **Other information**:

### CODE REVIEW

**Comment by illuque-iov** [comment]
pipeline:run

**Comment by illuque-iov** [comment]
pipeline:run

**Comment by illuque-iov** [comment]
pipeline:run

**Review by Vovchyk — APPROVED** [review]

**Comment by illuque-iov** [comment]
pipeline:run

**Pull request merged**
