### PR TITLE
Fix #806

### LINKED ISSUE #806: Remove Apache Commons Lang dependency
Following with our effort to reduce dependencies, the Apache Commons Lang doesn't add much value and thus must be removed

To remove from `build.gradle`: `org.apache.commons:commons-lang3:3.5`

### PR DESCRIPTION
**Pull request by alexjavabraz**
- removed dependency commons.ListUtil methods
- new methods with similar 'commons lib' behavior
- created some tests

Pending

- StringUtils methods
- Pair

### CODE REVIEW

**Comment by collheesi** [comment]
Would it be OK for you to add me as a contributor in your fork so I can commit there? A few suggestions are easier seen as code than as comments.

**Comment by alexjavabraz** [comment]
> Would it be OK for you to add me as a contributor in your fork so I can commit there? A few suggestions are easier seen as code than as comments.

added.

**Comment by collheesi** [comment]
I pushed branch [`pr869`](https://github.com/alexjavabraz/rskj/tree/pr869) where I:

* rebased on top of `master` to follow our git etiquette (see [ `CONTRIBUTING.md`](https://github.com/rsksmart/rskj/blob/master/CONTRIBUTING.md))
* tidied up your first commit
* added a second commit for the `IpUtils` changes. the first suggestion was actually breaking unit tests, so I enhanced the `IPV4` regex

Feel free to review these changes and reset/push the branch you used for this PR so we can merge it :)

**Comment by alexjavabraz** [comment]
can i close that pr and open new one using the pr869 branch ?

**Comment by collheesi** [comment]
To update this PR:

`git fetch`
`git reset --hard origin/pr869`
`git push --force`

**Comment by alexjavabraz** [comment]
done

**Pull request merged**
