### PR TITLE
Emit new event when batching pegouts

### PR DESCRIPTION
**Pull request by kelvinator07**

### CODE REVIEW

**Comment by josedahlquist** [comment]
I think this one needs rebase @kelvinator07

**Review by josedahlquist — APPROVED** [review]

**Comment by josedahlquist** [comment]
@kelvinator07 please rebase again ❤️

**Comment by kelvinator07** [comment]
> @kelvinator07 please rebase again ❤️

Done

**Review by josedahlquist — APPROVED** [review]

**Comment by marcos-iov** [comment]
In `BridgeSupportReleaseBtcTest` we should be checking that the event was emmited when a batched  pegout is performed

**Comment by kelvinator07** [comment]
> we should be checking that the event was emmited when a batched pegout is performed

Done

**Review by marcos-iov — APPROVED** [review]

**Pull request merged**
