### PR TITLE
Use TxSender instead of byte[] for Transaction.getSender()

### PR DESCRIPTION
**Pull request by tinchou**
As part of the effort to strongly-type our codebase and stop relying on basic types like `byte[]`, let's return `TxSender` from `Transaction.getSender()`.

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 216 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 129 major
* ![MINOR][MINOR] 18 minor
* ![INFO][INFO] 68 info

#### Top 10 issues

1. ![CRITICAL][CRITICAL] [BridgeSerializationUtils.java#L23](https://github.com/rsksmart/rskj/blob/3f83e97c4a660beb820f0f4d916733e6d096429a/rskj-core/src/main/java/co/rsk/peg/BridgeSerializationUtils.java#L23): Unused import - com.google.common.primitives.UnsignedBytes. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck)
1. ![MAJOR][MAJOR] [ReversibleTransactionExecutor.java#L40](https://github.com/rsksmart/rskj/blob/3f83e97c4a660beb820f0f4d916733e6d096429a/rskj-core/src/main/java/co/rsk/core/ReversibleTransactionExecutor.java#L40): Method has 12 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)
1. ![MAJOR][MAJOR] [MinerServerImpl.java#L116](https://github.com/rsksmart/rskj/blob/3f83e97c4a660beb820f0f4d916733e6d096429a/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L116): Constructor has 11 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)
1. ![MAJOR][MAJOR] [MinerUtils.java#L72](https://github.com/rsksmart/rskj/blob/3f83e97c4a660beb820f0f4d916733e6d096429a/rskj-core/src/main/java/co/rsk/mine/MinerUtils.java#L72): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [MinerUtils.java#L111](https://github.com/rsksmart/rskj/blob/3f83e97c4a660beb820f0f4d916733e6d096429a/rskj-core/src/main/java/co/rsk/mine/MinerUtils.java#L111): Method co.rsk.mine.MinerUtils.filterTransactions(List, List, Map, Repository, BigInteger) appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [MinerUtils.java#L148](https://github.com/rsksmart/rskj/blob/3f83e97c4a660beb820f0f4d916733e6d096429a/rskj-core/src/main/java/co/rsk/mine/MinerUtils.java#L148): Method co.rsk.mine.MinerUtils.filterTransactions(List, List, Map, Repository, BigInteger) does not presize the allocation of a collection [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APSC_PRESIZE_COLLECTIONS)
1. ![MAJOR][MAJOR] [TxHandlerImpl.java#L61](https://github.com/rsksmart/rskj/blob/3f83e97c4a660beb820f0f4d916733e6d096429a/rskj-core/src/main/java/co/rsk/net/handler/TxHandlerImpl.java#L61): Method new co.rsk.net.handler.TxHandlerImpl(WorldManager, Repository, Blockchain) defines parameters more abstractly than needed to function properly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APDP_POORLY_DEFINED_PARAMETER)
1. ![MAJOR][MAJOR] [TxHandlerImpl.java#L108](https://github.com/rsksmart/rskj/blob/3f83e97c4a660beb820f0f4d916733e6d096429a/rskj-core/src/main/java/co/rsk/net/handler/TxHandlerImpl.java#L108): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS134)
1. ![MAJOR][MAJOR] [TxHandlerImpl.java#L116](https://github.com/rsksmart/rskj/blob/3f83e97c4a660beb820f0f4d916733e6d096429a/rskj-core/src/main/java/co/rsk/net/handler/TxHandlerImpl.java#L116): Method co.rsk.net.handler.TxHandlerImpl.cleanTxs() does not presize the allocation of a collection [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APSC_PRESIZE_COLLECTIONS)
1. ![MAJOR][MAJOR] [TxValidator.java#L64](https://github.com/rsksmart/rskj/blob/3f83e97c4a660beb820f0f4d916733e6d096429a/rskj-core/src/main/java/co/rsk/net/handler/TxValidator.java#L64): Take the required action to fix the issue indicated by this comment. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1134)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 214 issues
* ![MAJOR][MAJOR] 129 major
* ![MINOR][MINOR] 17 minor
* ![INFO][INFO] 68 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [ReversibleTransactionExecutor.java#L40](https://github.com/rsksmart/rskj/blob/c009b03b65727552e8dcdca530ca529c5f969d55/rskj-core/src/main/java/co/rsk/core/ReversibleTransactionExecutor.java#L40): Method has 12 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)
1. ![MAJOR][MAJOR] [MinerServerImpl.java#L116](https://github.com/rsksmart/rskj/blob/c009b03b65727552e8dcdca530ca529c5f969d55/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L116): Constructor has 11 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)
1. ![MAJOR][MAJOR] [MinerUtils.java#L72](https://github.com/rsksmart/rskj/blob/c009b03b65727552e8dcdca530ca529c5f969d55/rskj-core/src/main/java/co/rsk/mine/MinerUtils.java#L72): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [MinerUtils.java#L111](https://github.com/rsksmart/rskj/blob/c009b03b65727552e8dcdca530ca529c5f969d55/rskj-core/src/main/java/co/rsk/mine/MinerUtils.java#L111): Method co.rsk.mine.MinerUtils.filterTransactions(List, List, Map, Repository, BigInteger) appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [MinerUtils.java#L148](https://github.com/rsksmart/rskj/blob/c009b03b65727552e8dcdca530ca529c5f969d55/rskj-core/src/main/java/co/rsk/mine/MinerUtils.java#L148): Method co.rsk.mine.MinerUtils.filterTransactions(List, List, Map, Repository, BigInteger) does not presize the allocation of a collection [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APSC_PRESIZE_COLLECTIONS)
1. ![MAJOR][MAJOR] [TxHandlerImpl.java#L61](https://github.com/rsksmart/rskj/blob/c009b03b65727552e8dcdca530ca529c5f969d55/rskj-core/src/main/java/co/rsk/net/handler/TxHandlerImpl.java#L61): Method new co.rsk.net.handler.TxHandlerImpl(WorldManager, Repository, Blockchain) defines parameters more abstractly than needed to function properly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APDP_POORLY_DEFINED_PARAMETER)
1. ![MAJOR][MAJOR] [TxHandlerImpl.java#L108](https://github.com/rsksmart/rskj/blob/c009b03b65727552e8dcdca530ca529c5f969d55/rskj-core/src/main/java/co/rsk/net/handler/TxHandlerImpl.java#L108): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS134)
1. ![MAJOR][MAJOR] [TxHandlerImpl.java#L116](https://github.com/rsksmart/rskj/blob/c009b03b65727552e8dcdca530ca529c5f969d55/rskj-core/src/main/java/co/rsk/net/handler/TxHandlerImpl.java#L116): Method co.rsk.net.handler.TxHandlerImpl.cleanTxs() does not presize the allocation of a collection [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APSC_PRESIZE_COLLECTIONS)
1. ![MAJOR][MAJOR] [TxValidator.java#L64](https://github.com/rsksmart/rskj/blob/c009b03b65727552e8dcdca530ca529c5f969d55/rskj-core/src/main/java/co/rsk/net/handler/TxValidator.java#L64): Take the required action to fix the issue indicated by this comment. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1134)
1. ![MAJOR][MAJOR] [BridgeSerializationUtils.java#L121](https://github.com/rsksmart/rskj/blob/c009b03b65727552e8dcdca530ca529c5f969d55/rskj-core/src/main/java/co/rsk/peg/BridgeSerializationUtils.java#L121): Method co.rsk.peg.BridgeSerializationUtils.deserializeUTXOList(byte[]) does not presize the allocation of a collection [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APSC_PRESIZE_COLLECTIONS)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 211 issues
* ![MAJOR][MAJOR] 126 major
* ![MINOR][MINOR] 17 minor
* ![INFO][INFO] 68 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [ReversibleTransactionExecutor.java#L40](https://github.com/rsksmart/rskj/blob/40c678e7264d8adbfa6e318767b15deb0926a0a5/rskj-core/src/main/java/co/rsk/core/ReversibleTransactionExecutor.java#L40): Method has 12 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)
1. ![MAJOR][MAJOR] [MinerServerImpl.java#L116](https://github.com/rsksmart/rskj/blob/40c678e7264d8adbfa6e318767b15deb0926a0a5/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L116): Constructor has 11 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)
1. ![MAJOR][MAJOR] [MinerUtils.java#L72](https://github.com/rsksmart/rskj/blob/40c678e7264d8adbfa6e318767b15deb0926a0a5/rskj-core/src/main/java/co/rsk/mine/MinerUtils.java#L72): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [MinerUtils.java#L111](https://github.com/rsksmart/rskj/blob/40c678e7264d8adbfa6e318767b15deb0926a0a5/rskj-core/src/main/java/co/rsk/mine/MinerUtils.java#L111): Method co.rsk.mine.MinerUtils.filterTransactions(List, List, Map, Repository, BigInteger) appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [MinerUtils.java#L148](https://github.com/rsksmart/rskj/blob/40c678e7264d8adbfa6e318767b15deb0926a0a5/rskj-core/src/main/java/co/rsk/mine/MinerUtils.java#L148): Method co.rsk.mine.MinerUtils.filterTransactions(List, List, Map, Repository, BigInteger) does not presize the allocation of a collection [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APSC_PRESIZE_COLLECTIONS)
1. ![MAJOR][MAJOR] [TxHandlerImpl.java#L61](https://github.com/rsksmart/rskj/blob/40c678e7264d8adbfa6e318767b15deb0926a0a5/rskj-core/src/main/java/co/rsk/net/handler/TxHandlerImpl.java#L61): Method new co.rsk.net.handler.TxHandlerImpl(WorldManager, Repository, Blockchain) defines parameters more abstractly than needed to function properly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APDP_POORLY_DEFINED_PARAMETER)
1. ![MAJOR][MAJOR] [TxHandlerImpl.java#L108](https://github.com/rsksmart/rskj/blob/40c678e7264d8adbfa6e318767b15deb0926a0a5/rskj-core/src/main/java/co/rsk/net/handler/TxHandlerImpl.java#L108): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS134)
1. ![MAJOR][MAJOR] [TxHandlerImpl.java#L116](https://github.com/rsksmart/rskj/blob/40c678e7264d8adbfa6e318767b15deb0926a0a5/rskj-core/src/main/java/co/rsk/net/handler/TxHandlerImpl.java#L116): Method co.rsk.net.handler.TxHandlerImpl.cleanTxs() does not presize the allocation of a collection [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APSC_PRESIZE_COLLECTIONS)
1. ![MAJOR][MAJOR] [TxValidator.java#L64](https://github.com/rsksmart/rskj/blob/40c678e7264d8adbfa6e318767b15deb0926a0a5/rskj-core/src/main/java/co/rsk/net/handler/TxValidator.java#L64): Take the required action to fix the issue indicated by this comment. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1134)
1. ![MAJOR][MAJOR] [BridgeSerializationUtils.java#L122](https://github.com/rsksmart/rskj/blob/40c678e7264d8adbfa6e318767b15deb0926a0a5/rskj-core/src/main/java/co/rsk/peg/BridgeSerializationUtils.java#L122): Method co.rsk.peg.BridgeSerializationUtils.deserializeUTXOList(byte[]) does not presize the allocation of a collection [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APSC_PRESIZE_COLLECTIONS)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by tinchou** [comment]
Superseded by https://github.com/rsksmart/rskj/pull/406

**Pull request closed without merging**
