### PR TITLE
Just status remove execution result

### PR DESCRIPTION
**Pull request by adauto82**

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 42 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 16 major
* ![MINOR][MINOR] 4 minor
* ![INFO][INFO] 21 info

#### Top 10 issues

1. ![CRITICAL][CRITICAL] [TransactionReceipt.java#L51](https://github.com/rsksmart/rskj/blob/8e4f46ee592723f1b381532da4a253a006758941/rskj-core/src/main/java/org/ethereum/core/TransactionReceipt.java#L51): Make this member "protected". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2386)
1. ![MAJOR][MAJOR] [BlockExecutor.java#L152](https://github.com/rsksmart/rskj/blob/8e4f46ee592723f1b381532da4a253a006758941/rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java#L152): Method co.rsk.core.bc.BlockExecutor.validate(Block, BlockResult) appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [BlockExecutor.java#L229](https://github.com/rsksmart/rskj/blob/8e4f46ee592723f1b381532da4a253a006758941/rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java#L229): Method co.rsk.core.bc.BlockExecutor.execute(Block, byte[], boolean, boolean) does not presize the allocation of a collection [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APSC_PRESIZE_COLLECTIONS)
1. ![MAJOR][MAJOR] [BlockExecutor.java#L264](https://github.com/rsksmart/rskj/blob/8e4f46ee592723f1b381532da4a253a006758941/rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java#L264): Method co.rsk.core.bc.BlockExecutor.execute(Block, byte[], boolean, boolean) does not presize the allocation of a collection [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APSC_PRESIZE_COLLECTIONS)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L94](https://github.com/rsksmart/rskj/blob/8e4f46ee592723f1b381532da4a253a006758941/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L94): Constructor has 8 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L99](https://github.com/rsksmart/rskj/blob/8e4f46ee592723f1b381532da4a253a006758941/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L99): Constructor has 10 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L122](https://github.com/rsksmart/rskj/blob/8e4f46ee592723f1b381532da4a253a006758941/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L122): The Cyclomatic Complexity of this method "init" is 14 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L141](https://github.com/rsksmart/rskj/blob/8e4f46ee592723f1b381532da4a253a006758941/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L141): Method org.ethereum.core.TransactionExecutor.init() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L142](https://github.com/rsksmart/rskj/blob/8e4f46ee592723f1b381532da4a253a006758941/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L142): Method org.ethereum.core.TransactionExecutor.init() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L280](https://github.com/rsksmart/rskj/blob/8e4f46ee592723f1b381532da4a253a006758941/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L280): Take the required action to fix the issue indicated by this comment. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1134)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 39 issues
* ![MAJOR][MAJOR] 15 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 21 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [BlockExecutor.java#L152](https://github.com/rsksmart/rskj/blob/58345eb2bbf21a10ab299c442d37493cd3ddd288/rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java#L152): Method co.rsk.core.bc.BlockExecutor.validate(Block, BlockResult) appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [BlockExecutor.java#L229](https://github.com/rsksmart/rskj/blob/58345eb2bbf21a10ab299c442d37493cd3ddd288/rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java#L229): Method co.rsk.core.bc.BlockExecutor.execute(Block, byte[], boolean, boolean) does not presize the allocation of a collection [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APSC_PRESIZE_COLLECTIONS)
1. ![MAJOR][MAJOR] [BlockExecutor.java#L264](https://github.com/rsksmart/rskj/blob/58345eb2bbf21a10ab299c442d37493cd3ddd288/rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java#L264): Method co.rsk.core.bc.BlockExecutor.execute(Block, byte[], boolean, boolean) does not presize the allocation of a collection [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APSC_PRESIZE_COLLECTIONS)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L94](https://github.com/rsksmart/rskj/blob/58345eb2bbf21a10ab299c442d37493cd3ddd288/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L94): Constructor has 8 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L99](https://github.com/rsksmart/rskj/blob/58345eb2bbf21a10ab299c442d37493cd3ddd288/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L99): Constructor has 10 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L122](https://github.com/rsksmart/rskj/blob/58345eb2bbf21a10ab299c442d37493cd3ddd288/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L122): The Cyclomatic Complexity of this method "init" is 14 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L141](https://github.com/rsksmart/rskj/blob/58345eb2bbf21a10ab299c442d37493cd3ddd288/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L141): Method org.ethereum.core.TransactionExecutor.init() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L142](https://github.com/rsksmart/rskj/blob/58345eb2bbf21a10ab299c442d37493cd3ddd288/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L142): Method org.ethereum.core.TransactionExecutor.init() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L280](https://github.com/rsksmart/rskj/blob/58345eb2bbf21a10ab299c442d37493cd3ddd288/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L280): Take the required action to fix the issue indicated by this comment. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1134)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L338](https://github.com/rsksmart/rskj/blob/58345eb2bbf21a10ab299c442d37493cd3ddd288/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L338): The Cyclomatic Complexity of this method "go" is 11 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 62 issues
* ![MAJOR][MAJOR] 27 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 32 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [BlockExecutor.java#L152](https://github.com/rsksmart/rskj/blob/5b6320eee88fd15cee52b74a2e2cada69b8d490e/rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java#L152): Method co.rsk.core.bc.BlockExecutor.validate(Block, BlockResult) appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [BlockExecutor.java#L229](https://github.com/rsksmart/rskj/blob/5b6320eee88fd15cee52b74a2e2cada69b8d490e/rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java#L229): Method co.rsk.core.bc.BlockExecutor.execute(Block, byte[], boolean, boolean) does not presize the allocation of a collection [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APSC_PRESIZE_COLLECTIONS)
1. ![MAJOR][MAJOR] [BlockExecutor.java#L264](https://github.com/rsksmart/rskj/blob/5b6320eee88fd15cee52b74a2e2cada69b8d490e/rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java#L264): Method co.rsk.core.bc.BlockExecutor.execute(Block, byte[], boolean, boolean) does not presize the allocation of a collection [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APSC_PRESIZE_COLLECTIONS)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L94](https://github.com/rsksmart/rskj/blob/5b6320eee88fd15cee52b74a2e2cada69b8d490e/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L94): Constructor has 8 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L99](https://github.com/rsksmart/rskj/blob/5b6320eee88fd15cee52b74a2e2cada69b8d490e/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L99): Constructor has 10 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L122](https://github.com/rsksmart/rskj/blob/5b6320eee88fd15cee52b74a2e2cada69b8d490e/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L122): The Cyclomatic Complexity of this method "init" is 14 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L141](https://github.com/rsksmart/rskj/blob/5b6320eee88fd15cee52b74a2e2cada69b8d490e/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L141): Method org.ethereum.core.TransactionExecutor.init() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L142](https://github.com/rsksmart/rskj/blob/5b6320eee88fd15cee52b74a2e2cada69b8d490e/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L142): Method org.ethereum.core.TransactionExecutor.init() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L280](https://github.com/rsksmart/rskj/blob/5b6320eee88fd15cee52b74a2e2cada69b8d490e/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L280): Take the required action to fix the issue indicated by this comment. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1134)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L338](https://github.com/rsksmart/rskj/blob/5b6320eee88fd15cee52b74a2e2cada69b8d490e/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L338): The Cyclomatic Complexity of this method "go" is 11 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 65 issues
* ![CRITICAL][CRITICAL] 2 critical
* ![MAJOR][MAJOR] 27 major
* ![MINOR][MINOR] 4 minor
* ![INFO][INFO] 32 info

#### Top 10 issues

1. ![CRITICAL][CRITICAL] [TransactionReceiptDTO.java#L27](https://github.com/rsksmart/rskj/blob/5b6320eee88fd15cee52b74a2e2cada69b8d490e/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionReceiptDTO.java#L27): Unused import - java.util.Arrays. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck)
1. ![CRITICAL][CRITICAL] [TransactionReceiptDTO.java#L30](https://github.com/rsksmart/rskj/blob/5b6320eee88fd15cee52b74a2e2cada69b8d490e/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionReceiptDTO.java#L30): Unused import - org.ethereum.util.ByteUtil.EMPTY_BYTE_ARRAY. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck)
1. ![MAJOR][MAJOR] [BlockExecutor.java#L152](https://github.com/rsksmart/rskj/blob/5b6320eee88fd15cee52b74a2e2cada69b8d490e/rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java#L152): Method co.rsk.core.bc.BlockExecutor.validate(Block, BlockResult) appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [BlockExecutor.java#L229](https://github.com/rsksmart/rskj/blob/5b6320eee88fd15cee52b74a2e2cada69b8d490e/rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java#L229): Method co.rsk.core.bc.BlockExecutor.execute(Block, byte[], boolean, boolean) does not presize the allocation of a collection [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APSC_PRESIZE_COLLECTIONS)
1. ![MAJOR][MAJOR] [BlockExecutor.java#L264](https://github.com/rsksmart/rskj/blob/5b6320eee88fd15cee52b74a2e2cada69b8d490e/rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java#L264): Method co.rsk.core.bc.BlockExecutor.execute(Block, byte[], boolean, boolean) does not presize the allocation of a collection [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APSC_PRESIZE_COLLECTIONS)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L94](https://github.com/rsksmart/rskj/blob/5b6320eee88fd15cee52b74a2e2cada69b8d490e/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L94): Constructor has 8 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L99](https://github.com/rsksmart/rskj/blob/5b6320eee88fd15cee52b74a2e2cada69b8d490e/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L99): Constructor has 10 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L122](https://github.com/rsksmart/rskj/blob/5b6320eee88fd15cee52b74a2e2cada69b8d490e/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L122): The Cyclomatic Complexity of this method "init" is 14 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L141](https://github.com/rsksmart/rskj/blob/5b6320eee88fd15cee52b74a2e2cada69b8d490e/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L141): Method org.ethereum.core.TransactionExecutor.init() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L142](https://github.com/rsksmart/rskj/blob/5b6320eee88fd15cee52b74a2e2cada69b8d490e/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L142): Method org.ethereum.core.TransactionExecutor.init() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 64 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 27 major
* ![MINOR][MINOR] 4 minor
* ![INFO][INFO] 32 info

#### Top 10 issues

1. ![CRITICAL][CRITICAL] [TransactionReceiptDTO.java#L27](https://github.com/rsksmart/rskj/blob/44fc08701966b1905827cdafdb4b2c83868572be/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionReceiptDTO.java#L27): Unused import - java.util.Arrays. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck)
1. ![MAJOR][MAJOR] [BlockExecutor.java#L152](https://github.com/rsksmart/rskj/blob/44fc08701966b1905827cdafdb4b2c83868572be/rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java#L152): Method co.rsk.core.bc.BlockExecutor.validate(Block, BlockResult) appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [BlockExecutor.java#L229](https://github.com/rsksmart/rskj/blob/44fc08701966b1905827cdafdb4b2c83868572be/rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java#L229): Method co.rsk.core.bc.BlockExecutor.execute(Block, byte[], boolean, boolean) does not presize the allocation of a collection [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APSC_PRESIZE_COLLECTIONS)
1. ![MAJOR][MAJOR] [BlockExecutor.java#L264](https://github.com/rsksmart/rskj/blob/44fc08701966b1905827cdafdb4b2c83868572be/rskj-core/src/main/java/co/rsk/core/bc/BlockExecutor.java#L264): Method co.rsk.core.bc.BlockExecutor.execute(Block, byte[], boolean, boolean) does not presize the allocation of a collection [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APSC_PRESIZE_COLLECTIONS)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L94](https://github.com/rsksmart/rskj/blob/44fc08701966b1905827cdafdb4b2c83868572be/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L94): Constructor has 8 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L99](https://github.com/rsksmart/rskj/blob/44fc08701966b1905827cdafdb4b2c83868572be/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L99): Constructor has 10 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L122](https://github.com/rsksmart/rskj/blob/44fc08701966b1905827cdafdb4b2c83868572be/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L122): The Cyclomatic Complexity of this method "init" is 14 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L141](https://github.com/rsksmart/rskj/blob/44fc08701966b1905827cdafdb4b2c83868572be/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L141): Method org.ethereum.core.TransactionExecutor.init() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L142](https://github.com/rsksmart/rskj/blob/44fc08701966b1905827cdafdb4b2c83868572be/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L142): Method org.ethereum.core.TransactionExecutor.init() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L280](https://github.com/rsksmart/rskj/blob/44fc08701966b1905827cdafdb4b2c83868572be/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L280): Take the required action to fix the issue indicated by this comment. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1134)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by aeidelman** [comment]
@ajlopezrsk please review again since there have been new changes since your last review

**Pull request merged**
