### PR TITLE
Merge hop401 into hop411

### PR DESCRIPTION
**Pull request by marcos-iov**
*fed:HOP-4.0.1.0-rc*
*ci:new-erp-script*
*fit:new-erp-script*

### CODE REVIEW

**Review by josedahlquist — APPROVED** [review]

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Pull request merged**
