### PR TITLE
Tech debt integration

### PR DESCRIPTION
**Pull request by nathanieliov**
Summary

- Created an enum containing the index values used in BridgeStorageProvider. Also, used this enum in BridgeStorageProviderTest class replacing the use of strings literals for reference key index.
- Deleted BridgeSupportTestBase class. Moved methods that are common to different test classes into a Utils class as static methods.

### CODE REVIEW

**Review by marcos-iov — DISMISSED** [review]

**Comment by nathanieliov** [comment]
pipeline:run

**Comment by nathanieliov** [comment]
pipeline:run

**Comment by nathanieliov** [comment]
pipeline:run

**Comment by nathanieliov** [comment]
pipeline:run

**Comment by nathanieliov** [comment]
pipeline:run

**Comment by nathanieliov** [comment]
pipeline:run

**Comment by nathanieliov** [comment]
pipeline:run

**Comment by nathanieliov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Pull request merged**
