### PR TITLE
Use `ImmutableList.copyOf(list)` instead of `Collections.unmodifiable…

### LINKED ISSUE #1158: Transaction and Uncles Lists in Block are not Immutable
This code is from one of the `Block` constructors:

```
        this.transactionsList = Collections.unmodifiableList(transactionsList);
        this.uncleList = Collections.unmodifiableList(uncleList);

```

Altough this code prevents the modification of `this.transactionList` directly, the original list could still be modified externally, affecting the integrity of the block.

To prevent such behavior, maybe a list copy with unmodifiable view could be used.

### PR DESCRIPTION
**Pull request by kiminuo**
…List(list)`

Fixes #1158

### CODE REVIEW

**Comment by fedejinich** [comment]
why should we use google collection instead of java native implementation?

**Comment by kiminuo** [comment]
@fedejinich Have you read the original issue?

> Altough this code prevents the modification of this.transactionList directly, the original list could still be modified externally, affecting the integrity of the block.

And that's why using a 3rd party library may make sense in this case. Because Google's immutable list won't change. The items are still mutable though. In the current version and even in the proposed PR version.

This PR targets Java 8. Java 9+ would allow to use `List.of()` which would be ideal.

**Comment by fedejinich** [comment]
pipeline: run

**Comment by fedejinich** [comment]
pipeline: run

**Pull request merged**
