### PR TITLE
[PAPYRUS-2.2.0-rc] Make num of account slots for pending txs configurable

### PR DESCRIPTION
**Pull request by Vovchyk**
## Description

This change makes the number of account slots for pending transactions in a tx pool configurable.

## Motivation and Context

Instead of using hardcoded value, this allows us to configure it.

## How Has This Been Tested?

unit tests and running the node locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

*fit: 2.2-rc*

### CODE REVIEW

**Comment by Vovchyk** [comment]
pipeline: run

**Review by donequis — APPROVED** [review]

**Comment by Vovchyk** [comment]
pipeline: run

**Review by patogallaiovlabs — DISMISSED** [review]

**Comment by patogallaiovlabs** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
piepline: run

**Comment by Vovchyk** [comment]
piepline: run

**Review by ajlopezrsk — APPROVED** [review]

**Comment by Vovchyk** [comment]
piepline: run

**Pull request merged**
