### PR TITLE
Update bitcoinj-thin dependency to version 0.14.4-rsk-13

### PR DESCRIPTION
**Pull request by marcos-iov**
*fed:bitcoinj-thin-update*

### CODE REVIEW

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Review by jeremy-then — APPROVED** [review]
LGTM.

**Review by Vovchyk — APPROVED** [review]

**Review by illuque-iov — APPROVED** [review]

**Review by nathanieliov — APPROVED** [review]
LGTM

**Comment by marcos-iov** [comment]
This was already included in rsk version 4.0.1 along with bitcoinj-thin v14

**Pull request closed without merging**
