### PR TITLE
Automated reproducible on prerelease

### PR DESCRIPTION
**Pull request by alejandrod-iov**
Automated reproducible

## Description
This change triggers an automated reproducible generation using a Github Action providing hash checksum and jar files on prerelease

## Motivation and Context
Avoid human intervention on hash and reproducible generation related tasks

## How Has This Been Tested?
On forked repository made a github action workflow and reproduced using a Dockerfile as seen on `reproducible-builds` repo

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

### CODE REVIEW

**Review by lucasvuotto — APPROVED** [review]
LGTM

**Comment by lucasvuotto** [comment]
pipeline: run

**Comment by lucasvuotto** [comment]
pipeline: run

**Review by bcodesido — APPROVED** [review]
LGTM

**Pull request closed without merging**
