### PR TITLE
.clone() added to getBlockHash to avoid the chance of writing on sensitive data

### PR DESCRIPTION
**Pull request by lsebrie**
When we introduce data on a Dataword it's by reference by default, so to avoid that a blockHash could be written by another class, a change is to introduced to return a copy of the Dataword

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 41 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 29 major
* ![MINOR][MINOR] 4 minor
* ![INFO][INFO] 2 info

#### Top 10 issues

1. ![CRITICAL][CRITICAL] [Program.java#L186](https://github.com/rsksmart/rskj/blob/9e4c5ea0ba20d83c422ebc3ef1274d2bae2d3a12/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L186): Explicitly declare the visibility for "isLogEnabled". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2039)
1. ![CRITICAL][CRITICAL] [Program.java#L187](https://github.com/rsksmart/rskj/blob/9e4c5ea0ba20d83c422ebc3ef1274d2bae2d3a12/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L187): Explicitly declare the visibility for "isGasLogEnabled". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2039)
1. ![CRITICAL][CRITICAL] [Program.java#L228](https://github.com/rsksmart/rskj/blob/9e4c5ea0ba20d83c422ebc3ef1274d2bae2d3a12/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L228): Remove this call from a constructor to the overridable "precompile" method. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1699)
1. ![CRITICAL][CRITICAL] [Program.java#L812](https://github.com/rsksmart/rskj/blob/9e4c5ea0ba20d83c422ebc3ef1274d2bae2d3a12/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L812): Method org.ethereum.vm.program.Program.callToAddress(MessageCall) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![CRITICAL][CRITICAL] [Program.java#L1429](https://github.com/rsksmart/rskj/blob/9e4c5ea0ba20d83c422ebc3ef1274d2bae2d3a12/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L1429): Explicitly declare the visibility for "code". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2039)
1. ![CRITICAL][CRITICAL] [Program.java#L1430](https://github.com/rsksmart/rskj/blob/9e4c5ea0ba20d83c422ebc3ef1274d2bae2d3a12/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L1430): Explicitly declare the visibility for "pc". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2039)
1. ![MAJOR][MAJOR] [Program.java#](https://github.com/rsksmart/rskj/blob/9e4c5ea0ba20d83c422ebc3ef1274d2bae2d3a12/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#): This file has 1,210 lines, which is greater than 1,000 authorized. Split it into smaller files. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Program.java#L182](https://github.com/rsksmart/rskj/blob/9e4c5ea0ba20d83c422ebc3ef1274d2bae2d3a12/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L182): Method org.ethereum.vm.program.Program.<static initializer for Program>() needlessly boxes a boolean constant [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ANAB_NEEDLESS_BOOLEAN_CONSTANT_CONVERSION)
1. ![MAJOR][MAJOR] [Program.java#L228](https://github.com/rsksmart/rskj/blob/9e4c5ea0ba20d83c422ebc3ef1274d2bae2d3a12/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L228): Constructor new org.ethereum.vm.program.Program(VmConfig, PrecompiledContracts, BlockchainConfig, byte[], ProgramInvoke, Transaction) makes call to non-final method [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APCOA_PARTIALLY_CONSTRUCTED_OBJECT_ACCESS)
1. ![MAJOR][MAJOR] [Program.java#L589](https://github.com/rsksmart/rskj/blob/9e4c5ea0ba20d83c422ebc3ef1274d2bae2d3a12/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L589): The Cyclomatic Complexity of this method "createContract" is 18 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by donequis** [comment]
DataWord should be a final class now that I think about it

**Comment by donequis** [comment]
@tinchou Making Dataword immutable will force us to alloc more memory when doing some operations with dispensable data. For example, if we have A and B on the stack and we want to add them, we can override A with A+B instead of creating a new object for A+B

**Comment by rskops** [comment]
SonarQube analysis reported 77 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 38 major
* ![MINOR][MINOR] 18 minor
* ![INFO][INFO] 15 info

#### Top 10 issues

1. ![CRITICAL][CRITICAL] [Program.java#L186](https://github.com/rsksmart/rskj/blob/59871da6deca92d595dbdccbb9245b6949221e6c/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L186): Explicitly declare the visibility for "isLogEnabled". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2039)
1. ![CRITICAL][CRITICAL] [Program.java#L187](https://github.com/rsksmart/rskj/blob/59871da6deca92d595dbdccbb9245b6949221e6c/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L187): Explicitly declare the visibility for "isGasLogEnabled". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2039)
1. ![CRITICAL][CRITICAL] [Program.java#L228](https://github.com/rsksmart/rskj/blob/59871da6deca92d595dbdccbb9245b6949221e6c/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L228): Remove this call from a constructor to the overridable "precompile" method. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1699)
1. ![CRITICAL][CRITICAL] [Program.java#L812](https://github.com/rsksmart/rskj/blob/59871da6deca92d595dbdccbb9245b6949221e6c/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L812): Method org.ethereum.vm.program.Program.callToAddress(MessageCall) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![CRITICAL][CRITICAL] [Program.java#L1429](https://github.com/rsksmart/rskj/blob/59871da6deca92d595dbdccbb9245b6949221e6c/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L1429): Explicitly declare the visibility for "code". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2039)
1. ![CRITICAL][CRITICAL] [Program.java#L1430](https://github.com/rsksmart/rskj/blob/59871da6deca92d595dbdccbb9245b6949221e6c/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L1430): Explicitly declare the visibility for "pc". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2039)
1. ![MAJOR][MAJOR] [DataWord.java#L126](https://github.com/rsksmart/rskj/blob/59871da6deca92d595dbdccbb9245b6949221e6c/rskj-core/src/main/java/org/ethereum/vm/DataWord.java#L126): Invocation of toString on data in org.ethereum.vm.DataWord.assign(byte[]) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3ADMI_INVOKING_TOSTRING_ON_ARRAY)
1. ![MAJOR][MAJOR] [DataWord.java#L141](https://github.com/rsksmart/rskj/blob/59871da6deca92d595dbdccbb9245b6949221e6c/rskj-core/src/main/java/org/ethereum/vm/DataWord.java#L141): Invocation of toString on data in org.ethereum.vm.DataWord.assignDataRange(byte[], int, int) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3ADMI_INVOKING_TOSTRING_ON_ARRAY)
1. ![MAJOR][MAJOR] [DataWord.java#L151](https://github.com/rsksmart/rskj/blob/59871da6deca92d595dbdccbb9245b6949221e6c/rskj-core/src/main/java/org/ethereum/vm/DataWord.java#L151): Invocation of toString on data in org.ethereum.vm.DataWord.assignData(byte[]) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3ADMI_INVOKING_TOSTRING_ON_ARRAY)
1. ![MAJOR][MAJOR] [DataWord.java#L320](https://github.com/rsksmart/rskj/blob/59871da6deca92d595dbdccbb9245b6949221e6c/rskj-core/src/main/java/org/ethereum/vm/DataWord.java#L320): Rename method "zero" to prevent any misunderstanding/clash with field "ZERO" defined on line 46. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1845)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by adauto82** [comment]
Check SonarQube

**Pull request merged**
