### PR TITLE
Improve unit tests

### PR DESCRIPTION
**Pull request by guidohernan93**

### CODE REVIEW

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by alejandrod-iov** [comment]
pipeline:run

**Comment by alejandrod-iov** [comment]
pipeline:run

**Comment by alejandrod-iov** [comment]
pipeline:run

**Comment by alejandrod-iov** [comment]
pipeline:run

**Comment by alejandrod-iov** [comment]
pipeline:run

**Comment by alejandrod-iov** [comment]
pipeline:run

**Comment by alejandrod-iov** [comment]
pipeline:run

**Comment by alejandrod-iov** [comment]
pipeline:run

**Comment by alejandrod-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Pull request merged**
