### PR TITLE
Change Trie Serialization/Deserialization

### PR DESCRIPTION
**Pull request by ajlopezrsk**
These changes are motivated by issue #265 

Now, long values (with MORE than 32 bytes) are serialized and deserialized using their hashes.

The changes alter the root hashes of the states, and they are oriented only to prevent a future hard fork. The use of a Partial Merkled Tree should be improved, but after planning meeting discussion, it was posponed: they is no use of that class, yet.

Any change out the initial scope, was avoided.

Additional tests was added, and local manual tests were executed, with success. A full devnet test cycle is still pending.

### CODE REVIEW

**Comment by aeidelman** [comment]
@ajlopezrsk please check failing test.

**Comment by rskops** [comment]
SonarQube analysis reported 114 issues
* ![MAJOR][MAJOR] 15 major
* ![MINOR][MINOR] 93 minor
* ![INFO][INFO] 6 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [TrieImpl.java#L201](https://github.com/rsksmart/rskj/blob/944b252c2811cb18c8f7c31ea64a08931e945abe/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L201): The Cyclomatic Complexity of this method "fromMessage" is 12 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [TrieImpl.java#L256](https://github.com/rsksmart/rskj/blob/944b252c2811cb18c8f7c31ea64a08931e945abe/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L256): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS134)
1. ![MAJOR][MAJOR] [TrieImpl.java#L443](https://github.com/rsksmart/rskj/blob/944b252c2811cb18c8f7c31ea64a08931e945abe/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L443): The Cyclomatic Complexity of this method "toMessage" is 12 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [TrieImpl.java#L551](https://github.com/rsksmart/rskj/blob/944b252c2811cb18c8f7c31ea64a08931e945abe/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L551): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [TrieImpl.java#L554](https://github.com/rsksmart/rskj/blob/944b252c2811cb18c8f7c31ea64a08931e945abe/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L554): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [TrieImpl.java#L564](https://github.com/rsksmart/rskj/blob/944b252c2811cb18c8f7c31ea64a08931e945abe/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L564): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [TrieImpl.java#L644](https://github.com/rsksmart/rskj/blob/944b252c2811cb18c8f7c31ea64a08931e945abe/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L644): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [TrieImpl.java#L649](https://github.com/rsksmart/rskj/blob/944b252c2811cb18c8f7c31ea64a08931e945abe/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L649): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [TrieImpl.java#L859](https://github.com/rsksmart/rskj/blob/944b252c2811cb18c8f7c31ea64a08931e945abe/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L859): The Cyclomatic Complexity of this method "put" is 11 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [TrieImpl.java#L883](https://github.com/rsksmart/rskj/blob/944b252c2811cb18c8f7c31ea64a08931e945abe/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L883): Possible null pointer dereference of firstChild in co.rsk.trie.TrieImpl.put(byte[], int, int, byte[]) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3ANP_NULL_ON_SOME_PATH)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 28 issues
* ![MAJOR][MAJOR] 15 major
* ![MINOR][MINOR] 7 minor
* ![INFO][INFO] 6 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [TrieImpl.java#L206](https://github.com/rsksmart/rskj/blob/944b252c2811cb18c8f7c31ea64a08931e945abe/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L206): The Cyclomatic Complexity of this method "fromMessage" is 12 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [TrieImpl.java#L266](https://github.com/rsksmart/rskj/blob/944b252c2811cb18c8f7c31ea64a08931e945abe/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L266): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS134)
1. ![MAJOR][MAJOR] [TrieImpl.java#L462](https://github.com/rsksmart/rskj/blob/944b252c2811cb18c8f7c31ea64a08931e945abe/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L462): The Cyclomatic Complexity of this method "toMessage" is 12 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [TrieImpl.java#L579](https://github.com/rsksmart/rskj/blob/944b252c2811cb18c8f7c31ea64a08931e945abe/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L579): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [TrieImpl.java#L583](https://github.com/rsksmart/rskj/blob/944b252c2811cb18c8f7c31ea64a08931e945abe/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L583): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [TrieImpl.java#L595](https://github.com/rsksmart/rskj/blob/944b252c2811cb18c8f7c31ea64a08931e945abe/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L595): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [TrieImpl.java#L682](https://github.com/rsksmart/rskj/blob/944b252c2811cb18c8f7c31ea64a08931e945abe/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L682): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [TrieImpl.java#L688](https://github.com/rsksmart/rskj/blob/944b252c2811cb18c8f7c31ea64a08931e945abe/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L688): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [TrieImpl.java#L908](https://github.com/rsksmart/rskj/blob/944b252c2811cb18c8f7c31ea64a08931e945abe/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L908): The Cyclomatic Complexity of this method "put" is 11 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [TrieImpl.java#L935](https://github.com/rsksmart/rskj/blob/944b252c2811cb18c8f7c31ea64a08931e945abe/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L935): Possible null pointer dereference of firstChild in co.rsk.trie.TrieImpl.put(byte[], int, int, byte[]) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3ANP_NULL_ON_SOME_PATH)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 25 issues
* ![CRITICAL][CRITICAL] 2 critical
* ![MAJOR][MAJOR] 15 major
* ![MINOR][MINOR] 2 minor
* ![INFO][INFO] 6 info

#### Top 10 issues

1. ![CRITICAL][CRITICAL] [TrieImpl.java#L494](https://github.com/rsksmart/rskj/blob/38679c66f3920d286bf7ece4a67eee93336bf0a5/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L494): Missing curly brace. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00121)
1. ![CRITICAL][CRITICAL] [TrieImpl.java#L497](https://github.com/rsksmart/rskj/blob/38679c66f3920d286bf7ece4a67eee93336bf0a5/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L497): Missing curly brace. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00121)
1. ![MAJOR][MAJOR] [TrieImpl.java#L206](https://github.com/rsksmart/rskj/blob/38679c66f3920d286bf7ece4a67eee93336bf0a5/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L206): The Cyclomatic Complexity of this method "fromMessage" is 12 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [TrieImpl.java#L267](https://github.com/rsksmart/rskj/blob/38679c66f3920d286bf7ece4a67eee93336bf0a5/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L267): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS134)
1. ![MAJOR][MAJOR] [TrieImpl.java#L469](https://github.com/rsksmart/rskj/blob/38679c66f3920d286bf7ece4a67eee93336bf0a5/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L469): The Cyclomatic Complexity of this method "toMessage" is 12 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [TrieImpl.java#L595](https://github.com/rsksmart/rskj/blob/38679c66f3920d286bf7ece4a67eee93336bf0a5/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L595): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [TrieImpl.java#L599](https://github.com/rsksmart/rskj/blob/38679c66f3920d286bf7ece4a67eee93336bf0a5/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L599): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [TrieImpl.java#L611](https://github.com/rsksmart/rskj/blob/38679c66f3920d286bf7ece4a67eee93336bf0a5/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L611): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [TrieImpl.java#L698](https://github.com/rsksmart/rskj/blob/38679c66f3920d286bf7ece4a67eee93336bf0a5/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L698): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [TrieImpl.java#L704](https://github.com/rsksmart/rskj/blob/38679c66f3920d286bf7ece4a67eee93336bf0a5/rskj-core/src/main/java/co/rsk/trie/TrieImpl.java#L704): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
