### PR TITLE
Retrieving logs using bloom cache

### PR DESCRIPTION
**Pull request by ajlopezrsk**
These changes were tested on Testnet, using 0.6.1 release.

Out of scope: add configuration settings for number of blocks for confirmations. Now, it is hardcoded in 20 blocks. Only the logs of the confirmed blocks are added to the in-memory cache

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 9 issues

1. ![CRITICAL][CRITICAL] [Bloom.java#L41](https://github.com/rsksmart/rskj/blob/20e770a39bafc9cacb798191562b9af2b8079368/rskj-core/src/main/java/org/ethereum/core/Bloom.java#L41): Explicitly declare the visibility for "data". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2039)
1. ![MAJOR][MAJOR] [RskFactory.java#L359](https://github.com/rsksmart/rskj/blob/20e770a39bafc9cacb798191562b9af2b8079368/rskj-core/src/main/java/co/rsk/core/RskFactory.java#L359): java/nio/file/Paths.get(Ljava/lang/String;[Ljava/lang/String;)Ljava/nio/file/Path; reads a file whose location might be specified by user input [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3APATH_TRAVERSAL_IN)
1. ![MAJOR][MAJOR] [RskFactory.java#L360](https://github.com/rsksmart/rskj/blob/20e770a39bafc9cacb798191562b9af2b8079368/rskj-core/src/main/java/co/rsk/core/RskFactory.java#L360): java/nio/file/Paths.get(Ljava/lang/String;[Ljava/lang/String;)Ljava/nio/file/Path; reads a file whose location might be specified by user input [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3APATH_TRAVERSAL_IN)
1. ![MAJOR][MAJOR] [RskFactory.java#L366](https://github.com/rsksmart/rskj/blob/20e770a39bafc9cacb798191562b9af2b8079368/rskj-core/src/main/java/co/rsk/core/RskFactory.java#L366): java/io/FileOutputStream.<init>(Ljava/lang/String;)V writes to a file whose location might be specified by user input [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3APATH_TRAVERSAL_OUT)
1. ![MAJOR][MAJOR] [RskFactory.java#L534](https://github.com/rsksmart/rskj/blob/20e770a39bafc9cacb798191562b9af2b8079368/rskj-core/src/main/java/co/rsk/core/RskFactory.java#L534): Either log or rethrow this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [RskFactory.java#L707](https://github.com/rsksmart/rskj/blob/20e770a39bafc9cacb798191562b9af2b8079368/rskj-core/src/main/java/co/rsk/core/RskFactory.java#L707): java/io/File.<init>(Ljava/lang/String;)V reads a file whose location might be specified by user input [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3APATH_TRAVERSAL_IN)
1. ![MAJOR][MAJOR] [LogFilter.java#L213](https://github.com/rsksmart/rskj/blob/20e770a39bafc9cacb798191562b9af2b8079368/rskj-core/src/main/java/org/ethereum/rpc/LogFilter.java#L213): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS134)
1. ![MAJOR][MAJOR] [LogFilter.java#L217](https://github.com/rsksmart/rskj/blob/20e770a39bafc9cacb798191562b9af2b8079368/rskj-core/src/main/java/org/ethereum/rpc/LogFilter.java#L217): Refactor the code in order to not assign to this loop counter from within the loop body. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AForLoopCounterChangedCheck)
1. ![MINOR][MINOR] [BitSet.java#L65](https://github.com/rsksmart/rskj/blob/20e770a39bafc9cacb798191562b9af2b8079368/rskj-core/src/main/java/co/rsk/vm/BitSet.java#L65): Return a copy of "bytes". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2384)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 9 issues

1. ![CRITICAL][CRITICAL] [Bloom.java#L41](https://github.com/rsksmart/rskj/blob/c6f954efb4c386ff8af556e7ecfbc4f29f8de80c/rskj-core/src/main/java/org/ethereum/core/Bloom.java#L41): Explicitly declare the visibility for "data". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2039)
1. ![MAJOR][MAJOR] [RskFactory.java#L359](https://github.com/rsksmart/rskj/blob/c6f954efb4c386ff8af556e7ecfbc4f29f8de80c/rskj-core/src/main/java/co/rsk/core/RskFactory.java#L359): java/nio/file/Paths.get(Ljava/lang/String;[Ljava/lang/String;)Ljava/nio/file/Path; reads a file whose location might be specified by user input [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3APATH_TRAVERSAL_IN)
1. ![MAJOR][MAJOR] [RskFactory.java#L360](https://github.com/rsksmart/rskj/blob/c6f954efb4c386ff8af556e7ecfbc4f29f8de80c/rskj-core/src/main/java/co/rsk/core/RskFactory.java#L360): java/nio/file/Paths.get(Ljava/lang/String;[Ljava/lang/String;)Ljava/nio/file/Path; reads a file whose location might be specified by user input [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3APATH_TRAVERSAL_IN)
1. ![MAJOR][MAJOR] [RskFactory.java#L366](https://github.com/rsksmart/rskj/blob/c6f954efb4c386ff8af556e7ecfbc4f29f8de80c/rskj-core/src/main/java/co/rsk/core/RskFactory.java#L366): java/io/FileOutputStream.<init>(Ljava/lang/String;)V writes to a file whose location might be specified by user input [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3APATH_TRAVERSAL_OUT)
1. ![MAJOR][MAJOR] [RskFactory.java#L534](https://github.com/rsksmart/rskj/blob/c6f954efb4c386ff8af556e7ecfbc4f29f8de80c/rskj-core/src/main/java/co/rsk/core/RskFactory.java#L534): Either log or rethrow this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [RskFactory.java#L707](https://github.com/rsksmart/rskj/blob/c6f954efb4c386ff8af556e7ecfbc4f29f8de80c/rskj-core/src/main/java/co/rsk/core/RskFactory.java#L707): java/io/File.<init>(Ljava/lang/String;)V reads a file whose location might be specified by user input [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3APATH_TRAVERSAL_IN)
1. ![MAJOR][MAJOR] [LogFilter.java#L213](https://github.com/rsksmart/rskj/blob/c6f954efb4c386ff8af556e7ecfbc4f29f8de80c/rskj-core/src/main/java/org/ethereum/rpc/LogFilter.java#L213): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS134)
1. ![MAJOR][MAJOR] [LogFilter.java#L217](https://github.com/rsksmart/rskj/blob/c6f954efb4c386ff8af556e7ecfbc4f29f8de80c/rskj-core/src/main/java/org/ethereum/rpc/LogFilter.java#L217): Refactor the code in order to not assign to this loop counter from within the loop body. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AForLoopCounterChangedCheck)
1. ![MINOR][MINOR] [BitSet.java#L65](https://github.com/rsksmart/rskj/blob/c6f954efb4c386ff8af556e7ecfbc4f29f8de80c/rskj-core/src/main/java/co/rsk/vm/BitSet.java#L65): Return a copy of "bytes". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2384)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 10 issues

1. ![MAJOR][MAJOR] [RskFactory.java#L359](https://github.com/rsksmart/rskj/blob/f9dca96fb7a2f8d3494eb69a50e63d3a1706fdc7/rskj-core/src/main/java/co/rsk/core/RskFactory.java#L359): java/nio/file/Paths.get(Ljava/lang/String;[Ljava/lang/String;)Ljava/nio/file/Path; reads a file whose location might be specified by user input [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3APATH_TRAVERSAL_IN)
1. ![MAJOR][MAJOR] [RskFactory.java#L360](https://github.com/rsksmart/rskj/blob/f9dca96fb7a2f8d3494eb69a50e63d3a1706fdc7/rskj-core/src/main/java/co/rsk/core/RskFactory.java#L360): java/nio/file/Paths.get(Ljava/lang/String;[Ljava/lang/String;)Ljava/nio/file/Path; reads a file whose location might be specified by user input [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3APATH_TRAVERSAL_IN)
1. ![MAJOR][MAJOR] [RskFactory.java#L366](https://github.com/rsksmart/rskj/blob/f9dca96fb7a2f8d3494eb69a50e63d3a1706fdc7/rskj-core/src/main/java/co/rsk/core/RskFactory.java#L366): java/io/FileOutputStream.<init>(Ljava/lang/String;)V writes to a file whose location might be specified by user input [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3APATH_TRAVERSAL_OUT)
1. ![MAJOR][MAJOR] [RskFactory.java#L534](https://github.com/rsksmart/rskj/blob/f9dca96fb7a2f8d3494eb69a50e63d3a1706fdc7/rskj-core/src/main/java/co/rsk/core/RskFactory.java#L534): Either log or rethrow this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [RskFactory.java#L707](https://github.com/rsksmart/rskj/blob/f9dca96fb7a2f8d3494eb69a50e63d3a1706fdc7/rskj-core/src/main/java/co/rsk/core/RskFactory.java#L707): java/io/File.<init>(Ljava/lang/String;)V reads a file whose location might be specified by user input [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3APATH_TRAVERSAL_IN)
1. ![MAJOR][MAJOR] [LogFilter.java#L213](https://github.com/rsksmart/rskj/blob/f9dca96fb7a2f8d3494eb69a50e63d3a1706fdc7/rskj-core/src/main/java/org/ethereum/rpc/LogFilter.java#L213): Refactor this code to not nest more than 3 if/for/while/switch/try statements. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS134)
1. ![MAJOR][MAJOR] [LogFilter.java#L217](https://github.com/rsksmart/rskj/blob/f9dca96fb7a2f8d3494eb69a50e63d3a1706fdc7/rskj-core/src/main/java/org/ethereum/rpc/LogFilter.java#L217): Refactor the code in order to not assign to this loop counter from within the loop body. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AForLoopCounterChangedCheck)
1. ![MINOR][MINOR] [BitSet.java#L65](https://github.com/rsksmart/rskj/blob/f9dca96fb7a2f8d3494eb69a50e63d3a1706fdc7/rskj-core/src/main/java/co/rsk/vm/BitSet.java#L65): Return a copy of "bytes". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2384)
1. ![MINOR][MINOR] [Bloom.java#L47](https://github.com/rsksmart/rskj/blob/f9dca96fb7a2f8d3494eb69a50e63d3a1706fdc7/rskj-core/src/main/java/org/ethereum/core/Bloom.java#L47): Store a copy of "data". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2384)
1. ![MINOR][MINOR] [Bloom.java#L79](https://github.com/rsksmart/rskj/blob/f9dca96fb7a2f8d3494eb69a50e63d3a1706fdc7/rskj-core/src/main/java/org/ethereum/core/Bloom.java#L79): Return a copy of "data". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2384)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by ajlopezrsk** [comment]
BlocksBloomStore has no reference to a block. Moving this logic to BlocksBloomStore could infect it with new responsabilities, that live better in LogFilter.

The log filter logic could be rewritten, but it is out of scope for this pull request

> I think this looks good to merge. If I were coding it I would choose to make the `LogFilter#processBlocks` an instance method of `BlocksBloomStore`. There's an automatic refactor to do it:
> 
> image
> 
> After this, all the other methods of `BlocksBloomStore` would only accessed from tests, which means they would be exposing internal implementation details. I would rework those tests to only exercise the public interface, which in this case would be the `BlocksBloomStore#processBlocks`

**Pull request merged**
