### PR TITLE
Using temp directories in unit tests instead of user home directory

### PR DESCRIPTION
**Pull request by Vovchyk**
## Description
This PR updates unit tests in a way that user's home directory is not being used in tests anymore

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

* **Other information**:

### CODE REVIEW

**Review by asoto-iov — DISMISSED** [review]
In general everything is ok for me. Just a possible suggestion, what do you think about implement the logic of the TempDir into the RskTestContext class?
Additionally e could use a factory or default constructor to create it and avoid others to use it in a wrong way.
Also we could create default factory methods for testnet, regtest, etc.

**Comment by nagarev** [comment]
Nice! WDYT of github complaining about ignoring error statuses? maybe we could throw an exception if error is returned, it would be extremely rare tho.

**Review by nagarev — APPROVED** [review]
Nice! WDYT of github complaining about ignoring error statuses? maybe we could throw an exception if error is returned, it would be extremely rare tho.

**Comment by Vovchyk** [comment]
> In general everything is ok for me. Just a possible suggestion, what do you think about implement the logic of the TempDir into the RskTestContext class? Additionally e could use a factory or default constructor to create it and avoid others to use it in a wrong way. Also we could create default factory methods for testnet, regtest, etc.

the thing here is that `@TempDir` has to be a part of a unit test class

**Review by nagarev — APPROVED** [review]
LGTM!

**Review by rmoreliovlabs — APPROVED** [review]

**Pull request merged**
