### PR TITLE
Fix issues from QG

### PR DESCRIPTION
**Pull request by bcodesido**
Add missing curly braces.
Remove unused imports.
Move variables to comply with Java Code Conventions.
Remove unused private fields.
Remove unused loggers

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 373 issues
* ![CRITICAL][CRITICAL] 12 critical
* ![MAJOR][MAJOR] 224 major
* ![MINOR][MINOR] 41 minor
* ![INFO][INFO] 96 info

#### Top 10 issues

1. ![CRITICAL][CRITICAL] [Wallet.java#L211](https://github.com/rsksmart/rskj/blob/f978e3090d6abbbd14e3a62f8e4449f706e42ee8/rskj-core/src/main/java/co/rsk/core/Wallet.java#L211): Object deserialization is used in co.rsk.core.Wallet.decryptAES(byte[], byte[]) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3AOBJECT_DESERIALIZATION)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L119](https://github.com/rsksmart/rskj/blob/f978e3090d6abbbd14e3a62f8e4449f706e42ee8/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L119): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L127](https://github.com/rsksmart/rskj/blob/f978e3090d6abbbd14e3a62f8e4449f706e42ee8/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L127): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L139](https://github.com/rsksmart/rskj/blob/f978e3090d6abbbd14e3a62f8e4449f706e42ee8/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L139): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [TxBuilderEx.java#L72](https://github.com/rsksmart/rskj/blob/f978e3090d6abbbd14e3a62f8e4449f706e42ee8/rskj-core/src/main/java/co/rsk/mine/TxBuilderEx.java#L72): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [TxBuilderEx.java#L79](https://github.com/rsksmart/rskj/blob/f978e3090d6abbbd14e3a62f8e4449f706e42ee8/rskj-core/src/main/java/co/rsk/mine/TxBuilderEx.java#L79): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [TxBuilderEx.java#L87](https://github.com/rsksmart/rskj/blob/f978e3090d6abbbd14e3a62f8e4449f706e42ee8/rskj-core/src/main/java/co/rsk/mine/TxBuilderEx.java#L87): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [TxBuilderEx.java#L99](https://github.com/rsksmart/rskj/blob/f978e3090d6abbbd14e3a62f8e4449f706e42ee8/rskj-core/src/main/java/co/rsk/mine/TxBuilderEx.java#L99): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [TxBuilderEx.java#L127](https://github.com/rsksmart/rskj/blob/f978e3090d6abbbd14e3a62f8e4449f706e42ee8/rskj-core/src/main/java/co/rsk/mine/TxBuilderEx.java#L127): Cast one of the operands of this addition operation to a "long". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2184)
1. ![CRITICAL][CRITICAL] [TxBuilderEx.java#L131](https://github.com/rsksmart/rskj/blob/f978e3090d6abbbd14e3a62f8e4449f706e42ee8/rskj-core/src/main/java/co/rsk/mine/TxBuilderEx.java#L131): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by tinchou** [comment]
@aeidelman should we turn these rules to `critical` after this is merged? I think it's the best way to keep our codebase tidy. Now that we don't have any of these issues, we shouldn't allow them to happen again.

**Comment by aeidelman** [comment]
@bcodesido please resolve conflicts

**Comment by rskops** [comment]
SonarQube analysis reported 1521 issues
* ![BLOCKER][BLOCKER] 4 blocker
* ![CRITICAL][CRITICAL] 21 critical
* ![MAJOR][MAJOR] 940 major
* ![MINOR][MINOR] 171 minor
* ![INFO][INFO] 385 info

#### Top 10 issues

1. ![BLOCKER][BLOCKER] [Capability.java#L51](https://github.com/rsksmart/rskj/blob/16241bf5fb5c1040d91e36a3cb973312a6e40d7b/rskj-core/src/main/java/org/ethereum/net/client/Capability.java#L51): This class overrides "equals()" and should therefore also override "hashCode()". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1206)
1. ![BLOCKER][BLOCKER] [RlpxConnection.java#L62](https://github.com/rsksmart/rskj/blob/16241bf5fb5c1040d91e36a3cb973312a6e40d7b/rskj-core/src/main/java/org/ethereum/net/rlpx/RlpxConnection.java#L62): Check the return value of the "read" call to see how many bytes were read. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2674)
1. ![BLOCKER][BLOCKER] [RlpxConnection.java#L69](https://github.com/rsksmart/rskj/blob/16241bf5fb5c1040d91e36a3cb973312a6e40d7b/rskj-core/src/main/java/org/ethereum/net/rlpx/RlpxConnection.java#L69): Check the return value of the "read" call to see how many bytes were read. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2674)
1. ![BLOCKER][BLOCKER] [ProgramInvokeImpl.java#L306](https://github.com/rsksmart/rskj/blob/16241bf5fb5c1040d91e36a3cb973312a6e40d7b/rskj-core/src/main/java/org/ethereum/vm/program/invoke/ProgramInvokeImpl.java#L306): This class overrides "equals()" and should therefore also override "hashCode()". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1206)
1. ![CRITICAL][CRITICAL] [Wallet.java#L211](https://github.com/rsksmart/rskj/blob/16241bf5fb5c1040d91e36a3cb973312a6e40d7b/rskj-core/src/main/java/co/rsk/core/Wallet.java#L211): Object deserialization is used in co.rsk.core.Wallet.decryptAES(byte[], byte[]) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3AOBJECT_DESERIALIZATION)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L118](https://github.com/rsksmart/rskj/blob/16241bf5fb5c1040d91e36a3cb973312a6e40d7b/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L118): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L126](https://github.com/rsksmart/rskj/blob/16241bf5fb5c1040d91e36a3cb973312a6e40d7b/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L126): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L138](https://github.com/rsksmart/rskj/blob/16241bf5fb5c1040d91e36a3cb973312a6e40d7b/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L138): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [TxBuilderEx.java#L72](https://github.com/rsksmart/rskj/blob/16241bf5fb5c1040d91e36a3cb973312a6e40d7b/rskj-core/src/main/java/co/rsk/mine/TxBuilderEx.java#L72): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [TxBuilderEx.java#L79](https://github.com/rsksmart/rskj/blob/16241bf5fb5c1040d91e36a3cb973312a6e40d7b/rskj-core/src/main/java/co/rsk/mine/TxBuilderEx.java#L79): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 1518 issues
* ![BLOCKER][BLOCKER] 4 blocker
* ![CRITICAL][CRITICAL] 21 critical
* ![MAJOR][MAJOR] 938 major
* ![MINOR][MINOR] 171 minor
* ![INFO][INFO] 384 info

#### Top 10 issues

1. ![BLOCKER][BLOCKER] [Capability.java#L51](https://github.com/rsksmart/rskj/blob/3610dcdcb2e87cfdd88f17ce20ec8129f85e0373/rskj-core/src/main/java/org/ethereum/net/client/Capability.java#L51): This class overrides "equals()" and should therefore also override "hashCode()". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1206)
1. ![BLOCKER][BLOCKER] [RlpxConnection.java#L62](https://github.com/rsksmart/rskj/blob/3610dcdcb2e87cfdd88f17ce20ec8129f85e0373/rskj-core/src/main/java/org/ethereum/net/rlpx/RlpxConnection.java#L62): Check the return value of the "read" call to see how many bytes were read. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2674)
1. ![BLOCKER][BLOCKER] [RlpxConnection.java#L69](https://github.com/rsksmart/rskj/blob/3610dcdcb2e87cfdd88f17ce20ec8129f85e0373/rskj-core/src/main/java/org/ethereum/net/rlpx/RlpxConnection.java#L69): Check the return value of the "read" call to see how many bytes were read. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2674)
1. ![BLOCKER][BLOCKER] [ProgramInvokeImpl.java#L306](https://github.com/rsksmart/rskj/blob/3610dcdcb2e87cfdd88f17ce20ec8129f85e0373/rskj-core/src/main/java/org/ethereum/vm/program/invoke/ProgramInvokeImpl.java#L306): This class overrides "equals()" and should therefore also override "hashCode()". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1206)
1. ![CRITICAL][CRITICAL] [Wallet.java#L211](https://github.com/rsksmart/rskj/blob/3610dcdcb2e87cfdd88f17ce20ec8129f85e0373/rskj-core/src/main/java/co/rsk/core/Wallet.java#L211): Object deserialization is used in co.rsk.core.Wallet.decryptAES(byte[], byte[]) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3AOBJECT_DESERIALIZATION)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L118](https://github.com/rsksmart/rskj/blob/3610dcdcb2e87cfdd88f17ce20ec8129f85e0373/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L118): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L126](https://github.com/rsksmart/rskj/blob/3610dcdcb2e87cfdd88f17ce20ec8129f85e0373/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L126): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L138](https://github.com/rsksmart/rskj/blob/3610dcdcb2e87cfdd88f17ce20ec8129f85e0373/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L138): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [TxBuilderEx.java#L72](https://github.com/rsksmart/rskj/blob/3610dcdcb2e87cfdd88f17ce20ec8129f85e0373/rskj-core/src/main/java/co/rsk/mine/TxBuilderEx.java#L72): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [TxBuilderEx.java#L79](https://github.com/rsksmart/rskj/blob/3610dcdcb2e87cfdd88f17ce20ec8129f85e0373/rskj-core/src/main/java/co/rsk/mine/TxBuilderEx.java#L79): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
