### PR TITLE
Delete automatic rebase workflow from github actions

### PR DESCRIPTION
**Pull request by casiojapi**
Deleting unnecessary automatic rebase workflow from github actions.

IMPORTANT: whenever this is merged to master, we'll have to manually disable the "automatic rebase" workflow from the github UI. 

Apparently if that's not done it may continue running despite the yaml file not existing anymore inside the repo. (not sure why but I’ve seen lots of people talking about this error on forums when researching this task. So I believe we should do it just in case)

## Description
This GH action could be removed as it’s not being used and also there’s an alternative way of doing this by clicking Rebase & Merge button in the GH UI.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

### CODE REVIEW

**Comment by casiojapi** [comment]
pipeline:run

**Comment by casiojapi** [comment]
pipeline:run

**Review by illuque-iov — DISMISSED** [review]

**Comment by illuque-iov** [comment]
pipeline:run

**Comment by casiojapi** [comment]
pipeline:run

**Review by Vovchyk — APPROVED** [review]

**Comment by casiojapi** [comment]
pipeline:run

**Comment by casiojapi** [comment]
pipeline:run

**Review by Vovchyk — APPROVED** [review]

**Pull request merged**
