### PR TITLE
Add v, r and s EC values to JSON-RPC tx outputs

### PR DESCRIPTION
**Pull request by diega**
Improve compatibility with Web3 standard

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 6 issues

1. ![CRITICAL][CRITICAL] [TransactionResultDTO.java#L50](https://github.com/rsksmart/rskj/blob/9cf72ff32ace6868b01f36bae258a80de856129f/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L50): Make v a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [TransactionResultDTO.java#L51](https://github.com/rsksmart/rskj/blob/9cf72ff32ace6868b01f36bae258a80de856129f/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L51): Make r a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [TransactionResultDTO.java#L52](https://github.com/rsksmart/rskj/blob/9cf72ff32ace6868b01f36bae258a80de856129f/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L52): Make s a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![INFO][INFO] [TransactionResultDTO.java#L86](https://github.com/rsksmart/rskj/blob/9cf72ff32ace6868b01f36bae258a80de856129f/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L86): Unread public/protected field: org.ethereum.rpc.dto.TransactionResultDTO.v [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3AURF_UNREAD_PUBLIC_OR_PROTECTED_FIELD)
1. ![INFO][INFO] [TransactionResultDTO.java#L87](https://github.com/rsksmart/rskj/blob/9cf72ff32ace6868b01f36bae258a80de856129f/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L87): Unread public/protected field: org.ethereum.rpc.dto.TransactionResultDTO.r [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3AURF_UNREAD_PUBLIC_OR_PROTECTED_FIELD)
1. ![INFO][INFO] [TransactionResultDTO.java#L88](https://github.com/rsksmart/rskj/blob/9cf72ff32ace6868b01f36bae258a80de856129f/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L88): Unread public/protected field: org.ethereum.rpc.dto.TransactionResultDTO.s [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3AURF_UNREAD_PUBLIC_OR_PROTECTED_FIELD)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'

**Comment by tinchou** [comment]
Sonar reports shouldn't be tackled as part of this PR

**Comment by rskops** [comment]
SonarQube analysis reported 6 issues

1. ![CRITICAL][CRITICAL] [TransactionResultDTO.java#L50](https://github.com/rsksmart/rskj/blob/93d8484b67d477f80e0327b59ca9d4fe2f6b9c0c/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L50): Make v a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [TransactionResultDTO.java#L51](https://github.com/rsksmart/rskj/blob/93d8484b67d477f80e0327b59ca9d4fe2f6b9c0c/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L51): Make r a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [TransactionResultDTO.java#L52](https://github.com/rsksmart/rskj/blob/93d8484b67d477f80e0327b59ca9d4fe2f6b9c0c/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L52): Make s a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![INFO][INFO] [TransactionResultDTO.java#L86](https://github.com/rsksmart/rskj/blob/93d8484b67d477f80e0327b59ca9d4fe2f6b9c0c/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L86): Unread public/protected field: org.ethereum.rpc.dto.TransactionResultDTO.v [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3AURF_UNREAD_PUBLIC_OR_PROTECTED_FIELD)
1. ![INFO][INFO] [TransactionResultDTO.java#L87](https://github.com/rsksmart/rskj/blob/93d8484b67d477f80e0327b59ca9d4fe2f6b9c0c/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L87): Unread public/protected field: org.ethereum.rpc.dto.TransactionResultDTO.r [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3AURF_UNREAD_PUBLIC_OR_PROTECTED_FIELD)
1. ![INFO][INFO] [TransactionResultDTO.java#L88](https://github.com/rsksmart/rskj/blob/93d8484b67d477f80e0327b59ca9d4fe2f6b9c0c/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L88): Unread public/protected field: org.ethereum.rpc.dto.TransactionResultDTO.s [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3AURF_UNREAD_PUBLIC_OR_PROTECTED_FIELD)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'

**Comment by rskops** [comment]
SonarQube analysis reported 6 issues

1. ![CRITICAL][CRITICAL] [TransactionResultDTO.java#L50](https://github.com/rsksmart/rskj/blob/0ed6cbcbce1ab3930c9c3a13fed214a99bf55aa2/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L50): Make v a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [TransactionResultDTO.java#L51](https://github.com/rsksmart/rskj/blob/0ed6cbcbce1ab3930c9c3a13fed214a99bf55aa2/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L51): Make r a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![CRITICAL][CRITICAL] [TransactionResultDTO.java#L52](https://github.com/rsksmart/rskj/blob/0ed6cbcbce1ab3930c9c3a13fed214a99bf55aa2/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L52): Make s a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![INFO][INFO] [TransactionResultDTO.java#L86](https://github.com/rsksmart/rskj/blob/0ed6cbcbce1ab3930c9c3a13fed214a99bf55aa2/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L86): Unread public/protected field: org.ethereum.rpc.dto.TransactionResultDTO.v [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3AURF_UNREAD_PUBLIC_OR_PROTECTED_FIELD)
1. ![INFO][INFO] [TransactionResultDTO.java#L87](https://github.com/rsksmart/rskj/blob/0ed6cbcbce1ab3930c9c3a13fed214a99bf55aa2/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L87): Unread public/protected field: org.ethereum.rpc.dto.TransactionResultDTO.r [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3AURF_UNREAD_PUBLIC_OR_PROTECTED_FIELD)
1. ![INFO][INFO] [TransactionResultDTO.java#L88](https://github.com/rsksmart/rskj/blob/0ed6cbcbce1ab3930c9c3a13fed214a99bf55aa2/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L88): Unread public/protected field: org.ethereum.rpc.dto.TransactionResultDTO.s [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3AURF_UNREAD_PUBLIC_OR_PROTECTED_FIELD)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'

**Pull request merged**
