### PR TITLE
Fix hashcode and equals

### PR DESCRIPTION
**Pull request by casiojapi**
## Description

take into account host and port when comparing nodes and properly calculate hashcode of a node (by adding the calculation of the id internally)
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

* **Other information**:

### CODE REVIEW

**Comment by casiojapi** [comment]
pipeline:run

**Comment by casiojapi** [comment]
pipeline:run

**Comment by casiojapi** [comment]
pipeline:run

**Comment by casiojapi** [comment]
pipeline:run

**Comment by casiojapi** [comment]
pipeline:run

**Review by Vovchyk — DISMISSED** [review]

**Review by asoto-iov — DISMISSED** [review]

**Comment by casiojapi** [comment]
don't pay attention to the `github-code-scanning` warnings, I mistakenly pulled some commits that didn't belong in here. I just fixed that, now those warnings are outdated. sorry :/

**Review by Vovchyk — APPROVED** [review]

**Pull request merged**
