### PR TITLE
State trie clearing (EIP-161)

### PR DESCRIPTION
**Pull request by tinchou**
Testing involves some refactoring, so I split it in a separate PR for easier review: https://github.com/rsksmart/rskj/pull/283.

Based on:

* https://github.com/ethereum/EIPs/blob/master/EIPS/eip-161.md
* https://github.com/ethereum/ethereumj/commit/7a08a68c9eb1515737739754093d5668864c69cb
* https://github.com/ethereum/ethereumj/pull/625/files

Blocked by https://github.com/rsksmart/rskj/pull/278.

Note: I made many commits just to test a new development workflow. Feel free to request me to squash.

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 308 issues
* ![BLOCKER][BLOCKER] 1 blocker
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 99 major
* ![MINOR][MINOR] 134 minor
* ![INFO][INFO] 73 info

#### Top 10 issues

1. ![BLOCKER][BLOCKER] [TransactionExecutor.java#L373](https://github.com/rsksmart/rskj/blob/e250c5a2c324c125a45cc1c7071b8c9008773ec3/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L373): Catch Exception instead of Throwable. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1181)
1. ![CRITICAL][CRITICAL] [Program.java#L1611](https://github.com/rsksmart/rskj/blob/e250c5a2c324c125a45cc1c7071b8c9008773ec3/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L1611): Not enough arguments. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2275)
1. ![MAJOR][MAJOR] [AccountState.java#L170](https://github.com/rsksmart/rskj/blob/e250c5a2c324c125a45cc1c7071b8c9008773ec3/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L170): Rename "nonce" which hides the field declared at line 44. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. ![MAJOR][MAJOR] [AccountState.java#L171](https://github.com/rsksmart/rskj/blob/e250c5a2c324c125a45cc1c7071b8c9008773ec3/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L171): Rename "balance" which hides the field declared at line 47. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. ![MAJOR][MAJOR] [AccountState.java#L172](https://github.com/rsksmart/rskj/blob/e250c5a2c324c125a45cc1c7071b8c9008773ec3/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L172): Rename "stateRoot" which hides the field declared at line 59. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. ![MAJOR][MAJOR] [AccountState.java#L173](https://github.com/rsksmart/rskj/blob/e250c5a2c324c125a45cc1c7071b8c9008773ec3/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L173): Rename "codeHash" which hides the field declared at line 67. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. ![MAJOR][MAJOR] [AccountState.java#L175](https://github.com/rsksmart/rskj/blob/e250c5a2c324c125a45cc1c7071b8c9008773ec3/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L175): Rename "stateFlags" which hides the field declared at line 70. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. ![MAJOR][MAJOR] [AccountState.java#L200](https://github.com/rsksmart/rskj/blob/e250c5a2c324c125a45cc1c7071b8c9008773ec3/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L200): Remove this "clone" implementation; use a copy constructor or copy factory instead. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2975)
1. ![MAJOR][MAJOR] [AccountState.java#L200](https://github.com/rsksmart/rskj/blob/e250c5a2c324c125a45cc1c7071b8c9008773ec3/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L200): Use super.clone() to create and seed the cloned instance to be returned. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1182)
1. ![MAJOR][MAJOR] [AccountState.java#L201](https://github.com/rsksmart/rskj/blob/e250c5a2c324c125a45cc1c7071b8c9008773ec3/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L201): org.ethereum.core.AccountState defines clone() but doesn't implement Cloneable [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3ACN_IMPLEMENTS_CLONE_BUT_NOT_CLONEABLE)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 309 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 101 major
* ![MINOR][MINOR] 135 minor
* ![INFO][INFO] 72 info

#### Top 10 issues

1. ![CRITICAL][CRITICAL] [Program.java#L1611](https://github.com/rsksmart/rskj/blob/07a857f8addefaa46359cecd5556162f8a36172f/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L1611): Not enough arguments. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2275)
1. ![MAJOR][MAJOR] [AccountState.java#L170](https://github.com/rsksmart/rskj/blob/07a857f8addefaa46359cecd5556162f8a36172f/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L170): Rename "nonce" which hides the field declared at line 44. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. ![MAJOR][MAJOR] [AccountState.java#L171](https://github.com/rsksmart/rskj/blob/07a857f8addefaa46359cecd5556162f8a36172f/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L171): Rename "balance" which hides the field declared at line 47. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. ![MAJOR][MAJOR] [AccountState.java#L172](https://github.com/rsksmart/rskj/blob/07a857f8addefaa46359cecd5556162f8a36172f/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L172): Rename "stateRoot" which hides the field declared at line 59. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. ![MAJOR][MAJOR] [AccountState.java#L173](https://github.com/rsksmart/rskj/blob/07a857f8addefaa46359cecd5556162f8a36172f/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L173): Rename "codeHash" which hides the field declared at line 67. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. ![MAJOR][MAJOR] [AccountState.java#L175](https://github.com/rsksmart/rskj/blob/07a857f8addefaa46359cecd5556162f8a36172f/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L175): Rename "stateFlags" which hides the field declared at line 70. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. ![MAJOR][MAJOR] [AccountState.java#L200](https://github.com/rsksmart/rskj/blob/07a857f8addefaa46359cecd5556162f8a36172f/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L200): Remove this "clone" implementation; use a copy constructor or copy factory instead. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2975)
1. ![MAJOR][MAJOR] [AccountState.java#L200](https://github.com/rsksmart/rskj/blob/07a857f8addefaa46359cecd5556162f8a36172f/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L200): Use super.clone() to create and seed the cloned instance to be returned. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1182)
1. ![MAJOR][MAJOR] [AccountState.java#L201](https://github.com/rsksmart/rskj/blob/07a857f8addefaa46359cecd5556162f8a36172f/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L201): org.ethereum.core.AccountState defines clone() but doesn't implement Cloneable [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3ACN_IMPLEMENTS_CLONE_BUT_NOT_CLONEABLE)
1. ![MAJOR][MAJOR] [AccountState.java#L219](https://github.com/rsksmart/rskj/blob/07a857f8addefaa46359cecd5556162f8a36172f/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L219): Method org.ethereum.core.AccountState.toString() concatenates the result of a toString() call [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3AISB_TOSTRING_APPENDING)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 308 issues
* ![MAJOR][MAJOR] 101 major
* ![MINOR][MINOR] 135 minor
* ![INFO][INFO] 72 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [AccountState.java#L170](https://github.com/rsksmart/rskj/blob/07a857f8addefaa46359cecd5556162f8a36172f/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L170): Rename "nonce" which hides the field declared at line 44. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. ![MAJOR][MAJOR] [AccountState.java#L171](https://github.com/rsksmart/rskj/blob/07a857f8addefaa46359cecd5556162f8a36172f/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L171): Rename "balance" which hides the field declared at line 47. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. ![MAJOR][MAJOR] [AccountState.java#L172](https://github.com/rsksmart/rskj/blob/07a857f8addefaa46359cecd5556162f8a36172f/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L172): Rename "stateRoot" which hides the field declared at line 59. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. ![MAJOR][MAJOR] [AccountState.java#L173](https://github.com/rsksmart/rskj/blob/07a857f8addefaa46359cecd5556162f8a36172f/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L173): Rename "codeHash" which hides the field declared at line 67. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. ![MAJOR][MAJOR] [AccountState.java#L175](https://github.com/rsksmart/rskj/blob/07a857f8addefaa46359cecd5556162f8a36172f/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L175): Rename "stateFlags" which hides the field declared at line 70. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. ![MAJOR][MAJOR] [AccountState.java#L200](https://github.com/rsksmart/rskj/blob/07a857f8addefaa46359cecd5556162f8a36172f/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L200): Remove this "clone" implementation; use a copy constructor or copy factory instead. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2975)
1. ![MAJOR][MAJOR] [AccountState.java#L200](https://github.com/rsksmart/rskj/blob/07a857f8addefaa46359cecd5556162f8a36172f/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L200): Use super.clone() to create and seed the cloned instance to be returned. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1182)
1. ![MAJOR][MAJOR] [AccountState.java#L201](https://github.com/rsksmart/rskj/blob/07a857f8addefaa46359cecd5556162f8a36172f/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L201): org.ethereum.core.AccountState defines clone() but doesn't implement Cloneable [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3ACN_IMPLEMENTS_CLONE_BUT_NOT_CLONEABLE)
1. ![MAJOR][MAJOR] [AccountState.java#L219](https://github.com/rsksmart/rskj/blob/07a857f8addefaa46359cecd5556162f8a36172f/rskj-core/src/main/java/org/ethereum/core/AccountState.java#L219): Method org.ethereum.core.AccountState.toString() concatenates the result of a toString() call [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3AISB_TOSTRING_APPENDING)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L73](https://github.com/rsksmart/rskj/blob/07a857f8addefaa46359cecd5556162f8a36172f/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L73): Remove this unused "coinbase" private field. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1068)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by aeidelman** [comment]
This won't be implemented. Closing PR.

**Pull request closed without merging**
