### PR TITLE
Cleanup org.ethereum.vm package

### PR DESCRIPTION
**Pull request by tinchou**
* `public` -> `private` where possible
* delete unused code
* use `Integer.signum` in `DataWord.compareTo`

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 20 issues
* ![BLOCKER][BLOCKER] 3 blocker
* ![MAJOR][MAJOR] 5 major
* ![MINOR][MINOR] 12 minor

#### Top 10 issues

1. ![BLOCKER][BLOCKER] [Program.java#L770](https://github.com/rsksmart/rskj/blob/6171fbea3a50f866f9407af935d48ef43c17b818/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L770): "NullPointerException" will be thrown when invoking method "executeCode()". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2259)
1. ![BLOCKER][BLOCKER] [Program.java#L1369](https://github.com/rsksmart/rskj/blob/6171fbea3a50f866f9407af935d48ef43c17b818/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L1369): A "NullPointerException" could be thrown; "getCurOpcode()" can return null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2259)
1. ![BLOCKER][BLOCKER] [Program.java#L1374](https://github.com/rsksmart/rskj/blob/6171fbea3a50f866f9407af935d48ef43c17b818/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L1374): A "NullPointerException" could be thrown; "getCurOpcode()" can return null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2259)
1. ![MAJOR][MAJOR] [VM.java#L1407](https://github.com/rsksmart/rskj/blob/6171fbea3a50f866f9407af935d48ef43c17b818/rskj-core/src/main/java/org/ethereum/vm/VM.java#L1407): The Cyclomatic Complexity of this method "doCALL" is 12 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [VM.java#L1643](https://github.com/rsksmart/rskj/blob/6171fbea3a50f866f9407af935d48ef43c17b818/rskj-core/src/main/java/org/ethereum/vm/VM.java#L1643): The Cyclomatic Complexity of this method "executeOpcode" is 142 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [Program.java#L1112](https://github.com/rsksmart/rskj/blob/6171fbea3a50f866f9407af935d48ef43c17b818/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L1112): Method org.ethereum.vm.program.Program.fullTrace() passes constant String of length 1 to character overridden method [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3AUCPM_USE_CHARACTER_PARAMETERIZED_METHOD)
1. ![MAJOR][MAJOR] [Program.java#L1387](https://github.com/rsksmart/rskj/blob/6171fbea3a50f866f9407af935d48ef43c17b818/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L1387): The Cyclomatic Complexity of this method "buildReachableBytecodesMask" is 11 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [Program.java#L1601](https://github.com/rsksmart/rskj/blob/6171fbea3a50f866f9407af935d48ef43c17b818/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L1601): Should org.ethereum.vm.program.Program$StackTooLargeException be a _static_ inner class? [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3ASIC_INNER_SHOULD_BE_STATIC)
1. ![MINOR][MINOR] [CallCreate.java#L35](https://github.com/rsksmart/rskj/blob/6171fbea3a50f866f9407af935d48ef43c17b818/rskj-core/src/main/java/org/ethereum/vm/CallCreate.java#L35): Store a copy of "data". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2384)
1. ![MINOR][MINOR] [CallCreate.java#L36](https://github.com/rsksmart/rskj/blob/6171fbea3a50f866f9407af935d48ef43c17b818/rskj-core/src/main/java/org/ethereum/vm/CallCreate.java#L36): Store a copy of "destination". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2384)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 20 issues
* ![BLOCKER][BLOCKER] 1 blocker
* ![CRITICAL][CRITICAL] 3 critical
* ![MAJOR][MAJOR] 4 major
* ![MINOR][MINOR] 12 minor

#### Top 10 issues

1. ![BLOCKER][BLOCKER] [Program.java#L770](https://github.com/rsksmart/rskj/blob/9bd21b9071d373d530f8f267ea0cd211b8c5bff4/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L770): "NullPointerException" will be thrown when invoking method "executeCode()". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2259)
1. ![CRITICAL][CRITICAL] [Program.java#L38](https://github.com/rsksmart/rskj/blob/9bd21b9071d373d530f8f267ea0cd211b8c5bff4/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L38): Unused import - org.ethereum.util.Utils. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck)
1. ![CRITICAL][CRITICAL] [Program.java#L53](https://github.com/rsksmart/rskj/blob/9bd21b9071d373d530f8f267ea0cd211b8c5bff4/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L53): Unused import - java.io.ByteArrayOutputStream. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck)
1. ![CRITICAL][CRITICAL] [Program.java#L57](https://github.com/rsksmart/rskj/blob/9bd21b9071d373d530f8f267ea0cd211b8c5bff4/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L57): Unused import - java.lang.StrictMath.min. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck)
1. ![MAJOR][MAJOR] [VM.java#L1407](https://github.com/rsksmart/rskj/blob/9bd21b9071d373d530f8f267ea0cd211b8c5bff4/rskj-core/src/main/java/org/ethereum/vm/VM.java#L1407): The Cyclomatic Complexity of this method "doCALL" is 12 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [VM.java#L1643](https://github.com/rsksmart/rskj/blob/9bd21b9071d373d530f8f267ea0cd211b8c5bff4/rskj-core/src/main/java/org/ethereum/vm/VM.java#L1643): The Cyclomatic Complexity of this method "executeOpcode" is 142 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [Program.java#L1112](https://github.com/rsksmart/rskj/blob/9bd21b9071d373d530f8f267ea0cd211b8c5bff4/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L1112): Method org.ethereum.vm.program.Program.fullTrace() passes constant String of length 1 to character overridden method [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3AUCPM_USE_CHARACTER_PARAMETERIZED_METHOD)
1. ![MAJOR][MAJOR] [Program.java#L1456](https://github.com/rsksmart/rskj/blob/9bd21b9071d373d530f8f267ea0cd211b8c5bff4/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L1456): Should org.ethereum.vm.program.Program$StackTooLargeException be a _static_ inner class? [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3ASIC_INNER_SHOULD_BE_STATIC)
1. ![MINOR][MINOR] [CallCreate.java#L35](https://github.com/rsksmart/rskj/blob/9bd21b9071d373d530f8f267ea0cd211b8c5bff4/rskj-core/src/main/java/org/ethereum/vm/CallCreate.java#L35): Store a copy of "data". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2384)
1. ![MINOR][MINOR] [CallCreate.java#L36](https://github.com/rsksmart/rskj/blob/9bd21b9071d373d530f8f267ea0cd211b8c5bff4/rskj-core/src/main/java/org/ethereum/vm/CallCreate.java#L36): Store a copy of "destination". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2384)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 17 issues
* ![BLOCKER][BLOCKER] 1 blocker
* ![MAJOR][MAJOR] 4 major
* ![MINOR][MINOR] 12 minor

#### Top 10 issues

1. ![BLOCKER][BLOCKER] [Program.java#L767](https://github.com/rsksmart/rskj/blob/ed4f3a440fb65426e2052536d70ba0ad39b69676/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L767): "NullPointerException" will be thrown when invoking method "executeCode()". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2259)
1. ![MAJOR][MAJOR] [VM.java#L1407](https://github.com/rsksmart/rskj/blob/ed4f3a440fb65426e2052536d70ba0ad39b69676/rskj-core/src/main/java/org/ethereum/vm/VM.java#L1407): The Cyclomatic Complexity of this method "doCALL" is 12 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [VM.java#L1643](https://github.com/rsksmart/rskj/blob/ed4f3a440fb65426e2052536d70ba0ad39b69676/rskj-core/src/main/java/org/ethereum/vm/VM.java#L1643): The Cyclomatic Complexity of this method "executeOpcode" is 142 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [Program.java#L1108](https://github.com/rsksmart/rskj/blob/ed4f3a440fb65426e2052536d70ba0ad39b69676/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L1108): Method org.ethereum.vm.program.Program.fullTrace() passes constant String of length 1 to character overridden method [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3AUCPM_USE_CHARACTER_PARAMETERIZED_METHOD)
1. ![MAJOR][MAJOR] [Program.java#L1452](https://github.com/rsksmart/rskj/blob/ed4f3a440fb65426e2052536d70ba0ad39b69676/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L1452): Should org.ethereum.vm.program.Program$StackTooLargeException be a _static_ inner class? [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3ASIC_INNER_SHOULD_BE_STATIC)
1. ![MINOR][MINOR] [CallCreate.java#L35](https://github.com/rsksmart/rskj/blob/ed4f3a440fb65426e2052536d70ba0ad39b69676/rskj-core/src/main/java/org/ethereum/vm/CallCreate.java#L35): Store a copy of "data". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2384)
1. ![MINOR][MINOR] [CallCreate.java#L36](https://github.com/rsksmart/rskj/blob/ed4f3a440fb65426e2052536d70ba0ad39b69676/rskj-core/src/main/java/org/ethereum/vm/CallCreate.java#L36): Store a copy of "destination". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2384)
1. ![MINOR][MINOR] [CallCreate.java#L38](https://github.com/rsksmart/rskj/blob/ed4f3a440fb65426e2052536d70ba0ad39b69676/rskj-core/src/main/java/org/ethereum/vm/CallCreate.java#L38): Store a copy of "value". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2384)
1. ![MINOR][MINOR] [CallCreate.java#L42](https://github.com/rsksmart/rskj/blob/ed4f3a440fb65426e2052536d70ba0ad39b69676/rskj-core/src/main/java/org/ethereum/vm/CallCreate.java#L42): Return a copy of "data". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2384)
1. ![MINOR][MINOR] [CallCreate.java#L46](https://github.com/rsksmart/rskj/blob/ed4f3a440fb65426e2052536d70ba0ad39b69676/rskj-core/src/main/java/org/ethereum/vm/CallCreate.java#L46): Return a copy of "destination". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2384)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by tinchou** [comment]
I don't understand the reported `CRITICAL` issue, I don't think this is relevant.

**Comment by tinchou** [comment]
Will take another chance at this later on

**Pull request closed without merging**
