### PR TITLE
Add optional traceOptions param to debug_traceTransaction JSON-RPC api call

### LINKED ISSUE #1236: Truffle debug throwing 'method parameters invalid'
The Truffle debug tool is printing an error stack trace while trying to debug a Tx in the RSK testnet.

Having the RSK testnet network in the truffle.js file pointing to a private node connected to  said network, I run
`npx truffle debug 0x33d955a4b0ad5f72b313fb4d192f318848ebb55e3a86483841b4c17fe8f3238d --network rskTestnet`

This printed:
```
Starting Truffle Debugger...
✔ Compiling your contracts...
✖ Gathering information about your project and the transaction...
{ Error: method parameters invalid
    at ProviderError.ExtendableError (/..../node_modules/truffle/build/webpack:/packages/error/index.js:10:1)
......
   at process._tickDomainCallback (internal/process/next_tick.js:219:9)',
  name: 'ProviderError' }

Commands:
(enter) last command entered (step next)
(o) step over, (i) step into, (u) step out, (n) step next
(;) step instruction (include number to step multiple)
(p) print instruction & state (can specify locations, e.g. p mem; see docs)
(l) print additional source context, (s) print stacktrace, (h) print this help
(q) quit, (r) reset, (t) load new transaction, (T) unload transaction
(b) add breakpoint, (B) remove breakpoint, (c) continue until breakpoint
(+) add watch expression (`+:<expr>`), (-) remove watch expression (-:<expr>)
(?) list existing watch expressions and breakpoints
(v) print variables and values, (:) evaluate expression - see `v`
```
(I removed some output for privacy reasons of the project I'm working on and because I don't think it is relevant, if it is, let me know)

As you can see `method parameters invalid` seems to be the issue, and I could reproduce this using the debug_traceTransaction method directly with HTTP requests.

Using that request I found that 
`curl -X POST --data '{"jsonrpc":"2.0","method":"debug_traceTransaction","params":[<tx-hash>],"id":1}' --header "Content-Type:application/json" <host-url>` 
worked, but 
`curl -X POST --data '{"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0x33d955a4b0ad5f72b313fb4d192f318848ebb55e3a86483841b4c17fe8f3238d", {}],"id":1}' --header "Content-Type:application/json" http://45.79.72.117:4445
` didn't(printing 'method parameters invalid' too; note the second parameter '{}' in the body).

This in addition with the definition found [here](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#debug_tracetransaction) (which has the second parameter) makes me think that this is the issue found in truffle debug.

### PR DESCRIPTION
**Pull request by Vovchyk**
Resolves #1236

### CODE REVIEW

**Comment by patogallaiovlabs** [comment]
👍 +1 to the unit testing

**Comment by aeidelman** [comment]
pipeline: run

**Comment by jjtechuy** [comment]
pipeline: run

**Comment by jjtechuy** [comment]
pipeline: run

**Pull request merged**
