### PR TITLE
Implementation of EIP-1898 in RSKj JSON-RPC Methods

### PR DESCRIPTION
**Pull request by Vovchyk**
## Description

Implement EIP-1898 in RSKj JSON-RPC Methods.

The following methods were done to support EIP-1898:
- eth_getBalance
- eth_getStorageAt
- eth_getTransactionCount
- eth_getCode
- eth_call

Originated from https://github.com/rsksmart/rskj/pull/1515

## Motivation and Context

More details [here](https://github.com/rsksmart/rsk-gitcoin-hackathon-2021/issues/17).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

* **Other information**:

### Code Coverage

Attached  [coverage.zip](https://github.com/rsksmart/rskj/files/6398823/coverage.zip) you can find all the code coverage reports but you can see that the changes done are 100% covered, as the following image shows.
 
coverage
coverage-2
coverage-3

You can find it in coverage/ns-57/sources/source-c.html in the attached coverage reports.

### Demonstration

Here you can see a demonstration about some methods supporting EIP-1898.

requests

_rskj-node initialization_
rskj-node-init

Also you can find it in the attached [requests.txt](https://github.com/rsksmart/rskj/files/6398974/requests.txt)

### Improvements
In case of search by blockHash, 2 searches are done (one for blockHash and other by blockNumber), this could be avoided by adding blockHash search logic in Web3InformationRetriever.

### CODE REVIEW

**Review by heitorfm — DISMISSED** [review]

**Review by fedejinich — DISMISSED** [review]
lgtm!

**Comment by fedejinich** [comment]
rebased for sec review

**Comment by fedejinich** [comment]
can I squash the story ?

**Comment by joaquinlpereyra** [comment]
LGTM. A possible improvement is already mentioned on the PR:

```In case of search by blockHash, 2 searches are done (one for blockHash and other by blockNumber), this could be avoided by adding blockHash search logic in Web3InformationRetriever.```

But this does not pose any risk at all. The search will be slower but does not scale with input ;)

**Comment by fedejinich** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline: run

**Comment by Vovchyk** [comment]
pipeline: run

**Review by heitorfm — APPROVED** [review]

**Pull request merged**
