### PR TITLE
Move version to 1.2.0 snapshot

### PR DESCRIPTION
**Pull request by lsebrie**
*fed:version120* *fit:120*

### CODE REVIEW

**Comment by lsebrie** [comment]
Pipeline: run

**Comment by lsebrie** [comment]
fed: version120

**Comment by lsebrie** [comment]
Pipeline: run

**Comment by lsebrie** [comment]
Pipeline: run

**Comment by lsebrie** [comment]
Pipeline: run

**Comment by lsebrie** [comment]
Pipeline: run

**Comment by lsebrie** [comment]
Pipeline: run

**Comment by josedahlquist** [comment]
Pipeline: run

**Pull request merged**
