### PR TITLE
Max contract size (EIP-170)

### PR DESCRIPTION
**Pull request by tinchou**
This adds a max contract size check. We had to add some code to increase the gas limit in our tests because to trigger the contract size limit we need to spend around 5M gas.

* Commit 1: refactor, no functional changes
* Commit 2: add new code, only functional changes
* Commit 3: testing

Note: separating the implementation in two commits makes it very clear to see what the actual implementation is.

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 52 issues
* ![BLOCKER][BLOCKER] 1 blocker
* ![MAJOR][MAJOR] 38 major
* ![MINOR][MINOR] 4 minor
* ![INFO][INFO] 9 info

#### Top 10 issues

1. ![BLOCKER][BLOCKER] [TransactionExecutor.java#L361](https://github.com/rsksmart/rskj/blob/d8f9418b35513a0cf7b3ebcc79e8a12025a54a2c/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L361): Catch Exception instead of Throwable. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1181)
1. ![MAJOR][MAJOR] [Constants.java#L63](https://github.com/rsksmart/rskj/blob/d8f9418b35513a0cf7b3ebcc79e8a12025a54a2c/rskj-core/src/main/java/org/ethereum/config/Constants.java#L63): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L96](https://github.com/rsksmart/rskj/blob/d8f9418b35513a0cf7b3ebcc79e8a12025a54a2c/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L96): Constructor has 9 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L248](https://github.com/rsksmart/rskj/blob/d8f9418b35513a0cf7b3ebcc79e8a12025a54a2c/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L248): Take the required action to fix the issue indicated by this comment. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1134)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L301](https://github.com/rsksmart/rskj/blob/d8f9418b35513a0cf7b3ebcc79e8a12025a54a2c/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L301): The Cyclomatic Complexity of this method "go" is 11 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L361](https://github.com/rsksmart/rskj/blob/d8f9418b35513a0cf7b3ebcc79e8a12025a54a2c/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L361): Either log or rethrow this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L370](https://github.com/rsksmart/rskj/blob/d8f9418b35513a0cf7b3ebcc79e8a12025a54a2c/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L370): The Cyclomatic Complexity of this method "finalization" is 14 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L385](https://github.com/rsksmart/rskj/blob/d8f9418b35513a0cf7b3ebcc79e8a12025a54a2c/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L385): Nullcheck of TransactionExecutor.result at line 394 of value previously dereferenced in org.ethereum.core.TransactionExecutor.finalization() [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3ARCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE)
1. ![MAJOR][MAJOR] [Program.java#](https://github.com/rsksmart/rskj/blob/d8f9418b35513a0cf7b3ebcc79e8a12025a54a2c/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#): This file has 1,156 lines, which is greater than 1,000 authorized. Split it into smaller files. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Program.java#L174](https://github.com/rsksmart/rskj/blob/d8f9418b35513a0cf7b3ebcc79e8a12025a54a2c/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L174): Method org.ethereum.vm.program.Program.<static initializer for Program>() needlessly boxes a boolean constant [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ANAB_NEEDLESS_BOOLEAN_CONSTANT_CONVERSION)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 52 issues
* ![BLOCKER][BLOCKER] 1 blocker
* ![MAJOR][MAJOR] 38 major
* ![MINOR][MINOR] 4 minor
* ![INFO][INFO] 9 info

#### Top 10 issues

1. ![BLOCKER][BLOCKER] [TransactionExecutor.java#L361](https://github.com/rsksmart/rskj/blob/d35db4bfe3c54be76f5a6a2979b7be9d7f5bf397/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L361): Catch Exception instead of Throwable. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1181)
1. ![MAJOR][MAJOR] [Constants.java#L63](https://github.com/rsksmart/rskj/blob/d35db4bfe3c54be76f5a6a2979b7be9d7f5bf397/rskj-core/src/main/java/org/ethereum/config/Constants.java#L63): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L96](https://github.com/rsksmart/rskj/blob/d35db4bfe3c54be76f5a6a2979b7be9d7f5bf397/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L96): Constructor has 9 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L248](https://github.com/rsksmart/rskj/blob/d35db4bfe3c54be76f5a6a2979b7be9d7f5bf397/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L248): Take the required action to fix the issue indicated by this comment. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1134)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L301](https://github.com/rsksmart/rskj/blob/d35db4bfe3c54be76f5a6a2979b7be9d7f5bf397/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L301): The Cyclomatic Complexity of this method "go" is 11 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L361](https://github.com/rsksmart/rskj/blob/d35db4bfe3c54be76f5a6a2979b7be9d7f5bf397/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L361): Either log or rethrow this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L370](https://github.com/rsksmart/rskj/blob/d35db4bfe3c54be76f5a6a2979b7be9d7f5bf397/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L370): The Cyclomatic Complexity of this method "finalization" is 14 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L385](https://github.com/rsksmart/rskj/blob/d35db4bfe3c54be76f5a6a2979b7be9d7f5bf397/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L385): Nullcheck of TransactionExecutor.result at line 394 of value previously dereferenced in org.ethereum.core.TransactionExecutor.finalization() [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3ARCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE)
1. ![MAJOR][MAJOR] [Program.java#](https://github.com/rsksmart/rskj/blob/d35db4bfe3c54be76f5a6a2979b7be9d7f5bf397/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#): This file has 1,156 lines, which is greater than 1,000 authorized. Split it into smaller files. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Program.java#L174](https://github.com/rsksmart/rskj/blob/d35db4bfe3c54be76f5a6a2979b7be9d7f5bf397/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L174): Method org.ethereum.vm.program.Program.<static initializer for Program>() needlessly boxes a boolean constant [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ANAB_NEEDLESS_BOOLEAN_CONSTANT_CONVERSION)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by aeidelman** [comment]
@lsebrie Is any of these requested changes a blocker ?

**Comment by rskops** [comment]
SonarQube analysis reported 91 issues
* ![BLOCKER][BLOCKER] 1 blocker
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 38 major
* ![MINOR][MINOR] 42 minor
* ![INFO][INFO] 9 info

#### Top 10 issues

1. ![BLOCKER][BLOCKER] [TransactionExecutor.java#L361](https://github.com/rsksmart/rskj/blob/535cdae5b2281aa228520c9c4fce304b92bec1f9/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L361): Catch Exception instead of Throwable. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1181)
1. ![CRITICAL][CRITICAL] [Program.java#L1614](https://github.com/rsksmart/rskj/blob/535cdae5b2281aa228520c9c4fce304b92bec1f9/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L1614): Not enough arguments. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2275)
1. ![MAJOR][MAJOR] [Constants.java#L63](https://github.com/rsksmart/rskj/blob/535cdae5b2281aa228520c9c4fce304b92bec1f9/rskj-core/src/main/java/org/ethereum/config/Constants.java#L63): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L96](https://github.com/rsksmart/rskj/blob/535cdae5b2281aa228520c9c4fce304b92bec1f9/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L96): Constructor has 9 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L248](https://github.com/rsksmart/rskj/blob/535cdae5b2281aa228520c9c4fce304b92bec1f9/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L248): Take the required action to fix the issue indicated by this comment. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1134)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L301](https://github.com/rsksmart/rskj/blob/535cdae5b2281aa228520c9c4fce304b92bec1f9/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L301): The Cyclomatic Complexity of this method "go" is 11 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L361](https://github.com/rsksmart/rskj/blob/535cdae5b2281aa228520c9c4fce304b92bec1f9/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L361): Either log or rethrow this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L370](https://github.com/rsksmart/rskj/blob/535cdae5b2281aa228520c9c4fce304b92bec1f9/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L370): The Cyclomatic Complexity of this method "finalization" is 14 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L385](https://github.com/rsksmart/rskj/blob/535cdae5b2281aa228520c9c4fce304b92bec1f9/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L385): Nullcheck of TransactionExecutor.result at line 394 of value previously dereferenced in org.ethereum.core.TransactionExecutor.finalization() [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3ARCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE)
1. ![MAJOR][MAJOR] [Program.java#](https://github.com/rsksmart/rskj/blob/535cdae5b2281aa228520c9c4fce304b92bec1f9/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#): This file has 1,151 lines, which is greater than 1,000 authorized. Split it into smaller files. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00104)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 91 issues
* ![BLOCKER][BLOCKER] 1 blocker
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 38 major
* ![MINOR][MINOR] 42 minor
* ![INFO][INFO] 9 info

#### Top 10 issues

1. ![BLOCKER][BLOCKER] [TransactionExecutor.java#L361](https://github.com/rsksmart/rskj/blob/be21684c91188421208fbc469573fbfa8b228497/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L361): Catch Exception instead of Throwable. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1181)
1. ![CRITICAL][CRITICAL] [Program.java#L1614](https://github.com/rsksmart/rskj/blob/be21684c91188421208fbc469573fbfa8b228497/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#L1614): Not enough arguments. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2275)
1. ![MAJOR][MAJOR] [Constants.java#L63](https://github.com/rsksmart/rskj/blob/be21684c91188421208fbc469573fbfa8b228497/rskj-core/src/main/java/org/ethereum/config/Constants.java#L63): Remove this method and declare a constant for this value. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS3400)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L96](https://github.com/rsksmart/rskj/blob/be21684c91188421208fbc469573fbfa8b228497/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L96): Constructor has 9 parameters, which is greater than 7 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00107)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L248](https://github.com/rsksmart/rskj/blob/be21684c91188421208fbc469573fbfa8b228497/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L248): Take the required action to fix the issue indicated by this comment. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1134)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L301](https://github.com/rsksmart/rskj/blob/be21684c91188421208fbc469573fbfa8b228497/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L301): The Cyclomatic Complexity of this method "go" is 11 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L361](https://github.com/rsksmart/rskj/blob/be21684c91188421208fbc469573fbfa8b228497/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L361): Either log or rethrow this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L370](https://github.com/rsksmart/rskj/blob/be21684c91188421208fbc469573fbfa8b228497/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L370): The Cyclomatic Complexity of this method "finalization" is 14 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [TransactionExecutor.java#L385](https://github.com/rsksmart/rskj/blob/be21684c91188421208fbc469573fbfa8b228497/rskj-core/src/main/java/org/ethereum/core/TransactionExecutor.java#L385): Nullcheck of TransactionExecutor.result at line 394 of value previously dereferenced in org.ethereum.core.TransactionExecutor.finalization() [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3ARCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE)
1. ![MAJOR][MAJOR] [Program.java#](https://github.com/rsksmart/rskj/blob/be21684c91188421208fbc469573fbfa8b228497/rskj-core/src/main/java/org/ethereum/vm/program/Program.java#): This file has 1,151 lines, which is greater than 1,000 authorized. Split it into smaller files. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00104)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
