### PR TITLE
co.rsk.net.Metrics and its usage removed

### PR DESCRIPTION
**Pull request by raullaprida**
co.rsk.net.Metrics and its usage removed since no usage of the generated output has been found.
I encourage the reviewers to confirm there's no other project importing rskj and consuming this Metric class outputs.

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 5 issues

1. ![MAJOR][MAJOR] [NodeMessageHandler.java#L427](https://github.com/rsksmart/rskj/blob/9e01e216d94069e14c43778fc435c2948942fd94/rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java#L427): Remove this unused "acceptedTxs" local variable. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1481)
1. ![MAJOR][MAJOR] [NodeMessageHandler.java#L427](https://github.com/rsksmart/rskj/blob/9e01e216d94069e14c43778fc435c2948942fd94/rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java#L427): Remove this useless assignment to local variable "acceptedTxs". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1854)
1. ![MINOR][MINOR] [NodeMessageHandler.java#L328](https://github.com/rsksmart/rskj/blob/9e01e216d94069e14c43778fc435c2948942fd94/rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java#L328): Remove this unused method parameter "sender". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1172)
1. ![INFO][INFO] [NodeMessageHandler.java#L329](https://github.com/rsksmart/rskj/blob/9e01e216d94069e14c43778fc435c2948942fd94/rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java#L329): Static or private method co.rsk.net.NodeMessageHandler.relayBlock(MessageChannel, Block) has unused parameters [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3AUP_UNUSED_PARAMETER)
1. ![INFO][INFO] [NodeMessageHandler.java#L427](https://github.com/rsksmart/rskj/blob/9e01e216d94069e14c43778fc435c2948942fd94/rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java#L427): Dead store to acceptedTxs in co.rsk.net.NodeMessageHandler.processTransactionsMessage(MessageChannel, TransactionsMessage) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3ADLS_DEAD_LOCAL_STORE)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by tinchou** [comment]
Please remove the unused `acceptedTxs` variable, which is now unnecessary (see the Sonar report above).
I would also appreciate if you could remove some of the empty lines at the beginning of the methods you changed!

**Comment by rskops** [comment]
SonarQube analysis reported 5 issues

1. ![CRITICAL][CRITICAL] [NodeMessageHandler.java#L60](https://github.com/rsksmart/rskj/blob/280466ed1e53233b4c14f3b931a29cd39b2136c1/rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java#L60): Remove this unused "transactionGateway" private field. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1068)
1. ![MAJOR][MAJOR] [NodeMessageHandler.java#L415](https://github.com/rsksmart/rskj/blob/280466ed1e53233b4c14f3b931a29cd39b2136c1/rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java#L415): Method co.rsk.net.NodeMessageHandler.processTransactionsMessage(MessageChannel, TransactionsMessage) creates and initializes a collection but never reads or gains information from it [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3AWOC_WRITE_ONLY_COLLECTION_LOCAL)
1. ![MINOR][MINOR] [NodeMessageHandler.java#L328](https://github.com/rsksmart/rskj/blob/280466ed1e53233b4c14f3b931a29cd39b2136c1/rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java#L328): Remove this unused method parameter "sender". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1172)
1. ![INFO][INFO] [NodeMessageHandler.java#L329](https://github.com/rsksmart/rskj/blob/280466ed1e53233b4c14f3b931a29cd39b2136c1/rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java#L329): Static or private method co.rsk.net.NodeMessageHandler.relayBlock(MessageChannel, Block) has unused parameters [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3AUP_UNUSED_PARAMETER)
1. ![INFO][INFO] [NodeMessageHandler.java#L415](https://github.com/rsksmart/rskj/blob/280466ed1e53233b4c14f3b931a29cd39b2136c1/rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java#L415): Useless object stored in variable txs of method co.rsk.net.NodeMessageHandler.processTransactionsMessage(MessageChannel, TransactionsMessage) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3AUC_USELESS_OBJECT)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 5 issues

1. ![MAJOR][MAJOR] [NodeMessageHandler.java#L427](https://github.com/rsksmart/rskj/blob/9e01e216d94069e14c43778fc435c2948942fd94/rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java#L427): Remove this unused "acceptedTxs" local variable. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1481)
1. ![MAJOR][MAJOR] [NodeMessageHandler.java#L427](https://github.com/rsksmart/rskj/blob/9e01e216d94069e14c43778fc435c2948942fd94/rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java#L427): Remove this useless assignment to local variable "acceptedTxs". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1854)
1. ![MINOR][MINOR] [NodeMessageHandler.java#L328](https://github.com/rsksmart/rskj/blob/9e01e216d94069e14c43778fc435c2948942fd94/rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java#L328): Remove this unused method parameter "sender". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1172)
1. ![INFO][INFO] [NodeMessageHandler.java#L329](https://github.com/rsksmart/rskj/blob/9e01e216d94069e14c43778fc435c2948942fd94/rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java#L329): Static or private method co.rsk.net.NodeMessageHandler.relayBlock(MessageChannel, Block) has unused parameters [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3AUP_UNUSED_PARAMETER)
1. ![INFO][INFO] [NodeMessageHandler.java#L427](https://github.com/rsksmart/rskj/blob/9e01e216d94069e14c43778fc435c2948942fd94/rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java#L427): Dead store to acceptedTxs in co.rsk.net.NodeMessageHandler.processTransactionsMessage(MessageChannel, TransactionsMessage) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3ADLS_DEAD_LOCAL_STORE)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 2 issues

1. ![MINOR][MINOR] [NodeMessageHandler.java#L328](https://github.com/rsksmart/rskj/blob/b378b3da428987a30c71d827761f50187bbc425e/rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java#L328): Remove this unused method parameter "sender". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1172)
1. ![INFO][INFO] [NodeMessageHandler.java#L329](https://github.com/rsksmart/rskj/blob/b378b3da428987a30c71d827761f50187bbc425e/rskj-core/src/main/java/co/rsk/net/NodeMessageHandler.java#L329): Static or private method co.rsk.net.NodeMessageHandler.relayBlock(MessageChannel, Block) has unused parameters [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3AUP_UNUSED_PARAMETER)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
