### PR TITLE
Mitigated db inconsistency issue after improper node shutdown

### PR DESCRIPTION
**Pull request by Vovchyk**
## Description

This tries to mitigate an issue of data inconsistency after improper node shut down.

This also adds a new capability to the `RewindBlocks` cli tool, which allows to find minimum inconsistent block number as well as to "rewind" inconsistent blocks(`fmi` and `rbc` cli flags respectively).

## Motivation and Context

Recommended ways to stop the node is to use `Ctrl+C` or via the `kill -TERM <PID>` command.

Sometimes (rather rarely), if the node is not properly shut down, for instance, when it's killed via `kill -KILL <PID>`, stopping an IDE debugger or after machine powering off, the database goes into the inconsistent state - very often when a best block's state root hash points to a missing record in the states db.

This PR adds a few tricks to mitigate the issue, for instance, blocks are flushed after the trie states.

This change also adds a capability to find a minimum inconsistent block number, e.g. via the following command:
```bash
java -cp ./rskj-core/build/libs/rskj-core-3.2.0-SNAPSHOT-all.jar co.rsk.cli.tools.RewindBlocks fmi --testnet
```

which would print a number of first inconsistent block (or `-1` if not found). Or rewind inconsistent blocks, if any, like this:
```bash
java -cp ./rskj-core/build/libs/rskj-core-3.2.0-SNAPSHOT-all.jar co.rsk.cli.tools.RewindBlocks rbc --testnet
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

### CODE REVIEW

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Review by rmoreliovlabs — DISMISSED** [review]

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Review by heitorfm — APPROVED** [review]

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Pull request merged**
