### PR TITLE
Fix TransactionResultDTO Remasc sender serialization

### PR DESCRIPTION
**Pull request by tinchou**
@sirhill reported this issue in [Gitter](https://gitter.im/rsksmart/rskj?at=5a9d5f3df3f6d24c683c7dcf). It can be reproduced running the following code on `web3.js:1.0-beta30`:

```js
var Web3 = require('web3');
var web3 = new Web3('http://localhost:4444');
web3.eth.getTransaction('0x1b32ef862ace0ab9759775427dbb348dcb28b29152e8866eef56014d38b8d524')
    .then(console.log);
```

This is caused because `web3.js` is performing a strict validation on the sender address (`from` field): https://github.com/ethereum/web3.js/blob/a4d592e8d6d89e531ace066018bfc004ef501f0c/packages/web3-utils/src/index.js#L247

This fixes the `Remasc` sender address serialization to be a valid address.

### CODE REVIEW

**Comment by tinchou** [comment]
@herrerameri this should be ready for you to try out and give me your heads up!

**Comment by rskops** [comment]
SonarQube analysis reported 23 issues
* ![MAJOR][MAJOR] 11 major
* ![INFO][INFO] 12 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [TransactionResultDTO.java#L36](https://github.com/rsksmart/rskj/blob/4b4850c0a94eeac0f2a82bb1e8797a9f067f66a1/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L36): Make hash a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![MAJOR][MAJOR] [TransactionResultDTO.java#L37](https://github.com/rsksmart/rskj/blob/4b4850c0a94eeac0f2a82bb1e8797a9f067f66a1/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L37): Make nonce a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![MAJOR][MAJOR] [TransactionResultDTO.java#L38](https://github.com/rsksmart/rskj/blob/4b4850c0a94eeac0f2a82bb1e8797a9f067f66a1/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L38): Make blockHash a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![MAJOR][MAJOR] [TransactionResultDTO.java#L39](https://github.com/rsksmart/rskj/blob/4b4850c0a94eeac0f2a82bb1e8797a9f067f66a1/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L39): Make blockNumber a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![MAJOR][MAJOR] [TransactionResultDTO.java#L40](https://github.com/rsksmart/rskj/blob/4b4850c0a94eeac0f2a82bb1e8797a9f067f66a1/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L40): Make transactionIndex a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![MAJOR][MAJOR] [TransactionResultDTO.java#L42](https://github.com/rsksmart/rskj/blob/4b4850c0a94eeac0f2a82bb1e8797a9f067f66a1/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L42): Make from a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![MAJOR][MAJOR] [TransactionResultDTO.java#L43](https://github.com/rsksmart/rskj/blob/4b4850c0a94eeac0f2a82bb1e8797a9f067f66a1/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L43): Make to a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![MAJOR][MAJOR] [TransactionResultDTO.java#L44](https://github.com/rsksmart/rskj/blob/4b4850c0a94eeac0f2a82bb1e8797a9f067f66a1/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L44): Make gas a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![MAJOR][MAJOR] [TransactionResultDTO.java#L45](https://github.com/rsksmart/rskj/blob/4b4850c0a94eeac0f2a82bb1e8797a9f067f66a1/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L45): Make gasPrice a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![MAJOR][MAJOR] [TransactionResultDTO.java#L46](https://github.com/rsksmart/rskj/blob/4b4850c0a94eeac0f2a82bb1e8797a9f067f66a1/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L46): Make value a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by herrerameri** [comment]
I've tested `web3.eth.getTransaction` and `web3.eth.getTransactionFromBlock`.
@tinchou you have my approval and gratitude :smile:

**Comment by rskops** [comment]
SonarQube analysis reported 23 issues
* ![MAJOR][MAJOR] 11 major
* ![INFO][INFO] 12 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [TransactionResultDTO.java#L36](https://github.com/rsksmart/rskj/blob/641b90da3f972de0ac80f36686d17c35e0878c68/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L36): Make hash a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![MAJOR][MAJOR] [TransactionResultDTO.java#L37](https://github.com/rsksmart/rskj/blob/641b90da3f972de0ac80f36686d17c35e0878c68/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L37): Make nonce a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![MAJOR][MAJOR] [TransactionResultDTO.java#L38](https://github.com/rsksmart/rskj/blob/641b90da3f972de0ac80f36686d17c35e0878c68/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L38): Make blockHash a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![MAJOR][MAJOR] [TransactionResultDTO.java#L39](https://github.com/rsksmart/rskj/blob/641b90da3f972de0ac80f36686d17c35e0878c68/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L39): Make blockNumber a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![MAJOR][MAJOR] [TransactionResultDTO.java#L40](https://github.com/rsksmart/rskj/blob/641b90da3f972de0ac80f36686d17c35e0878c68/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L40): Make transactionIndex a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![MAJOR][MAJOR] [TransactionResultDTO.java#L42](https://github.com/rsksmart/rskj/blob/641b90da3f972de0ac80f36686d17c35e0878c68/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L42): Make from a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![MAJOR][MAJOR] [TransactionResultDTO.java#L43](https://github.com/rsksmart/rskj/blob/641b90da3f972de0ac80f36686d17c35e0878c68/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L43): Make to a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![MAJOR][MAJOR] [TransactionResultDTO.java#L44](https://github.com/rsksmart/rskj/blob/641b90da3f972de0ac80f36686d17c35e0878c68/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L44): Make gas a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![MAJOR][MAJOR] [TransactionResultDTO.java#L45](https://github.com/rsksmart/rskj/blob/641b90da3f972de0ac80f36686d17c35e0878c68/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L45): Make gasPrice a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![MAJOR][MAJOR] [TransactionResultDTO.java#L46](https://github.com/rsksmart/rskj/blob/641b90da3f972de0ac80f36686d17c35e0878c68/rskj-core/src/main/java/org/ethereum/rpc/dto/TransactionResultDTO.java#L46): Make value a static final constant or non-public and provide accessors if needed. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Pull request merged**
