### PR TITLE
Block replay

### PR DESCRIPTION
**Pull request by SergioDemianLerner**
This PR adds the capability to replay the blocks from a database into another (empty) database.

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 21 issues
* ![CRITICAL][CRITICAL] 10 critical
* ![MAJOR][MAJOR] 9 major
* ![INFO][INFO] 2 info

#### Top 10 issues

1. ![CRITICAL][CRITICAL] [FullNodeRunner.java#L339](https://github.com/rsksmart/rskj/blob/435a9c0a54b127b59ee4320db722005781326a97/rskj-core/src/main/java/co/rsk/FullNodeRunner.java#L339): Missing curly brace. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00121)
1. ![CRITICAL][CRITICAL] [BlockstoreBlockPlayer.java#L25](https://github.com/rsksmart/rskj/blob/435a9c0a54b127b59ee4320db722005781326a97/rskj-core/src/main/java/co/rsk/blocks/BlockstoreBlockPlayer.java#L25): Explicitly declare the visibility for "blockStore". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2039)
1. ![CRITICAL][CRITICAL] [BlockstoreBlockPlayer.java#L26](https://github.com/rsksmart/rskj/blob/435a9c0a54b127b59ee4320db722005781326a97/rskj-core/src/main/java/co/rsk/blocks/BlockstoreBlockPlayer.java#L26): Explicitly declare the visibility for "databaseDir". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2039)
1. ![CRITICAL][CRITICAL] [BlockstoreBlockPlayer.java#L27](https://github.com/rsksmart/rskj/blob/435a9c0a54b127b59ee4320db722005781326a97/rskj-core/src/main/java/co/rsk/blocks/BlockstoreBlockPlayer.java#L27): Explicitly declare the visibility for "blockNumber". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2039)
1. ![CRITICAL][CRITICAL] [BlockstoreBlockPlayer.java#L28](https://github.com/rsksmart/rskj/blob/435a9c0a54b127b59ee4320db722005781326a97/rskj-core/src/main/java/co/rsk/blocks/BlockstoreBlockPlayer.java#L28): Explicitly declare the visibility for "indexDB". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2039)
1. ![CRITICAL][CRITICAL] [BlockstoreBlockPlayer.java#L29](https://github.com/rsksmart/rskj/blob/435a9c0a54b127b59ee4320db722005781326a97/rskj-core/src/main/java/co/rsk/blocks/BlockstoreBlockPlayer.java#L29): Explicitly declare the visibility for "blocksDB". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2039)
1. ![CRITICAL][CRITICAL] [BlockstoreBlockPlayer.java#L35](https://github.com/rsksmart/rskj/blob/435a9c0a54b127b59ee4320db722005781326a97/rskj-core/src/main/java/co/rsk/blocks/BlockstoreBlockPlayer.java#L35): Remove this call from a constructor to the overridable "createBlockstore" method. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1699)
1. ![CRITICAL][CRITICAL] [BlockstoreBlockPlayer.java#L70](https://github.com/rsksmart/rskj/blob/435a9c0a54b127b59ee4320db722005781326a97/rskj-core/src/main/java/co/rsk/blocks/BlockstoreBlockPlayer.java#L70): Missing curly brace. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00121)
1. ![CRITICAL][CRITICAL] [BlockstoreBlockPlayer.java#L79](https://github.com/rsksmart/rskj/blob/435a9c0a54b127b59ee4320db722005781326a97/rskj-core/src/main/java/co/rsk/blocks/BlockstoreBlockPlayer.java#L79): Missing curly brace. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00121)
1. ![CRITICAL][CRITICAL] [BlockstoreBlockPlayer.java#L81](https://github.com/rsksmart/rskj/blob/435a9c0a54b127b59ee4320db722005781326a97/rskj-core/src/main/java/co/rsk/blocks/BlockstoreBlockPlayer.java#L81): Missing curly brace. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00121)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by rskops** [comment]
SonarQube analysis reported 21 issues
* ![CRITICAL][CRITICAL] 10 critical
* ![MAJOR][MAJOR] 9 major
* ![INFO][INFO] 2 info

#### Top 10 issues

1. ![CRITICAL][CRITICAL] [FullNodeRunner.java#L339](https://github.com/rsksmart/rskj/blob/6487cc07599f1c42b258c3a70428f94f4c4bfd38/rskj-core/src/main/java/co/rsk/FullNodeRunner.java#L339): Missing curly brace. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00121)
1. ![CRITICAL][CRITICAL] [BlockstoreBlockPlayer.java#L25](https://github.com/rsksmart/rskj/blob/6487cc07599f1c42b258c3a70428f94f4c4bfd38/rskj-core/src/main/java/co/rsk/blocks/BlockstoreBlockPlayer.java#L25): Explicitly declare the visibility for "blockStore". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2039)
1. ![CRITICAL][CRITICAL] [BlockstoreBlockPlayer.java#L26](https://github.com/rsksmart/rskj/blob/6487cc07599f1c42b258c3a70428f94f4c4bfd38/rskj-core/src/main/java/co/rsk/blocks/BlockstoreBlockPlayer.java#L26): Explicitly declare the visibility for "databaseDir". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2039)
1. ![CRITICAL][CRITICAL] [BlockstoreBlockPlayer.java#L27](https://github.com/rsksmart/rskj/blob/6487cc07599f1c42b258c3a70428f94f4c4bfd38/rskj-core/src/main/java/co/rsk/blocks/BlockstoreBlockPlayer.java#L27): Explicitly declare the visibility for "blockNumber". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2039)
1. ![CRITICAL][CRITICAL] [BlockstoreBlockPlayer.java#L28](https://github.com/rsksmart/rskj/blob/6487cc07599f1c42b258c3a70428f94f4c4bfd38/rskj-core/src/main/java/co/rsk/blocks/BlockstoreBlockPlayer.java#L28): Explicitly declare the visibility for "indexDB". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2039)
1. ![CRITICAL][CRITICAL] [BlockstoreBlockPlayer.java#L29](https://github.com/rsksmart/rskj/blob/6487cc07599f1c42b258c3a70428f94f4c4bfd38/rskj-core/src/main/java/co/rsk/blocks/BlockstoreBlockPlayer.java#L29): Explicitly declare the visibility for "blocksDB". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2039)
1. ![CRITICAL][CRITICAL] [BlockstoreBlockPlayer.java#L35](https://github.com/rsksmart/rskj/blob/6487cc07599f1c42b258c3a70428f94f4c4bfd38/rskj-core/src/main/java/co/rsk/blocks/BlockstoreBlockPlayer.java#L35): Remove this call from a constructor to the overridable "createBlockstore" method. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1699)
1. ![CRITICAL][CRITICAL] [BlockstoreBlockPlayer.java#L70](https://github.com/rsksmart/rskj/blob/6487cc07599f1c42b258c3a70428f94f4c4bfd38/rskj-core/src/main/java/co/rsk/blocks/BlockstoreBlockPlayer.java#L70): Missing curly brace. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00121)
1. ![CRITICAL][CRITICAL] [BlockstoreBlockPlayer.java#L79](https://github.com/rsksmart/rskj/blob/6487cc07599f1c42b258c3a70428f94f4c4bfd38/rskj-core/src/main/java/co/rsk/blocks/BlockstoreBlockPlayer.java#L79): Missing curly brace. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00121)
1. ![CRITICAL][CRITICAL] [BlockstoreBlockPlayer.java#L81](https://github.com/rsksmart/rskj/blob/6487cc07599f1c42b258c3a70428f94f4c4bfd38/rskj-core/src/main/java/co/rsk/blocks/BlockstoreBlockPlayer.java#L81): Missing curly brace. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00121)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by rskops** [comment]
SonarQube analysis reported 9 issues

1. ![CRITICAL][CRITICAL] [FileBlockPlayer.java#L21](https://github.com/rsksmart/rskj/blob/63207d89cfeeb64c41222d34389fbd41759d0f4a/rskj-core/src/main/java/co/rsk/blocks/FileBlockPlayer.java#L21): Unused import - co.rsk.config.RskSystemProperties. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck)
1. ![MAJOR][MAJOR] [FullNodeRunner.java#L348](https://github.com/rsksmart/rskj/blob/63207d89cfeeb64c41222d34389fbd41759d0f4a/rskj-core/src/main/java/co/rsk/FullNodeRunner.java#L348): Move the "file" string literal on the left side of this string comparison. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1132)
1. ![MAJOR][MAJOR] [FullNodeRunner.java#L348](https://github.com/rsksmart/rskj/blob/63207d89cfeeb64c41222d34389fbd41759d0f4a/rskj-core/src/main/java/co/rsk/FullNodeRunner.java#L348): Replace these toUpperCase()/toLowerCase() and equals() calls with a single equalsIgnoreCase() call. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1157)
1. ![MAJOR][MAJOR] [FullNodeRunner.java#L350](https://github.com/rsksmart/rskj/blob/63207d89cfeeb64c41222d34389fbd41759d0f4a/rskj-core/src/main/java/co/rsk/FullNodeRunner.java#L350): Move the "blockstore" string literal on the left side of this string comparison. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1132)
1. ![MAJOR][MAJOR] [FullNodeRunner.java#L350](https://github.com/rsksmart/rskj/blob/63207d89cfeeb64c41222d34389fbd41759d0f4a/rskj-core/src/main/java/co/rsk/FullNodeRunner.java#L350): Replace these toUpperCase()/toLowerCase() and equals() calls with a single equalsIgnoreCase() call. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1157)
1. ![MAJOR][MAJOR] [BlockstoreBlockPlayer.java#L35](https://github.com/rsksmart/rskj/blob/63207d89cfeeb64c41222d34389fbd41759d0f4a/rskj-core/src/main/java/co/rsk/blocks/BlockstoreBlockPlayer.java#L35): Method new co.rsk.blocks.BlockstoreBlockPlayer(String, long) passes an incorrect number of parameters to an SLF4J logging statement [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_INCORRECT_NUMBER_OF_ANCHOR_PARAMETERS)
1. ![MAJOR][MAJOR] [CommonConfig.java#L64](https://github.com/rsksmart/rskj/blob/63207d89cfeeb64c41222d34389fbd41759d0f4a/rskj-core/src/main/java/org/ethereum/config/CommonConfig.java#L64): Either log or rethrow this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1166)
1. ![INFO][INFO] [FullNodeRunner.java#L348](https://github.com/rsksmart/rskj/blob/63207d89cfeeb64c41222d34389fbd41759d0f4a/rskj-core/src/main/java/co/rsk/FullNodeRunner.java#L348): Method co.rsk.FullNodeRunner.createBlockPlayer(String, String) makes literal string comparisons passing the literal as an argument [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALSC_LITERAL_STRING_COMPARISON)
1. ![INFO][INFO] [FullNodeRunner.java#L350](https://github.com/rsksmart/rskj/blob/63207d89cfeeb64c41222d34389fbd41759d0f4a/rskj-core/src/main/java/co/rsk/FullNodeRunner.java#L350): Method co.rsk.FullNodeRunner.createBlockPlayer(String, String) makes literal string comparisons passing the literal as an argument [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALSC_LITERAL_STRING_COMPARISON)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by rskops** [comment]
SonarQube analysis reported 32 issues
* ![BLOCKER][BLOCKER] 1 blocker
* ![CRITICAL][CRITICAL] 2 critical
* ![MAJOR][MAJOR] 25 major
* ![INFO][INFO] 4 info

#### Top 10 issues

1. ![BLOCKER][BLOCKER] [BlocksFilePlayer.java#L71](https://github.com/rsksmart/rskj/blob/3e460d4185ec457b6a1fe9cec91f09588ac30ef6/rskj-core/src/main/java/co/rsk/BlocksFilePlayer.java#L71): Use or store the value returned from "readLine" instead of throwing it away. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2677)
1. ![CRITICAL][CRITICAL] [BlocksFileExporter.java#L52](https://github.com/rsksmart/rskj/blob/3e460d4185ec457b6a1fe9cec91f09588ac30ef6/rskj-core/src/main/java/co/rsk/BlocksFileExporter.java#L52): Use a logger to log this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1148)
1. ![CRITICAL][CRITICAL] [BlocksFilePlayer.java#L59](https://github.com/rsksmart/rskj/blob/3e460d4185ec457b6a1fe9cec91f09588ac30ef6/rskj-core/src/main/java/co/rsk/BlocksFilePlayer.java#L59): Use a logger to log this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1148)
1. ![MAJOR][MAJOR] [BlocksFileExporter.java#L43](https://github.com/rsksmart/rskj/blob/3e460d4185ec457b6a1fe9cec91f09588ac30ef6/rskj-core/src/main/java/co/rsk/BlocksFileExporter.java#L43): java/io/FileWriter.<init>(Ljava/lang/String;)V writes to a file whose location might be specified by user input [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3APATH_TRAVERSAL_OUT)
1. ![MAJOR][MAJOR] [BlocksFileExporter.java#L51](https://github.com/rsksmart/rskj/blob/3e460d4185ec457b6a1fe9cec91f09588ac30ef6/rskj-core/src/main/java/co/rsk/BlocksFileExporter.java#L51): Either log or rethrow this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [BlocksFileExporter.java#L62](https://github.com/rsksmart/rskj/blob/3e460d4185ec457b6a1fe9cec91f09588ac30ef6/rskj-core/src/main/java/co/rsk/BlocksFileExporter.java#L62): Replace this use of System.out or System.err by a logger. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS106)
1. ![MAJOR][MAJOR] [BlocksFilePlayer.java#L42](https://github.com/rsksmart/rskj/blob/3e460d4185ec457b6a1fe9cec91f09588ac30ef6/rskj-core/src/main/java/co/rsk/BlocksFilePlayer.java#L42): java/io/FileReader.<init>(Ljava/lang/String;)V reads a file whose location might be specified by user input [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3APATH_TRAVERSAL_IN)
1. ![MAJOR][MAJOR] [BlocksFilePlayer.java#L47](https://github.com/rsksmart/rskj/blob/3e460d4185ec457b6a1fe9cec91f09588ac30ef6/rskj-core/src/main/java/co/rsk/BlocksFilePlayer.java#L47): Replace this use of System.out or System.err by a logger. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS106)
1. ![MAJOR][MAJOR] [BlocksFilePlayer.java#L47](https://github.com/rsksmart/rskj/blob/3e460d4185ec457b6a1fe9cec91f09588ac30ef6/rskj-core/src/main/java/co/rsk/BlocksFilePlayer.java#L47): Format string should use %n rather than \n in co.rsk.BlocksFilePlayer.connectBlocks() [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3AVA_FORMAT_STRING_USES_NEWLINE)
1. ![MAJOR][MAJOR] [BlocksFilePlayer.java#L48](https://github.com/rsksmart/rskj/blob/3e460d4185ec457b6a1fe9cec91f09588ac30ef6/rskj-core/src/main/java/co/rsk/BlocksFilePlayer.java#L48): Remove this call to "exit" or ensure it is really required. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1147)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by tinchou** [comment]
Three entrypoints have been added, which can be easily called from the command line or through the IDE:
* `co.rsk.BlockstoreBlockPlayer#main`
* `co.rsk.BlocksFilePlayer#main`
* `co.rsk.BlocksFileExporter#main`

A new CLI parameter was added to enhance the UX when using these features:
* `-base-path [path]`: Specify the base data storage path (`database.dir` config setting)

To make this happen we decoupled from Spring by creating a `RskContext` class. This was easily done thanks to the previous hard work in removing circular dependencies.

Old features were removed:
* in-process block recording
* in-process block replaying

**Comment by rskops** [comment]
SonarQube analysis reported 37 issues
* ![BLOCKER][BLOCKER] 1 blocker
* ![CRITICAL][CRITICAL] 2 critical
* ![MAJOR][MAJOR] 30 major
* ![INFO][INFO] 4 info

#### Top 10 issues

1. ![BLOCKER][BLOCKER] [BlocksFilePlayer.java#L71](https://github.com/rsksmart/rskj/blob/228f6d2f9b156ce628aed98e9c00d8cde0574394/rskj-core/src/main/java/co/rsk/BlocksFilePlayer.java#L71): Use or store the value returned from "readLine" instead of throwing it away. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2677)
1. ![CRITICAL][CRITICAL] [BlocksFileExporter.java#L52](https://github.com/rsksmart/rskj/blob/228f6d2f9b156ce628aed98e9c00d8cde0574394/rskj-core/src/main/java/co/rsk/BlocksFileExporter.java#L52): Use a logger to log this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1148)
1. ![CRITICAL][CRITICAL] [BlocksFilePlayer.java#L59](https://github.com/rsksmart/rskj/blob/228f6d2f9b156ce628aed98e9c00d8cde0574394/rskj-core/src/main/java/co/rsk/BlocksFilePlayer.java#L59): Use a logger to log this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1148)
1. ![MAJOR][MAJOR] [BlocksFileExporter.java#L43](https://github.com/rsksmart/rskj/blob/228f6d2f9b156ce628aed98e9c00d8cde0574394/rskj-core/src/main/java/co/rsk/BlocksFileExporter.java#L43): java/io/FileWriter.<init>(Ljava/lang/String;)V writes to a file whose location might be specified by user input [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3APATH_TRAVERSAL_OUT)
1. ![MAJOR][MAJOR] [BlocksFileExporter.java#L51](https://github.com/rsksmart/rskj/blob/228f6d2f9b156ce628aed98e9c00d8cde0574394/rskj-core/src/main/java/co/rsk/BlocksFileExporter.java#L51): Either log or rethrow this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [BlocksFileExporter.java#L62](https://github.com/rsksmart/rskj/blob/228f6d2f9b156ce628aed98e9c00d8cde0574394/rskj-core/src/main/java/co/rsk/BlocksFileExporter.java#L62): Replace this use of System.out or System.err by a logger. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS106)
1. ![MAJOR][MAJOR] [BlocksFilePlayer.java#L42](https://github.com/rsksmart/rskj/blob/228f6d2f9b156ce628aed98e9c00d8cde0574394/rskj-core/src/main/java/co/rsk/BlocksFilePlayer.java#L42): java/io/FileReader.<init>(Ljava/lang/String;)V reads a file whose location might be specified by user input [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3APATH_TRAVERSAL_IN)
1. ![MAJOR][MAJOR] [BlocksFilePlayer.java#L47](https://github.com/rsksmart/rskj/blob/228f6d2f9b156ce628aed98e9c00d8cde0574394/rskj-core/src/main/java/co/rsk/BlocksFilePlayer.java#L47): Replace this use of System.out or System.err by a logger. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS106)
1. ![MAJOR][MAJOR] [BlocksFilePlayer.java#L47](https://github.com/rsksmart/rskj/blob/228f6d2f9b156ce628aed98e9c00d8cde0574394/rskj-core/src/main/java/co/rsk/BlocksFilePlayer.java#L47): Format string should use %n rather than \n in co.rsk.BlocksFilePlayer.connectBlocks() [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3AVA_FORMAT_STRING_USES_NEWLINE)
1. ![MAJOR][MAJOR] [BlocksFilePlayer.java#L48](https://github.com/rsksmart/rskj/blob/228f6d2f9b156ce628aed98e9c00d8cde0574394/rskj-core/src/main/java/co/rsk/BlocksFilePlayer.java#L48): Remove this call to "exit" or ensure it is really required. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1147)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by rskops** [comment]
SonarQube analysis reported 27 issues
* ![MAJOR][MAJOR] 26 major
* ![INFO][INFO] 1 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [BlocksFileExporter.java#L43](https://github.com/rsksmart/rskj/blob/608ce37ececc6cae49fb09cef56bbefdeb570e51/rskj-core/src/main/java/co/rsk/BlocksFileExporter.java#L43): java/io/FileWriter.<init>(Ljava/lang/String;)V writes to a file whose location might be specified by user input [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3APATH_TRAVERSAL_OUT)
1. ![MAJOR][MAJOR] [BlocksFileExporter.java#L52](https://github.com/rsksmart/rskj/blob/608ce37ececc6cae49fb09cef56bbefdeb570e51/rskj-core/src/main/java/co/rsk/BlocksFileExporter.java#L52): Replace this use of System.out or System.err by a logger. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS106)
1. ![MAJOR][MAJOR] [BlocksFileExporter.java#L62](https://github.com/rsksmart/rskj/blob/608ce37ececc6cae49fb09cef56bbefdeb570e51/rskj-core/src/main/java/co/rsk/BlocksFileExporter.java#L62): Replace this use of System.out or System.err by a logger. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS106)
1. ![MAJOR][MAJOR] [BlocksFilePlayer.java#L43](https://github.com/rsksmart/rskj/blob/608ce37ececc6cae49fb09cef56bbefdeb570e51/rskj-core/src/main/java/co/rsk/BlocksFilePlayer.java#L43): java/nio/file/Paths.get(Ljava/lang/String;[Ljava/lang/String;)Ljava/nio/file/Path; reads a file whose location might be specified by user input [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3APATH_TRAVERSAL_IN)
1. ![MAJOR][MAJOR] [BlocksFilePlayer.java#L47](https://github.com/rsksmart/rskj/blob/608ce37ececc6cae49fb09cef56bbefdeb570e51/rskj-core/src/main/java/co/rsk/BlocksFilePlayer.java#L47): Replace this use of System.out or System.err by a logger. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS106)
1. ![MAJOR][MAJOR] [BlocksFilePlayer.java#L59](https://github.com/rsksmart/rskj/blob/608ce37ececc6cae49fb09cef56bbefdeb570e51/rskj-core/src/main/java/co/rsk/BlocksFilePlayer.java#L59): Replace this use of System.out or System.err by a logger. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS106)
1. ![MAJOR][MAJOR] [BlocksFilePlayer.java#L60](https://github.com/rsksmart/rskj/blob/608ce37ececc6cae49fb09cef56bbefdeb570e51/rskj-core/src/main/java/co/rsk/BlocksFilePlayer.java#L60): Remove this call to "exit" or ensure it is really required. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1147)
1. ![MAJOR][MAJOR] [BlocksFilePlayer.java#L60](https://github.com/rsksmart/rskj/blob/608ce37ececc6cae49fb09cef56bbefdeb570e51/rskj-core/src/main/java/co/rsk/BlocksFilePlayer.java#L60): co.rsk.BlocksFilePlayer.connectBlock(Block) invokes System.exit(...), which shuts down the entire virtual machine [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3ADM_EXIT)
1. ![MAJOR][MAJOR] [BlocksFilePlayer.java#L65](https://github.com/rsksmart/rskj/blob/608ce37ececc6cae49fb09cef56bbefdeb570e51/rskj-core/src/main/java/co/rsk/BlocksFilePlayer.java#L65): Replace this use of System.out or System.err by a logger. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS106)
1. ![MAJOR][MAJOR] [BlocksFilePlayer.java#L65](https://github.com/rsksmart/rskj/blob/608ce37ececc6cae49fb09cef56bbefdeb570e51/rskj-core/src/main/java/co/rsk/BlocksFilePlayer.java#L65): Method co.rsk.BlocksFilePlayer.connectBlock(Block) appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by tinchou** [comment]
I'll update the fed project in a few

**Pull request merged**
