### PR TITLE
Forgive punishment fix

### PR DESCRIPTION
**Pull request by illuque-iov**
Node was not forgiven after Peer Scoring punishment under certain circumstances

## Description

Fix node forgiveness by correctly handling order of operations

## Motivation and Context

Node was not forgiven after Peer Scoring punishment under certain circumstances

## How Has This Been Tested?

- manual testing
- RSKj unit testing

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

* **Other information**:

### CODE REVIEW

**Review by Vovchyk — APPROVED** [review]

**Comment by illuque-iov** [comment]
pipeline:run

**Comment by illuque-iov** [comment]
pipeline:run

**Comment by illuque-iov** [comment]
pipeline:run

**Comment by illuque-iov** [comment]
pipeline:run

**Comment by nagarev** [comment]
pipeline:run

**Pull request merged**
