### PR TITLE
[PAPYRUS-2.2.0-rc] Block processing optimizations

### PR DESCRIPTION
**Pull request by Vovchyk**
## Description
This adds some optimizations to block processing

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

*fit: 2.2-rc*

### CODE REVIEW

**Review by donequis — APPROVED** [review]

**Comment by Vovchyk** [comment]
pipeline: run

**Comment by Vovchyk** [comment]
piepline: run

**Comment by Vovchyk** [comment]
piepline: run

**Review by ajlopezrsk — DISMISSED** [review]

**Comment by ajlopezrsk** [comment]
pipeline: run

**Comment by Vovchyk** [comment]
piepline: run

**Comment by Vovchyk** [comment]
piepline: run

**Comment by Vovchyk** [comment]
pipeline: run

**Review by ajlopezrsk — APPROVED** [review]

**Pull request merged**
