### PR TITLE
Development Node for RegTest

### PR DESCRIPTION
**Pull request by ajlopezrsk**
When the configuration is RegTest, the node have:

- 10 predefined accounts with balance
- Those initial accounts are listed first in the accounts list exposed by web3
- The genesis has a gas limit of 10 millions
- The miner client has an sleep of 1 second

We must add:
targetgaslimit = 10000000

to confi file, to keep the block gas limit along the time

All these changes allow the use of regtest (standalone/private) nodes in development, ie, using truffle framework without requiring the change of truffle configuration

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 34 issues
* ![CRITICAL][CRITICAL] 7 critical
* ![MAJOR][MAJOR] 22 major
* ![MINOR][MINOR] 1 minor
* ![INFO][INFO] 4 info

#### Top 10 issues

1. ![CRITICAL][CRITICAL] [Wallet.java#L223](https://github.com/rsksmart/rskj/blob/887b79ab169da33ba7a04e1c9da3c017b33a462d/rskj-core/src/main/java/co/rsk/core/Wallet.java#L223): Object deserialization is used in co.rsk.core.Wallet.decryptAES(byte[], byte[]) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3AOBJECT_DESERIALIZATION)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L126](https://github.com/rsksmart/rskj/blob/887b79ab169da33ba7a04e1c9da3c017b33a462d/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L126): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L134](https://github.com/rsksmart/rskj/blob/887b79ab169da33ba7a04e1c9da3c017b33a462d/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L134): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L146](https://github.com/rsksmart/rskj/blob/887b79ab169da33ba7a04e1c9da3c017b33a462d/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L146): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L183](https://github.com/rsksmart/rskj/blob/887b79ab169da33ba7a04e1c9da3c017b33a462d/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L183): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L191](https://github.com/rsksmart/rskj/blob/887b79ab169da33ba7a04e1c9da3c017b33a462d/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L191): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L234](https://github.com/rsksmart/rskj/blob/887b79ab169da33ba7a04e1c9da3c017b33a462d/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L234): Missing curly brace. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00121)
1. ![MAJOR][MAJOR] [MinerClientImpl.java#L126](https://github.com/rsksmart/rskj/blob/887b79ab169da33ba7a04e1c9da3c017b33a462d/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L126): Either remove or fill this block of code. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00108)
1. ![MAJOR][MAJOR] [MinerClientImpl.java#L134](https://github.com/rsksmart/rskj/blob/887b79ab169da33ba7a04e1c9da3c017b33a462d/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L134): Either remove or fill this block of code. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00108)
1. ![MAJOR][MAJOR] [MinerClientImpl.java#L146](https://github.com/rsksmart/rskj/blob/887b79ab169da33ba7a04e1c9da3c017b33a462d/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L146): Either remove or fill this block of code. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00108)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 29 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 17 major
* ![MINOR][MINOR] 2 minor
* ![INFO][INFO] 4 info

#### Top 10 issues

1. ![CRITICAL][CRITICAL] [Wallet.java#L223](https://github.com/rsksmart/rskj/blob/b789c1ff84c8881d7a89aa21795e2b518467dca3/rskj-core/src/main/java/co/rsk/core/Wallet.java#L223): Object deserialization is used in co.rsk.core.Wallet.decryptAES(byte[], byte[]) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3AOBJECT_DESERIALIZATION)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L126](https://github.com/rsksmart/rskj/blob/b789c1ff84c8881d7a89aa21795e2b518467dca3/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L126): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L135](https://github.com/rsksmart/rskj/blob/b789c1ff84c8881d7a89aa21795e2b518467dca3/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L135): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L148](https://github.com/rsksmart/rskj/blob/b789c1ff84c8881d7a89aa21795e2b518467dca3/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L148): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L186](https://github.com/rsksmart/rskj/blob/b789c1ff84c8881d7a89aa21795e2b518467dca3/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L186): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L195](https://github.com/rsksmart/rskj/blob/b789c1ff84c8881d7a89aa21795e2b518467dca3/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L195): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![MAJOR][MAJOR] [MinerClientImpl.java#L170](https://github.com/rsksmart/rskj/blob/b789c1ff84c8881d7a89aa21795e2b518467dca3/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L170): Method co.rsk.mine.MinerClientImpl.mineBlock() passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![MAJOR][MAJOR] [MinerClientImpl.java#L229](https://github.com/rsksmart/rskj/blob/b789c1ff84c8881d7a89aa21795e2b518467dca3/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L229): Method co.rsk.mine.MinerClientImpl.findNonce(BtcBlock, BigInteger) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![MAJOR][MAJOR] [MinerClientImpl.java#L255](https://github.com/rsksmart/rskj/blob/b789c1ff84c8881d7a89aa21795e2b518467dca3/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L255): Method co.rsk.mine.MinerClientImpl$RefreshWork.run() passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![MAJOR][MAJOR] [PersonalModuleWalletEnabled.java#L88](https://github.com/rsksmart/rskj/blob/b789c1ff84c8881d7a89aa21795e2b518467dca3/rskj-core/src/main/java/co/rsk/rpc/modules/personal/PersonalModuleWalletEnabled.java#L88): Extract the assignment out of this expression. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AAssignmentInSubExpressionCheck)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by aeidelman** [comment]
@ajlopezrsk please resolve conflicts

**Comment by rskops** [comment]
SonarQube analysis reported 29 issues
* ![CRITICAL][CRITICAL] 7 critical
* ![MAJOR][MAJOR] 17 major
* ![MINOR][MINOR] 1 minor
* ![INFO][INFO] 4 info

#### Top 10 issues

1. ![CRITICAL][CRITICAL] [Wallet.java#L58](https://github.com/rsksmart/rskj/blob/4780cacead82142161c1694f88fbe4bbadc50210/rskj-core/src/main/java/co/rsk/core/Wallet.java#L58): Missing curly brace. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00121)
1. ![CRITICAL][CRITICAL] [Wallet.java#L216](https://github.com/rsksmart/rskj/blob/4780cacead82142161c1694f88fbe4bbadc50210/rskj-core/src/main/java/co/rsk/core/Wallet.java#L216): Object deserialization is used in co.rsk.core.Wallet.decryptAES(byte[], byte[]) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3AOBJECT_DESERIALIZATION)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L126](https://github.com/rsksmart/rskj/blob/4780cacead82142161c1694f88fbe4bbadc50210/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L126): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L135](https://github.com/rsksmart/rskj/blob/4780cacead82142161c1694f88fbe4bbadc50210/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L135): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L148](https://github.com/rsksmart/rskj/blob/4780cacead82142161c1694f88fbe4bbadc50210/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L148): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L186](https://github.com/rsksmart/rskj/blob/4780cacead82142161c1694f88fbe4bbadc50210/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L186): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L195](https://github.com/rsksmart/rskj/blob/4780cacead82142161c1694f88fbe4bbadc50210/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L195): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![MAJOR][MAJOR] [MinerClientImpl.java#L170](https://github.com/rsksmart/rskj/blob/4780cacead82142161c1694f88fbe4bbadc50210/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L170): Method co.rsk.mine.MinerClientImpl.mineBlock() passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![MAJOR][MAJOR] [MinerClientImpl.java#L229](https://github.com/rsksmart/rskj/blob/4780cacead82142161c1694f88fbe4bbadc50210/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L229): Method co.rsk.mine.MinerClientImpl.findNonce(BtcBlock, BigInteger) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![MAJOR][MAJOR] [MinerClientImpl.java#L255](https://github.com/rsksmart/rskj/blob/4780cacead82142161c1694f88fbe4bbadc50210/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L255): Method co.rsk.mine.MinerClientImpl$RefreshWork.run() passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 28 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 17 major
* ![MINOR][MINOR] 1 minor
* ![INFO][INFO] 4 info

#### Top 10 issues

1. ![CRITICAL][CRITICAL] [Wallet.java#L217](https://github.com/rsksmart/rskj/blob/760965ecead629334626caaf9e2481d37c3b6324/rskj-core/src/main/java/co/rsk/core/Wallet.java#L217): Object deserialization is used in co.rsk.core.Wallet.decryptAES(byte[], byte[]) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3AOBJECT_DESERIALIZATION)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L126](https://github.com/rsksmart/rskj/blob/760965ecead629334626caaf9e2481d37c3b6324/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L126): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L135](https://github.com/rsksmart/rskj/blob/760965ecead629334626caaf9e2481d37c3b6324/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L135): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L148](https://github.com/rsksmart/rskj/blob/760965ecead629334626caaf9e2481d37c3b6324/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L148): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L186](https://github.com/rsksmart/rskj/blob/760965ecead629334626caaf9e2481d37c3b6324/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L186): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L195](https://github.com/rsksmart/rskj/blob/760965ecead629334626caaf9e2481d37c3b6324/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L195): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![MAJOR][MAJOR] [MinerClientImpl.java#L170](https://github.com/rsksmart/rskj/blob/760965ecead629334626caaf9e2481d37c3b6324/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L170): Method co.rsk.mine.MinerClientImpl.mineBlock() passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![MAJOR][MAJOR] [MinerClientImpl.java#L229](https://github.com/rsksmart/rskj/blob/760965ecead629334626caaf9e2481d37c3b6324/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L229): Method co.rsk.mine.MinerClientImpl.findNonce(BtcBlock, BigInteger) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![MAJOR][MAJOR] [MinerClientImpl.java#L255](https://github.com/rsksmart/rskj/blob/760965ecead629334626caaf9e2481d37c3b6324/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L255): Method co.rsk.mine.MinerClientImpl$RefreshWork.run() passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![MAJOR][MAJOR] [PersonalModuleWalletEnabled.java#L89](https://github.com/rsksmart/rskj/blob/760965ecead629334626caaf9e2481d37c3b6324/rskj-core/src/main/java/co/rsk/rpc/modules/personal/PersonalModuleWalletEnabled.java#L89): Extract the assignment out of this expression. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AAssignmentInSubExpressionCheck)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 28 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 17 major
* ![MINOR][MINOR] 1 minor
* ![INFO][INFO] 4 info

#### Top 10 issues

1. ![CRITICAL][CRITICAL] [Wallet.java#L217](https://github.com/rsksmart/rskj/blob/a98aac84c4d6dd27cef809769da8ae1c4ee83cd5/rskj-core/src/main/java/co/rsk/core/Wallet.java#L217): Object deserialization is used in co.rsk.core.Wallet.decryptAES(byte[], byte[]) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findsecbugs%3AOBJECT_DESERIALIZATION)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L126](https://github.com/rsksmart/rskj/blob/a98aac84c4d6dd27cef809769da8ae1c4ee83cd5/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L126): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L135](https://github.com/rsksmart/rskj/blob/a98aac84c4d6dd27cef809769da8ae1c4ee83cd5/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L135): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L148](https://github.com/rsksmart/rskj/blob/a98aac84c4d6dd27cef809769da8ae1c4ee83cd5/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L148): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L186](https://github.com/rsksmart/rskj/blob/a98aac84c4d6dd27cef809769da8ae1c4ee83cd5/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L186): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![CRITICAL][CRITICAL] [MinerClientImpl.java#L195](https://github.com/rsksmart/rskj/blob/a98aac84c4d6dd27cef809769da8ae1c4ee83cd5/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L195): Either re-interrupt this method or rethrow the "InterruptedException". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2142)
1. ![MAJOR][MAJOR] [MinerClientImpl.java#L170](https://github.com/rsksmart/rskj/blob/a98aac84c4d6dd27cef809769da8ae1c4ee83cd5/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L170): Method co.rsk.mine.MinerClientImpl.mineBlock() passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![MAJOR][MAJOR] [MinerClientImpl.java#L229](https://github.com/rsksmart/rskj/blob/a98aac84c4d6dd27cef809769da8ae1c4ee83cd5/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L229): Method co.rsk.mine.MinerClientImpl.findNonce(BtcBlock, BigInteger) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![MAJOR][MAJOR] [MinerClientImpl.java#L255](https://github.com/rsksmart/rskj/blob/a98aac84c4d6dd27cef809769da8ae1c4ee83cd5/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L255): Method co.rsk.mine.MinerClientImpl$RefreshWork.run() passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![MAJOR][MAJOR] [PersonalModuleWalletEnabled.java#L91](https://github.com/rsksmart/rskj/blob/a98aac84c4d6dd27cef809769da8ae1c4ee83cd5/rskj-core/src/main/java/co/rsk/rpc/modules/personal/PersonalModuleWalletEnabled.java#L91): Extract the assignment out of this expression. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AAssignmentInSubExpressionCheck)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
