### PR TITLE
New algorithm to sort pending transactions taking into account price

### PR DESCRIPTION
**Pull request by ignaciopulicedonatto**
- New algorithm to sort transactions by price, but taking into account sender and then each cluster is order by nonce.
This method first sorts list of getPendingTransactions into individual sender and sorts those lists by nonce. After the nonce ordering is satisfied, the results are merged back together by price in a heap to make it fast.

- Also added some test to check the correct behaviour of the new ordering.

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 1 issue

1. ![MAJOR][MAJOR] [PendingState.java#L122](https://github.com/rsksmart/rskj/blob/478971839bcbabd892012acf5d187daa71d4520e/rskj-core/src/main/java/co/rsk/core/bc/PendingState.java#L122): Method co.rsk.core.bc.PendingState.sortByPriceTakingIntoAccountSenderAndNonce(List) does not presize the allocation of a collection [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APSC_PRESIZE_COLLECTIONS)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by rskops** [comment]
SonarQube analysis reported 1 issue

1. ![MAJOR][MAJOR] [PendingState.java#L124](https://github.com/rsksmart/rskj/blob/8f39eec01215f30791ddf9feb9a0c14bf26000fb/rskj-core/src/main/java/co/rsk/core/bc/PendingState.java#L124): Method co.rsk.core.bc.PendingState.sortByPriceTakingIntoAccountSenderAndNonce(List) does not presize the allocation of a collection [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APSC_PRESIZE_COLLECTIONS)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by ignaciopulicedonatto** [comment]
This branch is ready to merge

**Comment by rskops** [comment]
SonarQube analysis reported 1 issue

1. ![MAJOR][MAJOR] [PendingState.java#L124](https://github.com/rsksmart/rskj/blob/8e00474e01ec9384e6e593f3562fc077f4b1fba8/rskj-core/src/main/java/co/rsk/core/bc/PendingState.java#L124): Method co.rsk.core.bc.PendingState.sortByPriceTakingIntoAccountSenderAndNonce(List) does not presize the allocation of a collection [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APSC_PRESIZE_COLLECTIONS)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by rskops** [comment]
SonarQube analysis reported 1 issue

1. ![MAJOR][MAJOR] [PendingState.java#L127](https://github.com/rsksmart/rskj/blob/8065c939c3c5bca8da3f9167ab51867ba7163328/rskj-core/src/main/java/co/rsk/core/bc/PendingState.java#L127): Method co.rsk.core.bc.PendingState.sortByPriceTakingIntoAccountSenderAndNonce(List) does not presize the allocation of a collection [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APSC_PRESIZE_COLLECTIONS)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by rskops** [comment]
SonarQube analysis reported 1 issue

1. ![MAJOR][MAJOR] [PendingState.java#L127](https://github.com/rsksmart/rskj/blob/fc55b20e70f7ad0d7a27382d833131ca0fdc56c5/rskj-core/src/main/java/co/rsk/core/bc/PendingState.java#L127): Method co.rsk.core.bc.PendingState.sortByPriceTakingIntoAccountSenderAndNonce(List) does not presize the allocation of a collection [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APSC_PRESIZE_COLLECTIONS)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Pull request merged**
