### PR TITLE
Return 0x instead of 0x00 in empty byte array results via JSON RPC

### PR DESCRIPTION
**Pull request by ajlopez**
Some formatting code was changed from `TypeConverter.toJsonValue` to `TypeConverter.toUnformattedJsonHex`.

## Description

With this code, getting code from a contract that IS NOT a contract, returns `0x`, like other implementations (ganache-cli)

And if a call to a contract returns nothing, it returns 0x instead of `0x00`, again, like other implementations.

Byte arrays in logs were also changed.

ADVICE: when this code was stabilized, detect the few use cases were a `0x00` return value is needed. Apparently, there is none associated to a byte array, only to other numeric values (maybe represented in byte arrays). Then, change the names of the `TypeConverter` methods to more descriptive ones.

## Motivation and Context

The main motivation is compatibility with other implementations and ecosystem tools

## How Has This Been Tested?

Code tests added

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

* **Other information**:

### CODE REVIEW

**Review by Vovchyk — DISMISSED** [review]

**Comment by alejandrod-iov** [comment]
pipeline:run

**Comment by alejandrod-iov** [comment]
pipeline:run

**Review by fedejinich — APPROVED** [review]
lgtm

**Comment by alejandrod-iov** [comment]
pipeline:run

**Review by ajlopezrsk — APPROVED** [review]

**Comment by fedejinich** [comment]
pipeline:run

**Comment by alejandrod-iov** [comment]
pipeline:run

**Pull request merged**
