### PR TITLE
Fix reference to whitelist constants in BridgeTestNetConstants

### PR DESCRIPTION
**Pull request by marcos-iov**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

* **Other information**:

### CODE REVIEW

**Comment by marcos-iov** [comment]
pipeline:run

**Review by julia-zack — APPROVED** [review]

**Review by nathanieliov — APPROVED** [review]

**Review by wilmerrootstock — APPROVED** [review]
LGTM!

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Review by apancorb — APPROVED** [review]

**Review by josedahlquist — APPROVED** [review]

**Pull request merged**
