### PR TITLE
Move call  to getLowestBlock() to getBtcBlockchainBlockLocator() 

### PR DESCRIPTION
**Pull request by pmprete**
getLowestBlock is delaying the execution of the bridge contract so we should avoid calling it if its not mandatory

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 65 issues
* ![CRITICAL][CRITICAL] 5 critical
* ![MAJOR][MAJOR] 36 major
* ![MINOR][MINOR] 8 minor
* ![INFO][INFO] 16 info

#### Top 10 issues

1. ![CRITICAL][CRITICAL] [BridgeSupport.java#L335](https://github.com/rsksmart/rskj/blob/364a5571b64136fb5e4d64b3f8a5d1edb07213a6/rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java#L335): Method co.rsk.peg.BridgeSupport.registerBtcTransaction(Transaction, byte[], int, byte[]) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![CRITICAL][CRITICAL] [BridgeSupport.java#L343](https://github.com/rsksmart/rskj/blob/364a5571b64136fb5e4d64b3f8a5d1edb07213a6/rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java#L343): Method co.rsk.peg.BridgeSupport.registerBtcTransaction(Transaction, byte[], int, byte[]) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![CRITICAL][CRITICAL] [BridgeSupport.java#L356](https://github.com/rsksmart/rskj/blob/364a5571b64136fb5e4d64b3f8a5d1edb07213a6/rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java#L356): Method co.rsk.peg.BridgeSupport.registerBtcTransaction(Transaction, byte[], int, byte[]) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![CRITICAL][CRITICAL] [BridgeSupport.java#L372](https://github.com/rsksmart/rskj/blob/364a5571b64136fb5e4d64b3f8a5d1edb07213a6/rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java#L372): Method co.rsk.peg.BridgeSupport.registerBtcTransaction(Transaction, byte[], int, byte[]) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![CRITICAL][CRITICAL] [BridgeSupport.java#L847](https://github.com/rsksmart/rskj/blob/364a5571b64136fb5e4d64b3f8a5d1edb07213a6/rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java#L847): Remove this unused method parameter "executionBlockNumber". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [BridgeSupport.java#](https://github.com/rsksmart/rskj/blob/364a5571b64136fb5e4d64b3f8a5d1edb07213a6/rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java#): This file has 1,184 lines, which is greater than 1,000 authorized. Split it into smaller files. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [BridgeSupport.java#L213](https://github.com/rsksmart/rskj/blob/364a5571b64136fb5e4d64b3f8a5d1edb07213a6/rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java#L213): Method co.rsk.peg.BridgeSupport.getCheckPoints() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [BridgeSupport.java#L308](https://github.com/rsksmart/rskj/blob/364a5571b64136fb5e4d64b3f8a5d1edb07213a6/rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java#L308): The Cyclomatic Complexity of this method "registerBtcTransaction" is 16 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [BridgeSupport.java#L429](https://github.com/rsksmart/rskj/blob/364a5571b64136fb5e4d64b3f8a5d1edb07213a6/rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java#L429): Method co.rsk.peg.BridgeSupport.registerBtcTransaction(Transaction, byte[], int, byte[]) calls String.format on a static (non parameterized) format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ASPP_STATIC_FORMAT_STRING)
1. ![MAJOR][MAJOR] [BridgeSupport.java#L429](https://github.com/rsksmart/rskj/blob/364a5571b64136fb5e4d64b3f8a5d1edb07213a6/rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java#L429): Format-string method String.format(String, Object[]) called with format string "whitelist money return tx build for btc tx {} error. Return was to {}. Tx {}. Value {}" wants 0 arguments but is given 4 in co.rsk.peg.BridgeSupport.registerBtcTransaction(Transaction, byte[], int, byte[]) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3AVA_FORMAT_STRING_EXTRA_ARGUMENTS_PASSED)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by tinchou** [comment]
Please fix the critical issues

**Comment by amendelzon** [comment]
In general it looks good. Nevertheless I feel we should:

a) Get this in the context of a ticket for fixing bridge performance issues (initialization of any bitcoin-related resources can also be delayed) and plan before doing.
b) Cover with unit tests.

**Comment by rskops** [comment]
SonarQube analysis reported 61 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 36 major
* ![MINOR][MINOR] 8 minor
* ![INFO][INFO] 16 info

#### Top 10 issues

1. ![CRITICAL][CRITICAL] [BridgeSupport.java#L847](https://github.com/rsksmart/rskj/blob/837425b222e2381fa2a61c5b2d5998a79b617e07/rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java#L847): Remove this unused method parameter "executionBlockNumber". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [BridgeSupport.java#](https://github.com/rsksmart/rskj/blob/837425b222e2381fa2a61c5b2d5998a79b617e07/rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java#): This file has 1,184 lines, which is greater than 1,000 authorized. Split it into smaller files. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [BridgeSupport.java#L213](https://github.com/rsksmart/rskj/blob/837425b222e2381fa2a61c5b2d5998a79b617e07/rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java#L213): Method co.rsk.peg.BridgeSupport.getCheckPoints() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [BridgeSupport.java#L308](https://github.com/rsksmart/rskj/blob/837425b222e2381fa2a61c5b2d5998a79b617e07/rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java#L308): The Cyclomatic Complexity of this method "registerBtcTransaction" is 16 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [BridgeSupport.java#L429](https://github.com/rsksmart/rskj/blob/837425b222e2381fa2a61c5b2d5998a79b617e07/rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java#L429): Method co.rsk.peg.BridgeSupport.registerBtcTransaction(Transaction, byte[], int, byte[]) calls String.format on a static (non parameterized) format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ASPP_STATIC_FORMAT_STRING)
1. ![MAJOR][MAJOR] [BridgeSupport.java#L429](https://github.com/rsksmart/rskj/blob/837425b222e2381fa2a61c5b2d5998a79b617e07/rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java#L429): Format-string method String.format(String, Object[]) called with format string "whitelist money return tx build for btc tx {} error. Return was to {}. Tx {}. Value {}" wants 0 arguments but is given 4 in co.rsk.peg.BridgeSupport.registerBtcTransaction(Transaction, byte[], int, byte[]) [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=findbugs%3AVA_FORMAT_STRING_EXTRA_ARGUMENTS_PASSED)
1. ![MAJOR][MAJOR] [BridgeSupport.java#L619](https://github.com/rsksmart/rskj/blob/837425b222e2381fa2a61c5b2d5998a79b617e07/rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java#L619): Method co.rsk.peg.BridgeSupport.processFundsMigration() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [BridgeSupport.java#L646](https://github.com/rsksmart/rskj/blob/837425b222e2381fa2a61c5b2d5998a79b617e07/rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java#L646): Either log or rethrow this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [BridgeSupport.java#L689](https://github.com/rsksmart/rskj/blob/837425b222e2381fa2a61c5b2d5998a79b617e07/rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java#L689): Reduce this lambda expression number of lines from 36 to at most 20. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [BridgeSupport.java#L712](https://github.com/rsksmart/rskj/blob/837425b222e2381fa2a61c5b2d5998a79b617e07/rskj-core/src/main/java/co/rsk/peg/BridgeSupport.java#L712): Method co.rsk.peg.BridgeSupport.lambda$processReleaseRequests$5(ReleaseTransactionBuilder, ReleaseRequestQueue$Entry) appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request closed without merging**
