### PR TITLE
Fixes for OpenZeppelin

### PR DESCRIPTION
**Pull request by tinchou**
Some quick fixes for OpenZeppelin tests that use truffle

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 1 issue

1. ![INFO][INFO] [IndexedBlockStore.java#L541](https://github.com/rsksmart/rskj/blob/e43d6c5efc34042110cdb865480193763440d14a/rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java#L541): Complete the task associated to this TODO comment. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1135)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'

**Comment by rskops** [comment]
SonarQube analysis reported 1 issue

1. ![INFO][INFO] [IndexedBlockStore.java#L541](https://github.com/rsksmart/rskj/blob/a75acd1c2061a7dd55c45c6d5bf1ab468b6f1ac4/rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java#L541): Complete the task associated to this TODO comment. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1135)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'

**Comment by rskops** [comment]
SonarQube analysis reported 2 issues

1. ![MAJOR][MAJOR] [MinerClientImpl.java#L106](https://github.com/rsksmart/rskj/blob/3e501916465f29ca11ad0b4bd3fc9d83ba85a8b7/rskj-core/src/main/java/co/rsk/mine/MinerClientImpl.java#L106): Merge this if statement with the enclosing one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1066)
1. ![INFO][INFO] [IndexedBlockStore.java#L541](https://github.com/rsksmart/rskj/blob/3e501916465f29ca11ad0b4bd3fc9d83ba85a8b7/rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java#L541): Complete the task associated to this TODO comment. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1135)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by rskops** [comment]
SonarQube analysis reported 1 issue

1. ![INFO][INFO] [IndexedBlockStore.java#L537](https://github.com/rsksmart/rskj/blob/50dd20123c4343cb46bb71c4591f3224788ec3b9/rskj-core/src/main/java/org/ethereum/db/IndexedBlockStore.java#L537): Complete the task associated to this TODO comment. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1135)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'

**Comment by ignaciopulicedonatto** [comment]
This changes are neccery to mere automine feature.

**Comment by tinchou** [comment]
Superseded by https://github.com/rsksmart/rskj/pull/664

**Pull request closed without merging**
