### PR TITLE
feat: publish containers into DockerHub

### PR DESCRIPTION
**Pull request by lucasvuotto**

### CODE REVIEW

**Comment by lucasvuotto** [comment]
I converted this to a draft.

- `ENTRYPOINT` needs some love in order to ease documentation
- We're still discussing on which events we should publish

**Comment by lucasvuotto** [comment]
pipeline: run

**Comment by lucasvuotto** [comment]
pipeline: run

**Comment by lucasvuotto** [comment]
pipeline: run

**Comment by lucasvuotto** [comment]
pipeline: run

**Review by Vovchyk — DISMISSED** [review]

**Review by david-iov — COMMENTED** [review]
Hello @Vovchyk, as soon as this is safe to merge, Can you please kindly merge, as some other tasks have been pending on this feature working?

**Comment by lucasvuotto** [comment]
pipeline: run

**Comment by lucasvuotto** [comment]
pipeline: run

**Comment by lucasvuotto** [comment]
pipeline: run

**Comment by lucasvuotto** [comment]
pipeline: run

**Comment by lucasvuotto** [comment]
pipeline: run

**Comment by lucasvuotto** [comment]
pipeline: run

**Comment by lucasvuotto** [comment]
pipeline: run

**Comment by lucasvuotto** [comment]
pipeline: run

**Comment by lucasvuotto** [comment]
pipeline: run

**Comment by lucasvuotto** [comment]
pipeline: run

**Comment by Vovchyk** [comment]
pipeline:run

**Review by Vovchyk — APPROVED** [review]

**Pull request merged**
