### PR TITLE
Changing version 2.1.0 to 2.2.0, SNAPSHOT

### PR DESCRIPTION
**Pull request by patogallaiovlabs**
*ci: begin_2.2.0*
*fed: begin_2.2.0.0*
*fit: begin_2.2.0.0*

### CODE REVIEW

**Review by ajlopezrsk — APPROVED** [review]

**Comment by josedahlquist** [comment]
pipeline:rune

**Comment by josedahlquist** [comment]
pipeline:run

**Comment by patogallaiovlabs** [comment]
pipeline:run

**Comment by josedahlquist** [comment]
pipeline:run

**Comment by patogallaiovlabs** [comment]
pipeline:run

**Review by josedahlquist — APPROVED** [review]

**Pull request merged**
