### PR TITLE
Remove fallback mining signing, but not validation

### PR DESCRIPTION
**Pull request by tinchou**
Since both networks have enabled RSKIP98, we will never again sign blocks with the fallback mechanism.

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 9 issues

1. ![CRITICAL][CRITICAL] [MinerServerImpl.java#L26](https://github.com/rsksmart/rskj/blob/d847448a4c7214e93431a5ce963adbdf578a7742/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L26): Unused import - co.rsk.core.BlockDifficulty. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck)
1. ![CRITICAL][CRITICAL] [MinerServerImpl.java#L41](https://github.com/rsksmart/rskj/blob/d847448a4c7214e93431a5ce963adbdf578a7742/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L41): Unused import - org.ethereum.crypto.ECKey. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck)
1. ![CRITICAL][CRITICAL] [MinerServerImpl.java#L45](https://github.com/rsksmart/rskj/blob/d847448a4c7214e93431a5ce963adbdf578a7742/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L45): Unused import - org.ethereum.util.RLP. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck)
1. ![CRITICAL][CRITICAL] [MinerServerImpl.java#L52](https://github.com/rsksmart/rskj/blob/d847448a4c7214e93431a5ce963adbdf578a7742/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L52): Unused import - javax.annotation.Nullable. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck)
1. ![CRITICAL][CRITICAL] [MinerServerImpl.java#L54](https://github.com/rsksmart/rskj/blob/d847448a4c7214e93431a5ce963adbdf578a7742/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L54): Unused import - java.io.File. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck)
1. ![CRITICAL][CRITICAL] [MinerServerImpl.java#L55](https://github.com/rsksmart/rskj/blob/d847448a4c7214e93431a5ce963adbdf578a7742/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L55): Unused import - java.io.FileInputStream. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck)
1. ![CRITICAL][CRITICAL] [MinerServerImpl.java#L56](https://github.com/rsksmart/rskj/blob/d847448a4c7214e93431a5ce963adbdf578a7742/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L56): Unused import - java.io.IOException. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck)
1. ![CRITICAL][CRITICAL] [MinerServerImpl.java#L109](https://github.com/rsksmart/rskj/blob/d847448a4c7214e93431a5ce963adbdf578a7742/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L109): Remove this unused "difficultyCalculator" private field. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1068)
1. ![MINOR][MINOR] [ProofOfWorkRule.java#L87](https://github.com/rsksmart/rskj/blob/d847448a4c7214e93431a5ce963adbdf578a7742/rskj-core/src/main/java/co/rsk/validators/ProofOfWorkRule.java#L87): Rename "constants" which hides the field declared at line 61. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 2 issues

1. ![CRITICAL][CRITICAL] [MinerServerImpl.java#L27](https://github.com/rsksmart/rskj/blob/31c3cd6a03e5f215f4a392360834fd23069b3c14/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L27): Unused import - co.rsk.core.DifficultyCalculator. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck)
1. ![MINOR][MINOR] [ProofOfWorkRule.java#L87](https://github.com/rsksmart/rskj/blob/31c3cd6a03e5f215f4a392360834fd23069b3c14/rskj-core/src/main/java/co/rsk/validators/ProofOfWorkRule.java#L87): Rename "constants" which hides the field declared at line 61. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 1 issue

1. ![MINOR][MINOR] [ProofOfWorkRule.java#L87](https://github.com/rsksmart/rskj/blob/b23137b0e668b66916e25d91635b9e16b9b84b51/rskj-core/src/main/java/co/rsk/validators/ProofOfWorkRule.java#L87): Rename "constants" which hides the field declared at line 61. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 1 issue

1. ![MINOR][MINOR] [ProofOfWorkRule.java#L87](https://github.com/rsksmart/rskj/blob/7d69909348055cb1c1925684d3de5810ae954967/rskj-core/src/main/java/co/rsk/validators/ProofOfWorkRule.java#L87): Rename "constants" which hides the field declared at line 61. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by tinchou** [comment]
@diega I added a second commit, removing some more code :).

I moved some responsibility from `MinerServer` to `MinerClock`. It doesn't have time-related methods now.

**Comment by rskops** [comment]
SonarQube analysis reported 1 issue

1. ![MINOR][MINOR] [ProofOfWorkRule.java#L89](https://github.com/rsksmart/rskj/blob/01e2321b6213aece9c7dd44a9a867f6885f76c5a/rskj-core/src/main/java/co/rsk/validators/ProofOfWorkRule.java#L89): Rename "constants" which hides the field declared at line 62. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 1 issue

1. ![MINOR][MINOR] [ProofOfWorkRule.java#L89](https://github.com/rsksmart/rskj/blob/978a969e8933092305b8b396a679ceb46ec1f487/rskj-core/src/main/java/co/rsk/validators/ProofOfWorkRule.java#L89): Rename "constants" which hides the field declared at line 62. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
