### PR TITLE
KeyValueDataSource#keys() result should allow contains() call

### PR DESCRIPTION
**Pull request by illuque-iov**
Allow running contains() on KeyValueDataSource#keys() result 

## Description

Use ByteArrayWrapper as return type of KeyValueDataSource#keys() instead of byte[] to ensure expected behavior: contains() working, etc.

## Motivation and Context
https://github.com/rsksmart/rskj/issues/1541

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

* **Other information**:

### CODE REVIEW

**Review by Vovchyk — APPROVED** [review]

**Comment by illuque-iov** [comment]
pipeline:run

**Comment by illuque-iov** [comment]
pipeline:run

**Comment by illuque-iov** [comment]
pipeline:run

**Comment by illuque-iov** [comment]
pipeline:run

**Comment by illuque-iov** [comment]
pipeline:run

**Review by Vovchyk — APPROVED** [review]

**Pull request merged**
