### PR TITLE
Shutdown node by RPC feature

### PR DESCRIPTION
**Pull request by SergioDemianLerner**
This PR add a new RPC method "rsk_shutdown" to shutdown the node.
## Description

A new RPC method named rsk_shutdown is added. This method performs System.exit(0), which smoothly and safely shutsdown the running threads. 
## Motivation and Context

There are several reasons why one may need to shutdown a node by RPC:
* When running rskj node in Intellij, Intellij refuses to send CTRL+C (SIGTERM == terminate) signals to the running process. The only way to terminate a process is by pressing the stop button, which sends a SIGKILL signal, which terminates all threads immediately potentially leaving databases in a broken state.  This prevents the use of the IDE from debugging live nodes.
*  Sometimes it is important to be able to remotely shutdown a node asap. For example, if a remote execution vulnerability is found.

## How Has This Been Tested?

I sent rsk_shutdown by RPC and it worked.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Requires Activation Code (Hard Fork)

**Other information**:
There is no documentation for RPC commands in the code, so no documentation was added to the code.

If merged, I will contact the developer's site maintainer to update the corresponding page.

### CODE REVIEW

**Comment by heitorfm** [comment]
This is interesting. Maybe it could close the databases to ensure that the data is safe ?

**Comment by Vovchyk** [comment]
@SergioDemianLerner,

> When running rskj node in Intellij, Intellij refuses to send CTRL+C (SIGTERM == terminate) signals to the running process. The only way to terminate a process is by pressing the stop button, which sends a SIGKILL signal, which terminates all threads immediately potentially leaving databases in a broken state. This prevents the use of the IDE from debugging live nodes.

afaik, if you do `RUN` in IntelliJ and then stop, then the IDE sends the `SIGTERM` signal, which allows a java process to gracefully finish its work. But if you do `DEBUG` and then press the stop button, the IDE sends `SIGKILL`, which basically does what you described in the description. But in this case while debugging your application you could just do `ps uax | grep co.rsk.Start` to get pid of your java process and then manually stop it via `kill -SIGTERM <PID>`

> Sometimes it is important to be able to remotely shutdown a node asap. For example, if a remote execution vulnerability is found.

not sure if this is the most secure way to stop a node remotely. Doing this via a secured ssh connection might be a better option. Perhaps, if introduced, this feature should be disabled by default.

**Comment by Vovchyk** [comment]
pipeline:run

**Review by illuque-iov — APPROVED** [review]
LGTM

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Pull request merged**
