### PR TITLE
Solidity event encoding. Events for lock and release request added

### PR DESCRIPTION
**Pull request by marcos-iov**
*fit:solidity-integration* *fed:solidity-event-encoding*

### CODE REVIEW

**Comment by josedahlquist** [comment]
Pipeline: run

**Comment by josedahlquist** [comment]
Pipeline: run

**Comment by guidohernan93** [comment]
pipeline:run

**Comment by guidohernan93** [comment]
Pipeline: run

**Comment by marcos-iov** [comment]
pipeline: run

**Comment by josedahlquist** [comment]
pipeline:run

**Pull request merged**
