### PR TITLE
Remove bridge reflection usage

### PR DESCRIPTION
**Pull request by diega**

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 80 issues
* ![MAJOR][MAJOR] 61 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 16 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [Bridge.java#L230](https://github.com/rsksmart/rskj/blob/f29974e04980aee10ffc7b30090db17ad18d675d/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L230): Either log or rethrow this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [Bridge.java#L259](https://github.com/rsksmart/rskj/blob/f29974e04980aee10ffc7b30090db17ad18d675d/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L259): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [Bridge.java#L265](https://github.com/rsksmart/rskj/blob/f29974e04980aee10ffc7b30090db17ad18d675d/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L265): Extract this nested try block into a separate method. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1141)
1. ![MAJOR][MAJOR] [Bridge.java#L271](https://github.com/rsksmart/rskj/blob/f29974e04980aee10ffc7b30090db17ad18d675d/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L271): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [Bridge.java#L281](https://github.com/rsksmart/rskj/blob/f29974e04980aee10ffc7b30090db17ad18d675d/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L281): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Bridge.java#L285](https://github.com/rsksmart/rskj/blob/f29974e04980aee10ffc7b30090db17ad18d675d/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L285): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Bridge.java#L294](https://github.com/rsksmart/rskj/blob/f29974e04980aee10ffc7b30090db17ad18d675d/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L294): Remove usage of generic wildcard type. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1452)
1. ![MAJOR][MAJOR] [Bridge.java#L294](https://github.com/rsksmart/rskj/blob/f29974e04980aee10ffc7b30090db17ad18d675d/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L294): Remove this unused method parameter "args". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [Bridge.java#L294](https://github.com/rsksmart/rskj/blob/f29974e04980aee10ffc7b30090db17ad18d675d/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L294): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Bridge.java#L301](https://github.com/rsksmart/rskj/blob/f29974e04980aee10ffc7b30090db17ad18d675d/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L301): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 81 issues
* ![MAJOR][MAJOR] 62 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 16 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [Bridge.java#L230](https://github.com/rsksmart/rskj/blob/f1e9908e8295603df00d4397e97d907306c38471/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L230): Either log or rethrow this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [Bridge.java#L259](https://github.com/rsksmart/rskj/blob/f1e9908e8295603df00d4397e97d907306c38471/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L259): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [Bridge.java#L265](https://github.com/rsksmart/rskj/blob/f1e9908e8295603df00d4397e97d907306c38471/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L265): Extract this nested try block into a separate method. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1141)
1. ![MAJOR][MAJOR] [Bridge.java#L271](https://github.com/rsksmart/rskj/blob/f1e9908e8295603df00d4397e97d907306c38471/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L271): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [Bridge.java#L281](https://github.com/rsksmart/rskj/blob/f1e9908e8295603df00d4397e97d907306c38471/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L281): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Bridge.java#L285](https://github.com/rsksmart/rskj/blob/f1e9908e8295603df00d4397e97d907306c38471/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L285): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Bridge.java#L294](https://github.com/rsksmart/rskj/blob/f1e9908e8295603df00d4397e97d907306c38471/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L294): Remove usage of generic wildcard type. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1452)
1. ![MAJOR][MAJOR] [Bridge.java#L294](https://github.com/rsksmart/rskj/blob/f1e9908e8295603df00d4397e97d907306c38471/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L294): Remove this unused method parameter "args". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [Bridge.java#L294](https://github.com/rsksmart/rskj/blob/f1e9908e8295603df00d4397e97d907306c38471/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L294): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Bridge.java#L301](https://github.com/rsksmart/rskj/blob/f1e9908e8295603df00d4397e97d907306c38471/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L301): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 81 issues
* ![MAJOR][MAJOR] 62 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 16 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [Bridge.java#L229](https://github.com/rsksmart/rskj/blob/d983548bd1f1eb048b2a65f3798e12b7998c9ddd/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L229): Either log or rethrow this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [Bridge.java#L258](https://github.com/rsksmart/rskj/blob/d983548bd1f1eb048b2a65f3798e12b7998c9ddd/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L258): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [Bridge.java#L264](https://github.com/rsksmart/rskj/blob/d983548bd1f1eb048b2a65f3798e12b7998c9ddd/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L264): Extract this nested try block into a separate method. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1141)
1. ![MAJOR][MAJOR] [Bridge.java#L270](https://github.com/rsksmart/rskj/blob/d983548bd1f1eb048b2a65f3798e12b7998c9ddd/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L270): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [Bridge.java#L280](https://github.com/rsksmart/rskj/blob/d983548bd1f1eb048b2a65f3798e12b7998c9ddd/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L280): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Bridge.java#L284](https://github.com/rsksmart/rskj/blob/d983548bd1f1eb048b2a65f3798e12b7998c9ddd/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L284): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Bridge.java#L293](https://github.com/rsksmart/rskj/blob/d983548bd1f1eb048b2a65f3798e12b7998c9ddd/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L293): Remove usage of generic wildcard type. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1452)
1. ![MAJOR][MAJOR] [Bridge.java#L293](https://github.com/rsksmart/rskj/blob/d983548bd1f1eb048b2a65f3798e12b7998c9ddd/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L293): Remove this unused method parameter "args". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [Bridge.java#L293](https://github.com/rsksmart/rskj/blob/d983548bd1f1eb048b2a65f3798e12b7998c9ddd/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L293): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Bridge.java#L300](https://github.com/rsksmart/rskj/blob/d983548bd1f1eb048b2a65f3798e12b7998c9ddd/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L300): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 83 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 62 major
* ![MINOR][MINOR] 4 minor
* ![INFO][INFO] 16 info

#### Top 10 issues

1. ![CRITICAL][CRITICAL] [BridgeMethods.java#L23](https://github.com/rsksmart/rskj/blob/192e66594ec60191858c23ff8d0091ab3bb494bd/rskj-core/src/main/java/co/rsk/peg/BridgeMethods.java#L23): Unused import - java.util.HashMap. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=checkstyle%3Acom.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck)
1. ![MAJOR][MAJOR] [Bridge.java#L219](https://github.com/rsksmart/rskj/blob/192e66594ec60191858c23ff8d0091ab3bb494bd/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L219): Either log or rethrow this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [Bridge.java#L248](https://github.com/rsksmart/rskj/blob/192e66594ec60191858c23ff8d0091ab3bb494bd/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L248): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [Bridge.java#L254](https://github.com/rsksmart/rskj/blob/192e66594ec60191858c23ff8d0091ab3bb494bd/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L254): Extract this nested try block into a separate method. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1141)
1. ![MAJOR][MAJOR] [Bridge.java#L260](https://github.com/rsksmart/rskj/blob/192e66594ec60191858c23ff8d0091ab3bb494bd/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L260): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [Bridge.java#L270](https://github.com/rsksmart/rskj/blob/192e66594ec60191858c23ff8d0091ab3bb494bd/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L270): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Bridge.java#L274](https://github.com/rsksmart/rskj/blob/192e66594ec60191858c23ff8d0091ab3bb494bd/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L274): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Bridge.java#L283](https://github.com/rsksmart/rskj/blob/192e66594ec60191858c23ff8d0091ab3bb494bd/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L283): Remove usage of generic wildcard type. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1452)
1. ![MAJOR][MAJOR] [Bridge.java#L283](https://github.com/rsksmart/rskj/blob/192e66594ec60191858c23ff8d0091ab3bb494bd/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L283): Remove this unused method parameter "args". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [Bridge.java#L283](https://github.com/rsksmart/rskj/blob/192e66594ec60191858c23ff8d0091ab3bb494bd/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L283): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 81 issues
* ![MAJOR][MAJOR] 62 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 16 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [Bridge.java#L219](https://github.com/rsksmart/rskj/blob/19772186a890591584fcca692ed0663081912d3a/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L219): Either log or rethrow this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [Bridge.java#L248](https://github.com/rsksmart/rskj/blob/19772186a890591584fcca692ed0663081912d3a/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L248): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [Bridge.java#L254](https://github.com/rsksmart/rskj/blob/19772186a890591584fcca692ed0663081912d3a/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L254): Extract this nested try block into a separate method. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1141)
1. ![MAJOR][MAJOR] [Bridge.java#L260](https://github.com/rsksmart/rskj/blob/19772186a890591584fcca692ed0663081912d3a/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L260): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [Bridge.java#L270](https://github.com/rsksmart/rskj/blob/19772186a890591584fcca692ed0663081912d3a/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L270): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Bridge.java#L274](https://github.com/rsksmart/rskj/blob/19772186a890591584fcca692ed0663081912d3a/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L274): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Bridge.java#L283](https://github.com/rsksmart/rskj/blob/19772186a890591584fcca692ed0663081912d3a/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L283): Remove usage of generic wildcard type. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1452)
1. ![MAJOR][MAJOR] [Bridge.java#L283](https://github.com/rsksmart/rskj/blob/19772186a890591584fcca692ed0663081912d3a/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L283): Remove this unused method parameter "args". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [Bridge.java#L283](https://github.com/rsksmart/rskj/blob/19772186a890591584fcca692ed0663081912d3a/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L283): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Bridge.java#L290](https://github.com/rsksmart/rskj/blob/19772186a890591584fcca692ed0663081912d3a/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L290): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by tinchou** [comment]
@amendelzon I think that `Optional` is one of the strengths of this code!

I think you are looking at the methods individually: those methods don't have an _optionality_ per se, and using `Optional` seems strange.

But on the other hand, these are not _true_ methods: these are implementations of a `BridgeMethodExecutor` interface, and thus act more like classes than methods. When you look at `BridgeMethodExecutor`'s interface, it makes sense for the `execute` method to return `Optional`: some methods might not have a return value, some methods might have one.

I would agree that changing the `BridgeMethodExecutor.execute` signature to allow void methods would be the best solution, but that doesn't seem to be possible. And to workaround this, we should use `Optional` instead of returning `null` per our own [guidelines](https://github.com/rsksmart/rskj/blob/master/CONTRIBUTING.md):

> **Prefer `Optional<T>` over null**
> 
> Unlike with `null`s, you’re forced to check for existence before using an `Optional` value.

**Comment by amendelzon** [comment]
@tinchou I am looking at the individual methods, because that's what they are. Each of those methods performs an independent operation of the rest.

I agree with respect to the `execute` method: that method should indeed return `Optional`.

The guideline reads "prefer", which literally means there can be exceptions to the rule. I believe this to be one of those exceptions. If a way is creating a method that returns null, it doesn't sound as bad to me as changing twenty-something methods' signatures to something that does not reflect their actual return values.

What we need is machinery to go from good signatures in the actual methods to the `Optional` in the `execute` method.

**Comment by amendelzon** [comment]
@tinchou I like the solution! I agree in that it's not the most elegant, but at least it isolates de aforementioned complexity in a single place.

I'd probably add that we could even change the signature of existing Bridge methods that nowadays can return nullables to `Optional`, and that would wrap up the job.

Good work!

**Comment by rskops** [comment]
SonarQube analysis reported 75 issues
* ![MAJOR][MAJOR] 56 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 16 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [Bridge.java#L218](https://github.com/rsksmart/rskj/blob/5908c6cf4f43b7d51b9ceed8455a9f26369e2d42/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L218): Either log or rethrow this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [Bridge.java#L247](https://github.com/rsksmart/rskj/blob/5908c6cf4f43b7d51b9ceed8455a9f26369e2d42/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L247): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [Bridge.java#L253](https://github.com/rsksmart/rskj/blob/5908c6cf4f43b7d51b9ceed8455a9f26369e2d42/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L253): Extract this nested try block into a separate method. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1141)
1. ![MAJOR][MAJOR] [Bridge.java#L259](https://github.com/rsksmart/rskj/blob/5908c6cf4f43b7d51b9ceed8455a9f26369e2d42/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L259): Return an empty array instead of null. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1168)
1. ![MAJOR][MAJOR] [Bridge.java#L269](https://github.com/rsksmart/rskj/blob/5908c6cf4f43b7d51b9ceed8455a9f26369e2d42/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L269): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Bridge.java#L273](https://github.com/rsksmart/rskj/blob/5908c6cf4f43b7d51b9ceed8455a9f26369e2d42/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L273): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Bridge.java#L282](https://github.com/rsksmart/rskj/blob/5908c6cf4f43b7d51b9ceed8455a9f26369e2d42/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L282): Remove this unused method parameter "args". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [Bridge.java#L290](https://github.com/rsksmart/rskj/blob/5908c6cf4f43b7d51b9ceed8455a9f26369e2d42/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L290): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Bridge.java#L313](https://github.com/rsksmart/rskj/blob/5908c6cf4f43b7d51b9ceed8455a9f26369e2d42/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L313): Define and throw a dedicated exception instead of using a generic one. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00112)
1. ![MAJOR][MAJOR] [Bridge.java#L328](https://github.com/rsksmart/rskj/blob/5908c6cf4f43b7d51b9ceed8455a9f26369e2d42/rskj-core/src/main/java/co/rsk/peg/Bridge.java#L328): Method co.rsk.peg.Bridge.registerBtcTransaction(Object[]) accesses list or array with constant index [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ACLI_CONSTANT_LIST_INDEX)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request closed without merging**
