### PR TITLE
processBest only on imported best in TransactionPoolImpl

### PR DESCRIPTION
**Pull request by tinchou**

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 67 issues
* ![CRITICAL][CRITICAL] 8 critical
* ![MAJOR][MAJOR] 36 major
* ![MINOR][MINOR] 12 minor
* ![INFO][INFO] 11 info

#### Top 10 issues

1. ![CRITICAL][CRITICAL] [MinerServerImpl.java#L289](https://github.com/rsksmart/rskj/blob/1f10f1a43de28740cddfaead56e29cfaf23d760c/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L289): Explicitly declare the visibility for "privKey0". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2039)
1. ![CRITICAL][CRITICAL] [MinerServerImpl.java#L290](https://github.com/rsksmart/rskj/blob/1f10f1a43de28740cddfaead56e29cfaf23d760c/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L290): Explicitly declare the visibility for "privKey1". [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2039)
1. ![CRITICAL][CRITICAL] [MinerServerImpl.java#L311](https://github.com/rsksmart/rskj/blob/1f10f1a43de28740cddfaead56e29cfaf23d760c/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L311): Make the enclosing method "static" or remove this set. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2696)
1. ![CRITICAL][CRITICAL] [MinerServerImpl.java#L315](https://github.com/rsksmart/rskj/blob/1f10f1a43de28740cddfaead56e29cfaf23d760c/rskj-core/src/main/java/co/rsk/mine/MinerServerImpl.java#L315): Make the enclosing method "static" or remove this set. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2696)
1. ![CRITICAL][CRITICAL] [CompositeEthereumListener.java#L57](https://github.com/rsksmart/rskj/blob/1f10f1a43de28740cddfaead56e29cfaf23d760c/rskj-core/src/main/java/org/ethereum/listener/CompositeEthereumListener.java#L57): This call to "add()" may be a performance hot spot if the collection is large. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2250)
1. ![CRITICAL][CRITICAL] [CompositeEthereumListener.java#L60](https://github.com/rsksmart/rskj/blob/1f10f1a43de28740cddfaead56e29cfaf23d760c/rskj-core/src/main/java/org/ethereum/listener/CompositeEthereumListener.java#L60): This call to "remove()" may be a performance hot spot if the collection is large. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS2250)
1. ![CRITICAL][CRITICAL] [EthHandler.java#L87](https://github.com/rsksmart/rskj/blob/1f10f1a43de28740cddfaead56e29cfaf23d760c/rskj-core/src/main/java/org/ethereum/net/eth/handler/EthHandler.java#L87): Method org.ethereum.net.eth.handler.EthHandler.channelRead0(ChannelHandlerContext, EthMessage) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![CRITICAL][CRITICAL] [EthHandler.java#L126](https://github.com/rsksmart/rskj/blob/1f10f1a43de28740cddfaead56e29cfaf23d760c/rskj-core/src/main/java/org/ethereum/net/eth/handler/EthHandler.java#L126): Method org.ethereum.net.eth.handler.EthHandler.sendMessage(EthMessage) passes a concatenated string to SLF4J's format string [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3ALO_APPENDED_STRING_IN_FORMAT_STRING)
1. ![MAJOR][MAJOR] [BlockChainImpl.java#L184](https://github.com/rsksmart/rskj/blob/1f10f1a43de28740cddfaead56e29cfaf23d760c/rskj-core/src/main/java/co/rsk/core/bc/BlockChainImpl.java#L184): The Cyclomatic Complexity of this method "internalTryToConnect" is 22 which is greater than 10 authorized. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [BlockChainImpl.java#L186](https://github.com/rsksmart/rskj/blob/1f10f1a43de28740cddfaead56e29cfaf23d760c/rskj-core/src/main/java/co/rsk/core/bc/BlockChainImpl.java#L186): Method co.rsk.core.bc.BlockChainImpl.internalTryToConnect(Block) appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by donequis** [comment]
If the idea is to fix TxPool shouln't TxPool check for the increase on total difficulty instead of changing the listener interface?

**Comment by tinchou** [comment]
@donequis that is already handled by BlockChainImpl, and that's when you get an `IMPORTED_BEST`. I agree that refactoring would be nice, but maybe as a different task.

This basically rolls back an unwanted change from https://github.com/rsksmart/rskj/pull/549, while enabling other listeners to also benefit from this interface change.

**Comment by tinchou** [comment]
This is superseded by #567. We need to rethink how we handle our listeners.

**Pull request closed without merging**
