### PR TITLE
Update signature

### PR DESCRIPTION
**Pull request by bcodesido**
Update Signature

## Description
Signature used for sign the `configure.sh` file was updated.

## Motivation and Context
The old signature expired and we created, uploaded and configure a new one.

*ci:rskj-400-rc-ver*

### CODE REVIEW

**Comment by aeidelman** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Comment by Vovchyk** [comment]
pipeline:run

**Review by Vovchyk — APPROVED** [review]

**Pull request merged**
