### PR TITLE
[RSKIP218] - New fee rewards address for the RSK Core Developers Fund

### PR DESCRIPTION
**Pull request by fedejinich**
## Description

Implementing [RSKIP218](https://github.com/rsksmart/RSKIPs/pull/218): New fee rewards address for the RSK Core Developers Fund

## Motivation and Context

Filling the missing gaps from this [old PR](https://github.com/rsksmart/rskj/pull/1317)

## How Has This Been Tested?

Run the entire test suite, and also added a unit test for REMASC.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Requires Activation Code (Hard Fork)

* **Other information**:

### CODE REVIEW

**Review by Vovchyk — APPROVED** [review]

**Comment by fedejinich** [comment]
just rebased

**Comment by fedejinich** [comment]
pipeline:run

**Comment by fedejinich** [comment]
pipeline:run

**Comment by fedejinich** [comment]
pipeline:run

**Comment by fedejinich** [comment]
pipeline:run

**Review by ajlopezrsk — APPROVED** [review]

**Pull request merged**
