### PR TITLE
Fix issue where calleeGas would be less than the stipend

### PR DESCRIPTION
**Pull request by tinchou**
Fixed issue with CALL that wouldn't pass at least the minimum stipend when the remaining gas was lower than that.

Sorry there's no tests, but I couldn't reproduce it yet.

### CODE REVIEW

**Comment by rskops** [comment]
SonarQube analysis reported 196 issues
* ![MAJOR][MAJOR] 52 major
* ![MINOR][MINOR] 89 minor
* ![INFO][INFO] 55 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [VM.java#](https://github.com/rsksmart/rskj/blob/8d094d81e416f8f82561767db2fe817e30e92eb1/rskj-core/src/main/java/org/ethereum/vm/VM.java#): This file has 1,353 lines, which is greater than 1,000 authorized. Split it into smaller files. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [VM.java#L106](https://github.com/rsksmart/rskj/blob/8d094d81e416f8f82561767db2fe817e30e92eb1/rskj-core/src/main/java/org/ethereum/vm/VM.java#L106): Rename "gasCost" which hides the field declared at line 162. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. ![MAJOR][MAJOR] [VM.java#L180](https://github.com/rsksmart/rskj/blob/8d094d81e416f8f82561767db2fe817e30e92eb1/rskj-core/src/main/java/org/ethereum/vm/VM.java#L180): Either log or rethrow this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [VM.java#L206](https://github.com/rsksmart/rskj/blob/8d094d81e416f8f82561767db2fe817e30e92eb1/rskj-core/src/main/java/org/ethereum/vm/VM.java#L206): Method org.ethereum.vm.VM.doADD() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [VM.java#L222](https://github.com/rsksmart/rskj/blob/8d094d81e416f8f82561767db2fe817e30e92eb1/rskj-core/src/main/java/org/ethereum/vm/VM.java#L222): Method org.ethereum.vm.VM.doMUL() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [VM.java#L237](https://github.com/rsksmart/rskj/blob/8d094d81e416f8f82561767db2fe817e30e92eb1/rskj-core/src/main/java/org/ethereum/vm/VM.java#L237): Method org.ethereum.vm.VM.doSUB() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [VM.java#L252](https://github.com/rsksmart/rskj/blob/8d094d81e416f8f82561767db2fe817e30e92eb1/rskj-core/src/main/java/org/ethereum/vm/VM.java#L252): Method org.ethereum.vm.VM.doDIV() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [VM.java#L267](https://github.com/rsksmart/rskj/blob/8d094d81e416f8f82561767db2fe817e30e92eb1/rskj-core/src/main/java/org/ethereum/vm/VM.java#L267): Method org.ethereum.vm.VM.doSDIV() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [VM.java#L282](https://github.com/rsksmart/rskj/blob/8d094d81e416f8f82561767db2fe817e30e92eb1/rskj-core/src/main/java/org/ethereum/vm/VM.java#L282): Method org.ethereum.vm.VM.doMOD() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [VM.java#L297](https://github.com/rsksmart/rskj/blob/8d094d81e416f8f82561767db2fe817e30e92eb1/rskj-core/src/main/java/org/ethereum/vm/VM.java#L297): Method org.ethereum.vm.VM.doSMOD() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by rskops** [comment]
SonarQube analysis reported 198 issues
* ![MAJOR][MAJOR] 52 major
* ![MINOR][MINOR] 90 minor
* ![INFO][INFO] 56 info

#### Top 10 issues

1. ![MAJOR][MAJOR] [VM.java#](https://github.com/rsksmart/rskj/blob/dce9c3c7d453afe074a180c9af52aface498314e/rskj-core/src/main/java/org/ethereum/vm/VM.java#): This file has 1,386 lines, which is greater than 1,000 authorized. Split it into smaller files. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [VM.java#L106](https://github.com/rsksmart/rskj/blob/dce9c3c7d453afe074a180c9af52aface498314e/rskj-core/src/main/java/org/ethereum/vm/VM.java#L106): Rename "gasCost" which hides the field declared at line 162. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AHiddenFieldCheck)
1. ![MAJOR][MAJOR] [VM.java#L180](https://github.com/rsksmart/rskj/blob/dce9c3c7d453afe074a180c9af52aface498314e/rskj-core/src/main/java/org/ethereum/vm/VM.java#L180): Either log or rethrow this exception. [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [VM.java#L206](https://github.com/rsksmart/rskj/blob/dce9c3c7d453afe074a180c9af52aface498314e/rskj-core/src/main/java/org/ethereum/vm/VM.java#L206): Method org.ethereum.vm.VM.doADD() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [VM.java#L222](https://github.com/rsksmart/rskj/blob/dce9c3c7d453afe074a180c9af52aface498314e/rskj-core/src/main/java/org/ethereum/vm/VM.java#L222): Method org.ethereum.vm.VM.doMUL() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [VM.java#L237](https://github.com/rsksmart/rskj/blob/dce9c3c7d453afe074a180c9af52aface498314e/rskj-core/src/main/java/org/ethereum/vm/VM.java#L237): Method org.ethereum.vm.VM.doSUB() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [VM.java#L252](https://github.com/rsksmart/rskj/blob/dce9c3c7d453afe074a180c9af52aface498314e/rskj-core/src/main/java/org/ethereum/vm/VM.java#L252): Method org.ethereum.vm.VM.doDIV() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [VM.java#L267](https://github.com/rsksmart/rskj/blob/dce9c3c7d453afe074a180c9af52aface498314e/rskj-core/src/main/java/org/ethereum/vm/VM.java#L267): Method org.ethereum.vm.VM.doSDIV() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [VM.java#L282](https://github.com/rsksmart/rskj/blob/dce9c3c7d453afe074a180c9af52aface498314e/rskj-core/src/main/java/org/ethereum/vm/VM.java#L282): Method org.ethereum.vm.VM.doMOD() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)
1. ![MAJOR][MAJOR] [VM.java#L297](https://github.com/rsksmart/rskj/blob/dce9c3c7d453afe074a180c9af52aface498314e/rskj-core/src/main/java/org/ethereum/vm/VM.java#L297): Method org.ethereum.vm.VM.doSMOD() appears to call the same method on the same object redundantly [rule](https://jenkins.rsklabs.io/sonar/coding_rules#rule_key=fb-contrib%3APRMC_POSSIBLY_REDUNDANT_METHOD_CALLS)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by tinchou** [comment]
@donequis I added one test here: https://github.com/rsksmart/rskj/pull/286/files#diff-b5d090bca002ef9ef0445d0c62bb2190R82

**Comment by tinchou** [comment]
@SergioDemianLerner friendly ping to let you know I'm blocked by your review.

**Pull request merged**
