### PR TITLE
Implementation of RSKIP271, batching pegouts

### PR DESCRIPTION
**Pull request by marcos-iov**
*fit:disable-pegout-batching*

### CODE REVIEW

**Comment by kelvinator07** [comment]
pipeline:run

**Comment by kelvinator07** [comment]
pipeline:run

**Comment by josedahlquist** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by marcos-iov** [comment]
pipeline:run

**Comment by josedahlquist** [comment]
pipeline:run

**Comment by lucasvuotto** [comment]
pipeline:run

**Comment by kelvinator07** [comment]
pipeline:run

**Comment by lucasvuotto** [comment]
pipeline: run

**Review by josedahlquist — APPROVED** [review]

**Pull request merged**
